### ISSUE TITLE
Add possibility to pass custom http.Client

### ISSUE THREAD

**Issue by avarabyeu** [go-resty/resty#100]
Here is use case. I need to configure oauth2 authentication. I'ld like go's `"golang.org/x/oauth2/clientcredentials"` to do all the job:

```go
cfg := clientcredentials.Config{
		ClientID:     conf.ClientID,
		ClientSecret: conf.ClientSecret,
		TokenURL:     oauth2TokenURL,
		Scopes:       []string{oauth2Scope},
	}
client *http.Client := cfg.Client(context.Background())
```

I think add smth like 
```go
func (c *Client) SetClient(hc *http.Client) *Client {
	c.httpClient = hc
	return c
}
```
would be very useful.

**Comment by jeevatkm** [comment]
@avarabyeu is `http.RoundTripper` not satisfying oauth2? Reference #89 

Please let me know.

**Comment by avarabyeu** [comment]
@jeevatkm it should, thank you for the comment. But anyway whether it would be useful to pass custom client with some specific network configs (like connection timeouts,etc)

**Comment by jeevatkm** [comment]
@avarabyeu thank you, I'm planning to add option of setting custom client.

I was trying to clarify, without this option is it preventing you from using resty. Based on that I can prioritize this enhancement.

**Comment by jeevatkm** [comment]
@avarabyeu added `NewWithClient` method, commit 6d988279fbd02f7e528a54f94401eba048c5be87

**Comment by avarabyeu** [comment]
@jeevatkm cool! thanks!

**Comment by jeevatkm** [comment]
@avarabyeu you're welcome.
