### ISSUE TITLE
Option to set Path Params

### ISSUE THREAD

**Issue by ramtg** [go-resty/resty#103]
It'd would be helpful to have an option to specify placeholders for path parameter names  and a way to specify values for them through a map much like SetQueryParams.

**Comment by jeevatkm** [comment]
@ramtg Did you mean this one?

URL:
```
/v1/users/{id}
```
Then user provides key-value pair via something like:
```go
resty.SetPathParams(map[string]string{
  "id": "sample@sample.com",
})
```

Then URL becomes:
```
/v1/users/sample@sample.com
```

**Comment by ramtg** [comment]
@jeevatkm . Correct.  It'd be nice if multiple path params could be supported anywhere in the URL.
(something along the lines of  http://square.github.io/retrofit/ )

**Comment by jeevatkm** [comment]
@ramtg I got the understanding of this feature. Will work on it. Thanks.

**Comment by ramtg** [comment]
@jeevatkm  Thank you!

**Comment by jeevatkm** [comment]
@ramtg Path params feature have been implemented at  branch 
`path-params` - 110f66a2f7595f1e263b65d0cf8e4b30dd2987bb  and PR #117

Please give it a try and let me know, thanks.

**Comment by jeevatkm** [comment]
Merged to edge 😄
