### ISSUE TITLE
[Feature] front-end for demo

### ISSUE THREAD

**Issue by roscopecoltran** [go-resty/resty#104]
Hey guys,

Hope you are all well !

Would be awesome to plug resty with a front-end framework like [aio_admin](https://github.com/aio-libs/aiohttp_admin) for python but for golang.

- React: https://github.com/marmelab/admin-on-rest
   - Custom client: https://marmelab.com/admin-on-rest/RestClients.html#writing-your-own-rest-client
- AngularJS: https://github.com/marmelab/ng-admin

The only solutions, I found for Golang, are https://github.com/qor/admin and https://github.com/ponzu-cms/ponzu for the moment.

Would be great to have something flexible and performent using [gopherjs](https://github.com/gopherjs/gopherjs) or[ gopherjs-vue](https://github.com/oskca/gopherjs-vue).

**Question:**
Do you see a way to bridge a json schema from resty to write the front-end js config with no headaches ? are any other flexible approaches from your point of view ? 

Cheers,
Richard

**Comment by jeevatkm** [comment]
@roscopecoltran `resty` library can be used with any Go projects. 

It seems you're looking for HTTP/REST client library for JS (front-end based applications)? If yes then please use any JS library OR give it try on Go to JS conversion using `gopherjs` compiler and share your experience with community.

**Comment by jeevatkm** [comment]
Closing it, thanks.
