### ISSUE TITLE
Automatic unmarshalling is not working correctly

### ISSUE THREAD

**Issue by sravanpatro** [go-resty/resty#105]
Hi,

I'm trying to decode the Json response of Get(url) and extract the specific field say id. 
But only bool type getting populated correctly. Rest of fields are not set. 
Response status is 200 OK   
Am i missing something?

Code Snippet:
```go
type sessionInfo struct {
    id string   `json:"id"`
    modified bool `json:"modified"`
    username string `json:"username"`
    updated uint  `json:"updated"`
    started uint  `json:"started"`
    description string  `json:"description"`
}

resp, err := resty.R().
SetHeader("Accept", "application/json").
SetHeader("Content-Type", "application/json").
SetBasicAuth("username","password").
SetResult(&sessionInfo{}).
Get(url)

result := (*resp.Result().(*sessionInfo))
fmt.Printf("\n Get Response: %+v", result)  ------------> only bool value is updated. 
fmt.Printf("\nResponse Status: %v", resp.Status())   ---> This is OK
fmt.Printf("\nResponse Body: %v", resp)  ---------------> This is also OK
```

Output:
Get Response: {id: modified:false username: updated:0 started:0 description:}
Response Status: 200 OK
Response Body: {"session":[{"id":"ED595C92EC75F81C","username":"xxxxx","description":"","started":"1510777160","updated":"1510777160","modified":"false"}],"message":" "}

**Comment by jeevatkm** [comment]
@sravanpatro It seems non of the fields is populated due to your incorrect `struct` definition.

In Go Fields have to be Exported for JSON marshaling and unmarshalling, like below:

```go
type sessionInfo struct {
    ID string   `json:"id"`
    Modified bool `json:"modified"`
    Username string `json:"username"`
    Updated uint  `json:"updated"`
    Started uint  `json:"started"`
    Description string  `json:"description"`
}
```

More Info: https://golang.org/pkg/encoding/json/

**Comment by sravanpatro** [comment]
I tried the structure given by you, But still seeing the same result.

**Comment by jeevatkm** [comment]
@sravanpatro I have pointed you to the right direction (i.e. Exported fields, still your struct has data type problems). You have to create a structure based on your JSON data. Above given links has examples for JSON marshaling and unmarshaling.

Please read more about JSON and create go `struct` based on your JSON data.
```json
{
	"session": [{
		"id": "ED595C92EC75F81C",
		"username": "xxxxx",
		"description": "",
		"started": "1510777160",
		"updated": "1510777160",
		"modified": "false"
	}],
	"message": " "
}
````

This issue is not a resty related. It is typical JSON issue/work you have to do.

**Comment by jeevatkm** [comment]
@sravanpatro I hope you have learned JSON handing in Go. Thank you.
