### ISSUE TITLE
redirect with method

### ISSUE THREAD

**Issue by dwdcth** [go-resty/resty#106]
I recently ran into a problem when redirect with restful method.
So,I just add a line in "checkHostAndAddHeaders" function.
I think it will be useful for others.
```go
func checkHostAndAddHeaders(cur *http.Request, pre *http.Request) {
	curHostname := getHostname(cur.URL.Host)
	preHostname := getHostname(pre.URL.Host)
	cur.Method = pre.Method  // add this maybe more flexible
	...
}
```

**Comment by jeevatkm** [comment]
@dwdcth Could you please describe the purpose of adding method info on redirect?

**Comment by dwdcth** [comment]
@jeevatkm Because some api have redirect
