### ISSUE TITLE
Clarification on SetResult and Result API

### ISSUE THREAD

**Issue by djui** [go-resty/resty#110]
It is not clear to me why one would use `Request.SetResult()` and `Response.Result()` or `Request.SetError()` and `Response.Error()` instead of a simple and idiomatic:

```go
package main

import (
	"fmt"

        "github.com/go-resty/resty"
)

type user struct {
        UserID int `json:"userId"`
        ID int `json:"id"`
        Title string `json:"title"`
        Body string `json:"body"`
}

func main() {
        var u user
        _, _ := resty.R().
                SetResult(&u).
                Get("https://jsonplaceholder.typicode.com/posts/1")
        fmt.Printf("%#v\n", u)
}
```

```go
main.user{UserID:1, ID:1, Title:"sunt aut facere repellat provident occaecati excepturi optio reprehenderit", Body:"quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"}
```

Could you either elaborate on that either here in the issue or in the README?

**Comment by jeevatkm** [comment]
@djui I understand what you mean. Actually resty `SetResult` and `SetError` takes an input and processes the type of object, not a object reference. That's why `Result` and `Error` methods retrieve the actual unmarshalled object. This is how initially designed/implemented.
