### ISSUE TITLE
Is it OK to share connections between Goroutines?

### ISSUE THREAD

**Issue by svenax** [go-resty/resty#112]
I am trying to use a global connection to make multiple REST API calls to the same server from a number of spawned Goroutines. I attached a rate limiter to `OnBeforeRequest` to avoid flooding the server. Everything seems to work fine if I set the allowed rate fairly low, but if I crank it up the calls start to fail. This can very likely be a problem with the called API endpoint, so I just wanted to check if this kind of usage is supposed to work at all?

**Comment by jeevatkm** [comment]
Yes, resty is safe to use with goroutines. It is recommend to keep resty client per server.

**Comment by jeevatkm** [comment]
I'm closing it
