### ISSUE TITLE
Is it possible to add resty.SetDebugBodyLimit on production V1.0 ?

### ISSUE THREAD

**Issue by RenathoAzevedo** [go-resty/resty#113]
I would like to have resty.SetDebugBodyLimit on production version of resty, is it possible?
If not, will we have a new production release soon ? 

and if it possible I would like to set my prefix to resty.Client.Log in Debug Mode, but it gets overwrited by 
c.enableLogPrefix(). could it be avaible ?

**Comment by jeevatkm** [comment]
@RenathoAzevedo I'm planning to add #103 and #109 then make a release next week.

I will include your Log prefix enhancement too.

**Comment by RenathoAzevedo** [comment]
Great, Thank you!

**Comment by jeevatkm** [comment]
`func (c *Client) SetLogPrefix(prefix string) *Client` method added.

It's done, will be released in `v1.1`
