### ISSUE TITLE
Trailing slash removed

### ISSUE THREAD

**Issue by lucadepaoli** [go-resty/resty#119]
After commit ad03978733316c, if a request is made with a trailing slash, it is removed in function `composeRequestURL ` (from util.go).
This is not expected, since there are many APIs that require trailing slashes to the endpoints.

**Comment by jeevatkm** [comment]
@lucadepaoli I understand, let me address that quickly and make an release. Thank you for notifying.

**Comment by jeevatkm** [comment]
@lucadepaoli I have fixed it, making release `v1.2`. Thank you.
