### ISSUE TITLE
Make Request.execute public

### ISSUE THREAD

**Issue by bmurphy1976** [go-resty/resty#12]
There are cases where we have to programmatically decide which http method to use when invoking an API.  While we can create a map of handler functions to call the various put/post/get/delete/options functions on a Request, it would be simpler if we could just pass the desired method to Execute directly, i.e:

```go
resp, err := resty.R().Execute(resty.POST, url)
```

vs what I have to do right now:

```go
type handler func(*resty.Request, string) (*resty.Response, error)

func get(r *resty.Request, url string) (*resty.Response, error) {
  return r.Get(url)
}

func post(r *resty.Request, url string) (*resty.Response, error) {
  return r.Post(url)
}

handlers := make(map[string]handler)
handlers[resty.GET] = get
handlers[resty.POST] = post
// etc

resp, err := handlers[resty.POST](resty.R(), url)

```

**Comment by jeevatkm** [comment]
I agree, it makes sense.

I have just released v0.3; looking at your need, I will bring this changes to master today itself (accessible via `github.com/go-resty/resty`) however will make a release later on via tag (accessible via `gopkg.in/resty.v0`).

is it okay?

**Comment by jeevatkm** [comment]
`Request.Execute` method is public now, available in master branch. Will be scheduled for release!

**Comment by bmurphy1976** [comment]
Can confirm, works great!  Thanks!

**Comment by jeevatkm** [comment]
Thanks!
