### ISSUE TITLE
Specific to Microsoft Graph (service providers): Re-ordered URL Query Params causes trouble

### ISSUE THREAD

**Issue by olihey** [go-resty/resty#123]
Hej,

I am working with Microsoft Graph and resty. Awesome so far but now I ran into an issue. I get download / upload URLs from the API and using them with resty always fails. The reason is that resty reorders the URLs query parameters.

For example this is the URL I get from Microsoft:
```
https://mycompany.sharepoint.com/personal/XXXXXXXX_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=ead1d0ed-XXX-XXX-XXX-abb7612b3146&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLC...HZEhwVnJ1d0NSUGVLaUpSaVNLRG5scz0&ApiVersion=2.0
```

but resty finally sends the following:
```
https://mycompany.sharepoint.com/personal/XXXXXXXX_onmicrosoft_com/_layouts/15/download.aspx?ApiVersion=2.0&Translate=false&UniqueId=ead1d0ed-XXX-XXX-XXX-abb7612b3146&tempauth=eyJ0eXAiOiJKV1QiLC...HZEhwVnJ1d0NSUGVLaUpSaVNLRG5scz0
```
I know that "technically" those two URLs express the same but the Microsoft Graph API seems to be picky about them. So after some debugging I found out that I can make this work with resty when I remove the `parseRequestURL` from the `beforeRequest` list.

Any chance we can make this an option? There is already an `SetDoNotParseResponse`. I am happy to contribute a `SetDoNotParseRequestURL` as PR. Would that be okay?

**Comment by jeevatkm** [comment]
> Microsoft Graph API seems to be picky about them.

@olihey sad to hear that. Thank you for sharing your experience. Technically `SetDoNotParseResponse` behavior, we cannot be compare with this. 

To bring better experience; let me have a look and get back to you.

**Comment by jeevatkm** [comment]
@olihey I have done my analyzes. As you know per RFC there is no order preserve requirement. 

Also standard package [url.Values.Encode(...)](https://golang.org/pkg/net/url/#Values.Encode) sorts query params alphabetically.

To bring balance and better resty user experience. I have enhanced the resty to preserve query string order partially, it means "resty will preserve query string order on provided URL not on `SetQuery*` methods". This enhancement is available at branch [preserve-query-string-order-partially](https://github.com/go-resty/resty/tree/preserve-query-string-order-partially)

Please give it try and share your feedback. Then it will be part of `v1.3` release.

**Comment by olihey** [comment]
The fix works for me. Thanks a lot 👍 
But I am a bit torn about this. I also read a bit into this and for me the issue actually lies in the Microsoft Graph API and not resty. I opened an issue at Microsoft and looking forward to what they say ( https://github.com/OneDrive/onedrive-api-docs/issues/792 )

If you don't see any issue in merging the changes you made, then please go for it.

**Comment by jeevatkm** [comment]
@olihey Thanks I'm glad to merge this enhancement. It is fully compatible with RFC and previous resty versions too.

**Comment by olihey** [comment]
Great, thanks again for the quick help!

**Comment by jeevatkm** [comment]
Merged 😄
