### ISSUE TITLE
Missing query params on relative path request

### ISSUE THREAD

**Issue by Eraac** [go-resty/resty#131]
Hello,

I found a weird bug (or maybe an error by me)

I have 2 versions of resty on local
- 00cb083b8cdc8b0fb1e1f5ebe24bbc23e0ff0cf6 <- have the bug
- 9ac9c42358f7c3c69ac9f8610e8790d7c338e85d <- no bug

Code for reproduce the error

```go
package main

import "gopkg.in/resty.v1"

func main() {
	c := resty.SetHostURL("https://google.com").SetDebug(true)

	c.R().Get("/test?foo=bar")
}
```

Query param foo=bar disappears with the latest version of resty, but not with commit 9ac9c42358f7c3c69ac9f8610e8790d7c338e85d

I think error come from this line: 
https://github.com/go-resty/resty/blob/master/middleware.go#L40

**Comment by jeevatkm** [comment]
@Eraac Thanks for reporting it. I will have a look and get back to you.

**Comment by jeevatkm** [comment]
@Eraac I believe found the commit which could have caused it.

* Up to this commit fc8cd4547db65ea4e402a895471cd93aeb6e0a82 - working fine
* And this commit ad03978733316c626c1ca7af03ff35326b04ac54 onwards - we have an issue

With your sample program. I will work on it and then ping you.

**Comment by jeevatkm** [comment]
@Eraac Sorry missed to mention in previous comment. You're correct, issue come from this line. Thanks.

https://github.com/go-resty/resty/blob/master/middleware.go#L40

**Comment by jeevatkm** [comment]
@Eraac Issue fixed, again thanks for reporting it.  

After PR merge `edge` version is good to go and also I will be making a `v1.3` release and tag today

**Comment by jeevatkm** [comment]
Merged 😄
