### ISSUE TITLE
Error Handling Status > 399

### ISSUE THREAD

**Issue by ggalihpp** [go-resty/resty#139]
So I have read that 
* If status code is between 200 and 299 considered as success, you can retrieve via response.Result()
* If status code is greater than 399 considered as failure/error, you can retrieve via response.Error() 

However, I use this code:
![image](https://user-images.githubusercontent.com/28330810/38402731-7d194230-3988-11e8-91f3-1b1954b5415b.png)

I expect when status code is greater than 399 its filled the "err" but its not. So the code is move on and send resp.Result()

so the question is:
1. How the err handled the failure?
2. If its not possible to fill the 'err', how to read the status code of the response?

Thanks in advance, sorry to filling this question in issue.

**Comment by jeevatkm** [comment]
@ggalihpp 

* In your code you're missing to set an error type like you did for result. Please refer here https://godoc.org/github.com/go-resty/resty#Request.SetError 
* To get status code - you just call `resp.StatusCode()` - https://godoc.org/github.com/go-resty/resty#Response.StatusCode

I hope it helps!

**Comment by ggalihpp** [comment]
@jeevatkm 

Thank you for the fast response, I'll try to fix my code. cheers

**Comment by jeevatkm** [comment]
@ggalihpp Closing it, If you have issues, ping here.
