### ISSUE TITLE
Include bazel-friendly BUILD file

### ISSUE THREAD

**Issue by paradoxengine** [go-resty/resty#140]
It would be great to be able to use resty from a bazel project, and that's much simpler if there is a BUILD file, as one can just point to the git repo and fetch resty and dependencies.

I've got a pull request ready for this, but wanted to check how amenable you were to the request before just sending it out.

**Comment by jeevatkm** [comment]
@paradoxengine I saw your message last night while I going to bed. I was fleeing very sleepy.

Currently I don't have insights about Bazel build, I will read about it.

**Comment by jeevatkm** [comment]
@paradoxengine Bazel PR merged to master 😄
