### ISSUE TITLE
`createClient` overrides http.Transport

### ISSUE THREAD

**Issue by turboezh** [go-resty/resty#146]
This line overrides Transport in custom http.Client.
https://github.com/go-resty/resty/blob/7d81d5596d405bcc25da77590cfec78f31e56293/default.go#L300
I think this line should be removed, it has no sense because transport already embedded in client.

In my case I lost proxy settings from my own http.Client.

**Comment by jeevatkm** [comment]
@turboezh Nice catch, thanks. It seems I missed this part when I introduced feature of accepting client. I will correct it.

**Comment by jeevatkm** [comment]
@turboezh I have corrected it on edge, to be released in `v1.5`. Thanks.
