### ISSUE TITLE
Add mock example to read me

### ISSUE THREAD

**Issue by RanAbram** [go-resty/resty#148]
Hey,

Lately i was struggling with mocking `resty` calls.
Would you mind if i open PR for updating the read me file to show
example of how to mock those calls?

Something like the example i added to `httpmock` library?
https://github.com/jarcoal/httpmock/pull/39

@jeevatkm

**Comment by jeevatkm** [comment]
@RanAbram Feel free to send the PR for examples. Also If you see any improvements can be made to readme. Thank you.

**Comment by jeevatkm** [comment]
PR is merged, Thank you @RanAbram
