### ISSUE TITLE
Unmarshaling does not seem to be working for me.

### ISSUE THREAD

**Issue by bimargulies** [go-resty/resty#152]
I have this object:

```
type PingResponse struct {
	Mock        bool `json:"mock"`
	CreateCount int  `json:"createCount"`
	DeleteCount int  `json:"deleteCount"`
}
```

And I return it from a GET handler with content-type `application/json`.

I call with Resty:

```
resp, err := resty.R().
		SetResult(PingResponse{}).
		Get(s.url + "/ping")
	require.NoError(t, err)
	if resp.StatusCode() != http.StatusOK {
		t.Fatalf("/ping returned status %d", resp.StatusCode())
	}

	respMsg := resp.Result().(*PingResponse)
	golog.Printf("ping: %v mock %v create %d delete %d",
		string(resp.Body()),
		respMsg.Mock, respMsg.CreateCount, respMsg.DeleteCount)
```

and the respMsg object ends up with default values for all of the fields, not the values from the json. If I look at `Body()`, it is correct.

**Comment by jeevatkm** [comment]
@bimargulies Typically auto unmarshaling works based on response status code.

### From godoc

* `SetResult` method is to register the response `Result` object for automatic unmarshalling in the RESTful mode if response status code is between 200 and 299 and content type either JSON or XML.
* `SetError` method is to register the global or client common `Error` object into go-resty. It is used for automatic unmarshalling if response status code is greater than 399 and content type either JSON or XML. Can be pointer or non-pointer.

### I have created test program for you

```go
package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"

	"gopkg.in/resty.v1"
)

type PingResponse struct {
	Mock        bool `json:"mock"`
	CreateCount int  `json:"createCount"`
	DeleteCount int  `json:"deleteCount"`
}

func main() {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodGet {
			switch r.URL.Path {
			case "/ping":
				w.Header().Set("Content-Type", "application/json")
				_ = json.NewEncoder(w).Encode(PingResponse{
					Mock:        true,
					CreateCount: 345,
					DeleteCount: 937,
				})
			}
		}
	}))

	resp, _ := resty.R().
		SetResult(PingResponse{}).
		Get(ts.URL + "/ping")

	pingRes := resp.Result().(*PingResponse)
	fmt.Printf("\n%#v\n", pingRes)
}
```
### Output

```
$ go run restytry.go

&main.PingResponse{Mock:true, CreateCount:345, DeleteCount:937}
```

I hope it helps.

**Comment by bimargulies** [comment]
Thank you for writing this up. I am perplexed; this is essentially the same as what's going on in my code, and yet my response comes up empty. I'll have to debug in and see what I can figure out.

**Comment by jeevatkm** [comment]
@bimargulies You could use `resty.SetDebug(true)` for debugging, its helpful one. Let me know I'm glad to assist.

**Comment by bimargulies** [comment]
I had a stray call to WriteHeader on the server side that discarded my content type. Thanks for the help!

**Comment by jeevatkm** [comment]
You're welcome.

**Comment by jonesnc** [comment]
If you're getting here from google, my issue was my struct's names were lowercase, and I had to change them to start with an uppercase letter. See also https://github.com/go-resty/resty/issues/162#issuecomment-399742110
