### ISSUE TITLE
How can I set a HOST for request?

### ISSUE THREAD

**Issue by mail2fish** [go-resty/resty#154]
There is  a vhost server IP.  We like to access it with a host name which  like www.example.com.

Usually we can set a Host header in request, but it didn't work for golang http request.

So could you add a special method for the matter?

**Comment by jeevatkm** [comment]
@mail2fish This is known issue in the Go http client golang/go/issues/7682 however there is a workaround.

Use [`resty.SetPreRequestHook()`](https://godoc.org/github.com/go-resty/resty#SetPreRequestHook) to set Host value.

For example:

```go
resty.SetPreRequestHook(func(c *resty.Client, r *resty.Request) error {
	r.RawRequest.Host = "www.example.com"
	return nil
})
```

Can you try and please let me know?

**Comment by jeevatkm** [comment]
Or via classic approach is using `hosts` file mapping of target-ip with host address. Then make with requests with mapped address.

**Comment by mail2fish** [comment]
@jeevatkm thanks for your answer.  That's worked. But I  think that is convenient for developers if there is a shortcut for this matter.  In my situation, I developed in the localhost, and don't want to change my hosts file because I have to access that host by a browser.

Thanks again, That hook have solved my problem.

**Comment by jeevatkm** [comment]
@mail2fish thanks for confirming, I have created an issue to add built-in support for `Host` value. Coming in next release.

**Comment by jeevatkm** [comment]
@sorribas just did a PR for #155, its coming in `v1.7` release 😄

**Comment by waghcwb** [comment]
`net/http` was updated, and the new way is to set the `request.Host` field directly.

Reference: [golang/go@9dbb185](https://github.com/golang/go/commit/9dbb185fb6902d9a1308f709deaa67460ccd6c02)

```go
client.SetPreRequestHook(func(client *resty.Client, request *http.Request) error {
    request.Host = "<host>"
    return nil
})
```
