### ISSUE TITLE
REST error handling?

### ISSUE THREAD

**Issue by intel352** [go-resty/resty#157]
Is there any built-in logic for reacting to REST responses other than 2xx series?

**Comment by jeevatkm** [comment]
Yes, of-course.
*  Success scenario [Request.SetResult()](https://godoc.org/github.com/go-resty/resty#Request.SetResult) and [Response.Result()](https://godoc.org/github.com/go-resty/resty#Response.Result).
* Error scenario [Request.SetError()](https://godoc.org/github.com/go-resty/resty#Request.SetError) and [Response.Error()](https://godoc.org/github.com/go-resty/resty#Response.Error).
* Supports [RFC7807](https://tools.ietf.org/html/rfc7807) - `application/problem+json` & `application/problem+xml`

**Comment by intel352** [comment]
Thanks @jeevatkm, I missed that in my first perusal of the docs, cheers.
