### ISSUE TITLE
Add per request Proxy Support

### ISSUE THREAD

**Issue by jeevatkm** [go-resty/resty#16]
Add per request proxy support, preserving client level proxy setting value.

**Comment by jeevatkm** [comment]
Done!

**Comment by jeevatkm** [comment]
@lucaswxp do you mean golang removed the proxy option in the transport? Can you provide a reference for removal?

**Comment by lucaswxp** [comment]
@jeevatkm Hi, sorry no, I meant I can't see proxyURL in the Request struct in upsteam anymore, or am I missing something?

**Comment by jeevatkm** [comment]
@lucaswxp So you mean upstream is Resty, correct? I got confused by the word "upstream".
Yes, it got removed the request proxy in [`v0.11`](https://github.com/go-resty/resty/releases/tag/v0.11) in Mar 2017
