### ISSUE TITLE
[Answered] Possible leak on redirection error?

### ISSUE THREAD

**Issue by sudo-suhas** [go-resty/resty#163]
I was reading this article on Go gotchas and I think this could be relevant for `resty` - http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#close_http_resp_body. I don't think the response body is closed on redirection error. Is this something the consumer should take care of?

**Comment by jeevatkm** [comment]
@sudo-suhas Thanks for bringing your concern.

Go client does not expose response instance on redirects pipeline. It has to be caller responsibility i.e. `resty`.

Resty does closes the response body on all scenarios except DoNotParseResponse setting used -

* https://godoc.org/github.com/go-resty/resty#Client.SetDoNotParseResponse
* https://godoc.org/github.com/go-resty/resty#Request.SetDoNotParseResponse

I believe no leak in resty. If you could find a scenario please let me know, I'm glad to fix it.

Also I'm gonna review the response handling cases, will post if I find any 😄

**Comment by sudo-suhas** [comment]
> Go client does not expose response instance on redirects pipeline.

I tested this and I found that the article was correct about both response and error being present:

```go
package main

import (
	"fmt"

	resty "gopkg.in/resty.v1"
)

func main() {
	client := resty.New()
	client.SetHostURL("https://myhost.com")

	resp, err := client.R().Get("/my-endpoint")
	fmt.Printf("resp: %#v\n", resp)
	fmt.Println("error:", err)
	fmt.Println("resp.RawResponse == nil:", resp.RawResponse == nil)
	if resp.RawResponse != nil {
		fmt.Printf("resp.RawResponse: %#v\n", resp.RawResponse)
	}
}

```

Output:
```
resp: &resty.Response{Request:(*resty.Request)(0xc4200e2500), RawResponse:(*http.Response)(0xc420146000), body:[]uint8(nil), size:0, receivedAt:time.Time{wall:0xbec436091278ece0, ext:275346923, loc:(*time.Location)(0x87b000)}}
error: Get https://myhost.com/my-endpoint: auto redirect is disabled
resp.RawResponse == nil: false
resp.RawResponse: &http.Response{Status:"301 Moved Permanently", StatusCode:301, Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Content-Length":[]string{"178"}, "Location":[]string{"https://myhost.com/my-endpoint"}, "Connection":[]string{"keep-alive"}, "Server":[]string{"nginx"}, "Date":[]string{"Mon, 25 Jun 2018 03:25:08 GMT"}, "Content-Type":[]string{"text/html"}}, Body:(*http.bodyEOFSignal)(0xc4203440c0), ContentLength:178, TransferEncoding:[]string(nil), Close:false, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc42014c000), TLS:(*tls.ConnectionState)(0xc4203c68f0)}
```

**Comment by jeevatkm** [comment]
@sudo-suhas Thanks, what I meant was response instance on `checkRedirect pipeline`; not on typical request and response. 

Go client certainly closes response body on redirect fail and returns non-nil error and response.

For your reference: https://golang.org/pkg/net/http/#Client.Do

> On error, any Response can be ignored. A non-nil Response with a non-nil error only occurs when CheckRedirect fails, and even then the returned Response.Body is already closed.


It seems that article is not 100% correct on this use case.

**Comment by sudo-suhas** [comment]
Thanks for looking into it and sharing the relevant resources.

**Comment by jeevatkm** [comment]
@sudo-suhas You're very welcome. Always bring any question regarding resty. Its good to discuss and vet it out.
