### ISSUE TITLE
auto gzip will fail when Content-Encoding is gzip and content-length is zero

### ISSUE THREAD

**Issue by Jack47** [go-resty/resty#164]
there are some cases that the response's content-length is zero, in this case the below code will return err because failure of `gzip.NewReader`.
  https://github.com/go-resty/resty/blob/master/client.go#L804-L812
```go
		if strings.EqualFold(resp.Header.Get(hdrContentEncodingKey), "gzip") {
			if _, ok := body.(*gzip.Reader); !ok {
				body, err = gzip.NewReader(body)
				if err != nil {
					return response, err
				}
				defer closeq(body)
			}
		}
```
gzip.NewReader(body) will try to read the gzip header, so the call will fail.

I added some test cases and fixed this locally, I would like to pull a request to fix this if needed.

**Comment by jeevatkm** [comment]
@Jack47 Thank you for PR and addressing edge use case.
