### ISSUE TITLE
how to hit url without waiting response ?

### ISSUE THREAD

**Issue by youcandoit95** [go-resty/resty#170]
hello..

can somebody tell me , how to hit url both of GET or POST without waiting response ?

like hit n run 

thanks

**Comment by jeevatkm** [comment]
@youcandoit95 I believe your question is about approach. That approach applied for any operation in Go.   

Probably you may have to use goruntine to fire request.

**Comment by jeevatkm** [comment]
@youcandoit95 I hope you have figured out. If you have questions feel free to ask. I'm closing this one.
