### ISSUE TITLE
Posting body as JSON escapes the content

### ISSUE THREAD

**Issue by jryd** [go-resty/resty#177]
I am using this library to post a collection of products to an API.

Some of the names of the products have special characters (e.g '&') and these are escaped using the below request:

```
_, err := client.R().SetHeader("Content-Type", "application/json").
	SetBody(product).
	Post("API URL")
```

Example:

Product name is `Super Awesome & Fun`

When posted with the above example request, it is sent as `Super Awesome \u0026 Fun`.

Looking at this StackOverflow answer: https://stackoverflow.com/a/39079238/1739852 it looks like it is possible to disable the HTML escaping on the encoder:

e.g
```
enc := json.NewEncoder(os.Stdout)
enc.SetEscapeHTML(false)
```

Would it be possible to add this as a configuration option to disable the escaping of HTML?

**Comment by jeevatkm** [comment]
@jryd Sure, will add configuration to disable the escaping of HTML on JSON encoder/content-type.

**Comment by jeevatkm** [comment]
@jryd I have added an option `SetJSONEscapeHTML` to disable HTML escape. Could you please give it a try on branch `json-html-escape-opt` and let me know?  Then I will merge it master. Will be released in `v1.9.0`.

**Comment by jeevatkm** [comment]
Making a release.

**Comment by jryd** [comment]
@jeevatkm sorry for the late reply. Have tried using this in the v1.9.0 release and it looks like it is working well!

**Comment by jeevatkm** [comment]
@jryd No worries, Thanks for the confirmation.
