### ISSUE TITLE
stop redirect 

### ISSUE THREAD

**Issue by mostafadahab** [go-resty/resty#18]
can resty stop redirect without getting error ?! i tried custom redirectpolicy but still nil continue the redirect and error panic and not returning with response

**Comment by jeevatkm** [comment]
@mostafadahab can you please try from master branch and share your feedback?

**Comment by mostafadahab** [comment]
Good :+1: , worked for me and nice warnings

**Comment by jeevatkm** [comment]
I'm glad to hear that. Thanks for verification. This change will be released with v0.5 release.

BTW, how about the headers while redirect #19 ?
