### ISSUE TITLE
Debug mode dumps secret Auth headers

### ISSUE THREAD

**Issue by CallMeFoxie** [go-resty/resty#180]
Hi
it seems that enabling a debug mode dumps password right into the console making it hard to share the log with developers etc. IMHO there should be some filter to filter at least the basic auth/bearer tokens/... out.

```
---------------------- REQUEST LOG -----------------------
GET  /v1/services  HTTP/1.1
HOST   : 172.16.16.4:443
HEADERS:
                   Accept: application/json
            Authorization: Basic ZGV2OmRldg== <-- HIDE THIS
             Content-Type: application/json
               User-Agent: go-resty v1.7 - https://github.com/go-resty/resty
BODY   :
***** NO CONTENT *****
----------------------------------------------------------
```

Any opinions? :)
Thanks
Ashley

**Comment by jeevatkm** [comment]
@CallMeFoxie I agree, let's create an option in resty.

**Comment by jeevatkm** [comment]
@CallMeFoxie I have added the implementation fdc2f93ba79cc7e3951f70cbe6b765afa40e7b59, give it try and please let me know. I will merge it.
