### ISSUE TITLE
Allow user to edit request body string before the string is dumped to the debug logs

### ISSUE THREAD

**Issue by dapchen** [go-resty/resty#182]
Sometimes a request body contains sensitive information that user would like to mask out before they share the request log with other people. Can resty make a request body string editable before the string is dumped to the debug logs?

**Comment by jeevatkm** [comment]
@dapchen Its feasible to implement. 

I think its better to make generic implementation for handling debug log before logging, so that it would satisfy #180 too.

**Comment by jeevatkm** [comment]
@dapchen I have added the implementation fdc2f93ba79cc7e3951f70cbe6b765afa40e7b59, give it try and please let me know. I will merge it.

**Comment by dapchen** [comment]
@jeevatkm  I pulled in the  `debug-log-enhancement`. I was able to mask password in my request body. Thank you for making this enhancement!

**Comment by jeevatkm** [comment]
@dapchen Thank you for your feedback.
