### ISSUE TITLE
Error when attempting to use with golang 1.11

### ISSUE THREAD

**Issue by forrestdix** [go-resty/resty#183]
`go get -u gopkg.in/resty.v1`
`go get gopkg.in/resty.v1: unrecognized import path "gopkg.in/resty.v1" (parse https://gopkg.in/resty.v1?go-get=1: no go-import meta tags ())`

**Comment by forrestdix** [comment]
I also get an error when I attempt to use go 1.11 modules and use github.com/go-resty/resty directly.

`go: github.com/go-resty/resty@v1.9.1: parsing go.mod: unexpected module path "gopkg.in/resty.v1"`
`go: error loading module requirements`

**Comment by moorereason** [comment]
Try again.

See https://github.com/niemeyer/gopkg/issues/63

**Comment by forrestdix** [comment]
Seems to be working now. Thanks.

**Comment by jeevatkm** [comment]
Thank you @moorereason 

@forrestdix Glad to hear that its working for you.
