### ISSUE TITLE
Accept-Encoding: gzip with Content-Length: -1 and Chunked response not decoded

### ISSUE THREAD

**Issue by visualphoenix** [go-resty/resty#187]
There is a problem with https://github.com/go-resty/resty/issues/164

A gzipped chunked http response with a -1 content-length should be gunzipped.
Perhaps the patch meant to check if the Content-Length is 0 specifically?

https://github.com/go-resty/resty/blob/master/client.go#L814

https://golang.org/src/net/http/response_test.go#L133

Workaround for now is to set SetDoNotParseResponse(true) and manually handle the response.

**Comment by jeevatkm** [comment]
@visualphoenix Thanks for reporting an issue. I have looked at the PR too, I will accept it.

I would recommend you to NOT to add header manually for gzip (refer to #142). Or do you have any specific use case?
