### ISSUE TITLE
redirect with cookies and headers

### ISSUE THREAD

**Issue by mostafadahab** [go-resty/resty#19]
like other http libs for golang 
when redirect cookies disappear

**Comment by jeevatkm** [comment]
@mostafadahab - You may have to set HTTP mode to take advantage for cookiejar capability. Please have a look [here](https://godoc.org/github.com/go-resty/resty#Client.SetHTTPMode). Default mode is REST.

**Comment by mostafadahab** [comment]
Not only the cookies the headers also changed:
![image](https://cloud.githubusercontent.com/assets/10044038/11434212/23006c38-94da-11e5-9c10-a4074d19f3bc.png)
And when the resty follows request:
![image](https://cloud.githubusercontent.com/assets/10044038/11434218/37afb22e-94da-11e5-8c4e-bd696e6edee4.png)

**Comment by jeevatkm** [comment]
Thanks for inputs, will have a look and let you know.

**Comment by mostafadahab** [comment]
https://github.com/franela/goreq/issues/69

I think this will help

**Comment by jeevatkm** [comment]
@mostafadahab Thank you for your patient. I was bit occupied in the day work. 

Currently I'm working on this issue and other request from your end. I will update you!

**Comment by jeevatkm** [comment]
I went through given reference and https://github.com/golang/go/issues/4800 for redirect.

go-resty will add all the headers during a redirect for the same host. It is available in master. Can you please try and share you feedback on this issue?

**Comment by jeevatkm** [comment]
Did you get a chance to have a look? Thanks.

**Comment by mostafadahab** [comment]
I'll check this weekend

**Comment by jeevatkm** [comment]
Okay, sounds good.

**Comment by jeevatkm** [comment]
done!
