### ISSUE TITLE
Set Header with Accept-Encoding:gzip manually, but get uncompressed bytes from resp.body

### ISSUE THREAD

**Issue by foxluqi** [go-resty/resty#191]
When I upgrade resty, I found my previous project failed when I set Accept-Encoding:gzip in header manually. The response body is uncompressed bytes unless I remove the set header statement. Anybody encounter the same problem in newest version resty?
	c.SetHeaders(map[string]string{
		//"Accept-Encoding": "gzip, deflate",
		"Accept-Language": "en-US;q=1",
		"Accept":          "*/*",
		"Connection":      "keep-alive",
	})

**Comment by jeevatkm** [comment]
@foxluqi May I know what was the issue and how did you resolve it?
