### ISSUE TITLE
update references to point to gopkg.in/resty.v1

### ISSUE THREAD

**Issue by dmitris** [go-resty/resty#193]
Could you please modify the Godoc link in README (Godoc banner) to point to https://godoc.org/gopkg.in/resty.v1 instead of https://godoc.org/github.com/go-resty/resty?  Also if there are other similar (legacy) references, please replace them as well to be with the module value in `go.mod`.  It could be also useful to highlight in README.md that the canonical value to import the package is now `gopkg.in/resty.v1`.

**Comment by jeevatkm** [comment]
@dmitris This morning I saw the conversation on gopher slack. I believe this is related to that.

I will surely update the godoc and readme. Do you have an any other issues with go mod and resty besides godoc and readme?

FYI, in upcoming `resty v2` release, resty will not use `gopkg.in` .

**Comment by dmitris** [comment]
> Do you have an any other issues with go mod and resty besides godoc and readme?

No - thanks for your prompt response! 😄

**Comment by jeevatkm** [comment]
References updated 👍
