### ISSUE TITLE
no way to send Form Data other than string ?

### ISSUE THREAD

**Issue by michelson** [go-resty/resty#196]
Hi , is possible to send golang url.UrlValues to post ? I've seen that the methods to set parameters on posts (url-encoded) only accepts string .

**Comment by jeevatkm** [comment]
@michelson you could use this method `R().SetMultiValueFormData(param)`.

**Comment by jeevatkm** [comment]
@michelson Any updates?

**Comment by michelson** [comment]
Thanks @jeevatkm ! all good
