### ISSUE TITLE
header don't have clean

### ISSUE THREAD

**Issue by lockp111** [go-resty/resty#199]
If I have set some header  in first time,it will have value when I restry.R() it.
```
req :=resty.R()
// set header
if token!="" {
    req.SetHeader("XToken", token)
}
req.Post("xxxxxxx")
```
 `req` will send the last time `token`,when my `token` is ""

**Comment by lockp111** [comment]
```
fmt.Printf("%p",resty.R())
```
I can see some duplicate address

**Comment by jeevatkm** [comment]
@lockp111 `resty.R()` or `someclient.R()` always returns new instance on Request (refer to https://github.com/go-resty/resty/blob/master/client.go#L306-L320). There is no sharing of value between requests.

Could you please check at your end also use debug log of resty?
