### ISSUE TITLE
unsupported 'Body' type/value

### ISSUE THREAD

**Issue by codenoid** [go-resty/resty#208]
hi, i'm trying to send POST DATA with `application/x-www-form-urlencoded` type & the source from struct, but i got

My struct : 

```
type PostData struct {
	Id string `json:"id"`
	Number string `json:"number"`
}
```

Resty syntax : 

```
resp, err := resty.R().
  	SetHeader("Content-Type", "application/x-www-form-urlencoded").
  	SetBody(PostData{Id: "2",Number: "251"}).
  	SetResult(&ExpectedResult).    // or SetResult(AuthSuccess{}).
  	Post("http://localhost:5000")
```
Error : 

`unsupported 'Body' type/value`

**Comment by codenoid** [comment]
hmm, idk why, i'm always getting error when **i really want** use go-resty  **(from the deepest of my heart)**

**Comment by jeevatkm** [comment]
@codenoid It seems you have mixed up the usage. For form submission please refer to https://github.com/go-resty/resty#sample-form-submission

FYI, Resty does not support this way of form submission yet(content-type as `application/x-www-form-urlencoded` & body as `struct`) -

```go
SetHeader("Content-Type", "application/x-www-form-urlencoded").
SetBody(PostData{Id: "2",Number: "251"}).
```
