### ISSUE TITLE
Save & Re-Use session

### ISSUE THREAD

**Issue by codenoid** [go-resty/resty#210]
hi, currently i'm trying to login into `https://mbasic.facebook.com` save the current resty, and re-use the session, my current code : 

```
func main() {
	resty.SetRedirectPolicy(resty.FlexibleRedirectPolicy(20))

        // check is cookie with specified id exist ?

	// Cookies for all request
	resty.SetCookie(&http.Cookie{
	      Name:"go-resty",
	      Value:"This is cookie value",
	      Path: "/",
	      Domain: "facebook.com",
	      MaxAge: 36000,
	      HttpOnly: true,
	      Secure: false,
	    })

	// resp, err := resty.R().Get("https://mbasic.facebook.com")
	
	resp, err := resty.R().
	      SetFormData(map[string]string{
	        "email": "email@gmail.com",
	        "pass": "password",
	        "lsd": "AVqpZRkz",
	        "m_ts": "1547062998",
	      }).
	      Post("https://mbasic.facebook.com/login/device-based/regular/login/?refsrc=https%3A%2F%2Fmbasic.facebook.com%2F&amp;lwv=100&amp;refid=8")

	if err == nil {
               // success -> save cookie
		fmt.Println(resp)
	}
	fmt.Println(err)	
}
```

**Comment by codenoid** [comment]
actually not cookie, but session, sorry :smile:

**Comment by jeevatkm** [comment]
@codenoid First of all, is credentials you have put in the comment is real? if yes change your password. And going forward please do not put real credentials in the public forum.

Resty has cookie jar built-in; it will relay the cookies received from server in the next request for corresponding domains. If you know the Form post URL and know the required values, you can do it with resty.

Being said that resty is not test automation library. However you could develop one using resty.

Also `resty.SetDebug(true)` is your friend, make use of it for your development. It will help you to see what goes out in the request and what you receive from server.

**Comment by codenoid** [comment]
is there any example for cookie jar usage mister ?

**Comment by jeevatkm** [comment]
@codenoid Cookie jar is enabled by default in Resty.

**Comment by jeevatkm** [comment]
I'm closing this one.
