### ISSUE TITLE
Add method into struct `Request` to accept type `url.Values` for Query strings

### ISSUE THREAD

**Issue by jeevatkm** [go-resty/resty#213]
Refer to https://github.com/go-resty/resty/issues/166#issuecomment-406465002

**Comment by jeevatkm** [comment]
I have analysis, it seems there is method already exists in Resty to accept `url.values` for Query Parameters and Form Data. 

So I will do following changes, for easy understanding:
- Refactor method from `SetMultiValueQueryParams` to `SetQueryParamsFromValues`
- Refactor method from `SetMultiValueFormData` to `SetFormDataFromValues`

**Comment by jeevatkm** [comment]
It's done 😄

**Comment by moorereason** [comment]
This should be labeled as a breaking change.
