### ISSUE TITLE
Ordered Query Parameters

### ISSUE THREAD

**Issue by tiger5226** [go-resty/resty#220]
I have run into a very frustrating issue. I am communicating with an API that leverages HMAC signing. The problem is that given params A,G,F and `hmac_sign`, the url called by resty puts the params in alphabetical order, instead of the order I have set them. HMAC signing, requires you to sign something. In this case the url + parameters. However, once I make the call, go-resty reorders the params. So now the url signature is wrong.

It is using the `url.Values` package. So that is pretty official. Not sure how this is handled with HMAC url signing.

**Comment by jeevatkm** [comment]
@tiger5226 I'm sorry about the delayed response.

Typically in Go lang, query parameter will be always alphabetical order (https://golang.org/pkg/net/url/#Values.Encode), resty uses this method.

For your HMAC sign requirement. One workaround I could think is compose your URL with ordered query parameter and supply the URL string into Resty. Do not use Resty query parameter composing methods for your use case.

Could you try it out and let me know?

**Comment by tiger5226** [comment]
Yeah, that is how I solved the problem for now. Feels a bit hacky so I wanted to flag it in case you wanted to provide an alternative for HMAC signing. I agree its standard in the golang package. Maybe an issue for golang repo? Or the API requiring the signing.

**Comment by jeevatkm** [comment]
@tiger5226 Thanks for the confirmation. I will think of one; however, it will be the same as what you did at your end happening inside the Resty 😄.

**Comment by tiger5226** [comment]
I don't know why they choose to sort it, besides being required to do so. They are using a `map[string]string` to represent the parameters. This means that the map can only return a random order since golang does not promise ordering. So they probably sort it for it to be deterministic. The problem is everything outside of golang does not do this. They should really just be using a slice so they can preserve the order rather than being forced into a box with maps. Feels like a case of over-optimization.

**Comment by jeevatkm** [comment]
@tiger5226 I don't know either, probably for deterministic behavior. The `url.Values` data type is `map[string][]string`.

I'm closing this one, thanks.

**Comment by voronovmaksim** [comment]
I faced with the issue also, i understood your answer, but anyway, I hope the bug will be fixed on resty side some day)

**Comment by Harnoor-se7en** [comment]
ordered query param is one of the worst decisions the Golang devs made.
