### ISSUE TITLE
how to get request header in format string ?

### ISSUE THREAD

**Issue by youcandoit95** [go-resty/resty#222]
hello.. can we get request header in string format return ?

like resty.Request.URL 

thank you

**Comment by moorereason** [comment]
See https://godoc.org/gopkg.in/resty.v1#Request

```go
type Request struct {
    URL        string
```

**Comment by jeevatkm** [comment]
@moorereason Thanks for the answer.

@youcandoit95 You could access all the request related values (such as headers, url, etc.). The best place to learn more is godoc as mentioned by @moorereason .
