### ISSUE TITLE
how to get all response header in string format ?

### ISSUE THREAD

**Issue by youcandoit95** [go-resty/resty#223]
hello i need feature that can provide get all response header in string format  for logging requirement ? can somebody help me ?

**Comment by moorereason** [comment]
See https://godoc.org/gopkg.in/resty.v1#Response.Header and https://godoc.org/net/http#Header.

**Comment by jeevatkm** [comment]
@moorereason Thanks for the answer.

**Comment by youcandoit95** [comment]
thankss
