### ISSUE TITLE
Create multiple http clients with different internet connections

### ISSUE THREAD

**Issue by AndrusGerman** [go-resty/resty#224]
I would like to do this in resty, I know that it is possible but I do not have the knowledge for her this could someone leave me an example.
I have two lan connections and I want to make requests with both in the same script and I propose that they add functionality similar to the one in the example

```
package main

import (
	"fmt"

	resty "gopkg.in/resty.v1"
)
//two lan connections on the same computer

func main() {
	// Default request (My Default Conection: eth0: red:localhost-187.3.4.XX)
	defaultClient := resty.New()
	d1,_ := defaultClient.R().Get("http://ww.google.com")

	// Custom request (Secondary Conection: eth1: red:170.27.10)
	customClient := resty.NewByIpNetwork("170.27.10")
	d1,_ := customClient.R().Get("http://ww.google.com")
}

```

**Comment by moorereason** [comment]
Start in resty with [`Client.SetTransport`](https://godoc.org/gopkg.in/resty.v1#Client.SetTransport). You have to create a custom transport with a [`net.Dialer`](https://golang.org/pkg/net/#Dialer) containing the `LocalAddr` property set.  [`net.InterfaceAddrs`](https://golang.org/pkg/net/#InterfaceAddrs) will give you a list of interface addresses.

**Comment by AndrusGerman** [comment]
@alexmontecucco  Thanks for your detailed response. Thank you so much. I do not speak English very well, so I would be delighted with a simple example. I will close the issue

**Comment by jeevatkm** [comment]
@moorereason thanks for the answer.

@AndrusGerman I have not tested this code. try it out and let me know.

```go
package main

import (
	"fmt"
	"net"
	"net/http"
	"time"

	"gopkg.in/resty.v1"
)

func main() {
        // put your correct IP address here
	localAddress, _ := net.ResolveTCPAddr("tcp", "127.0.0.1") 

	// From here https://github.com/golang/go/blob/c75ee696c341cef94b00409b3692f3df82af1c71/src/net/http/transport.go#L42-L53
	// And added Local Address line into transport
	transport := &http.Transport{
		DialContext: (&net.Dialer{
			Timeout:   30 * time.Second,
			KeepAlive: 30 * time.Second,
			LocalAddr: localAddress,   // local address goes here
			DualStack: true,
		}).DialContext,
		MaxIdleConns:          100,
		IdleConnTimeout:       90 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
	}

	client := resty.New()
	client.SetTransport(transport)

	resp, err := client.R().Get("https://www.google.com")
	fmt.Println(err, resp)
}
```

**Comment by AndrusGerman** [comment]
It worked perfectly, With different connections.. Thanks @jeevatkm

**Comment by jeevatkm** [comment]
@AndrusGerman Good to hear. I have created an issue for this feature #226 will be coming in Resty v2.
