### ISSUE TITLE
Cannot use PathParams in Client

### ISSUE THREAD

**Issue by skunert** [go-resty/resty#227]
Hi,
I am trying to prepare a client that is used for subsequent requests.

```go
client := resty.New().SetHostURL("http://myhost:{port}").SetPathParams(map[string]string{
		"port": "123456",
	})

_, e = client.R().SetResult(&myType).Get("/test")
```

In my understanding, the request should work and request the url `http://myhost:123456/test`.
However, I get the following error:

`parse http://myhost:{port}/test: invalid character "{" in host name`

**Comment by moorereason** [comment]
The method naming may be a little confusing, but the URL Host and URL Path are two separate items that will be joined to form the eventual request.  `SetHostURL` is only `scheme://[userinfo@]host`, and no parameter replacement functionality is exposed for the URL Host.  Parameter replacement only occurs for the URL Path.
