### ISSUE TITLE
SetQueryParams supports map[string]interface{} maybe?

### ISSUE THREAD

**Issue by zh-lab** [go-resty/resty#23]
Something like this...
```
resty.R().
	SetQueryParams(map[string]interface{}{
		"name": "xxx",
		"age": 10,
	})
```
also
`SetQueryParam(param string, value interface{})`

**Comment by jeevatkm** [comment]
@zh-lab Actually URL query params are string always. That's why `interface{}` is not supported in those methods.

Do you have something else in your mind?

**Comment by zh-lab** [comment]
```
func (c *Client) SetQueryParams(params map[string]interface{}) *Client {
	for p, v := range params {
		c.QueryParam.Add(p, fmt.Sprint(v))
	}

	return c
}
```

```
func (c *Client) SetQueryParam(param string, value interface{}) *Client {
	c.QueryParam.Add(param, fmt.Sprint(value))
	return c
}
```
Then we could use int params without atoi?
Just my thoughts.

**Comment by jeevatkm** [comment]
Implementing this way is okay, however changing existing method signature might break user code. I will get back to you about method signature or if you have suggestion please let me know.

**Comment by zh-lab** [comment]
I see, thx!:smiley:

**Comment by jeevatkm** [comment]
Currently I'm thinking about unique method signature. If you have any name suggestion let me know. I will bring this `interface{}` support.

**Comment by voronovmaksim** [comment]
6 years have passed, but the api is not implemented(
