### ISSUE TITLE
parsing go.mod: unexpected module path "gopkg.in/resty.v1"

### ISSUE THREAD

**Issue by kourtni** [go-resty/resty#230]
Hi,

I'm trying to generate a go.mod file for a project I'm working on. However it is failing with:
```
go: github.com/go-resty/resty@v1.11.0: parsing go.mod: unexpected module path "gopkg.in/resty.v1"
go: error loading module requirements
```

We don't directly depend on resty, so not certain how I can get beyond this issue.

**Comment by jeevatkm** [comment]
@kourtni It seems, one of your project dependencies use incorrect resty import path for `go mod` [refer here](https://github.com/go-resty/resty#installation). 

Could you try the following, add this into `go.mod` after the `require` block? 

```
replace github.com/go-resty/resty => gopkg.in/resty.v1 v1.11.0
```

**Comment by kourtni** [comment]
That worked. Thanks!

**Comment by kotyara85** [comment]
Having the same issue,
My go.mod is :
gopkg.in/resty.v2 v2.0.0

$ GO111MODULE=on go mod vendor
go: gopkg.in/resty.v2@v2.0.0: go.mod has non-....v2 module path "github.com/go-resty/resty/v2" at revision v2.0.0

**Comment by jeevatkm** [comment]
@kourtni For `v2` usage please refer to readme at https://github.com/go-resty/resty#installation and usage.  

There are breaking changes in `v2` release, please refer to release notes https://github.com/go-resty/resty/releases/tag/v2.0.0 at `Breaking Changes - Migrating v1.x to v2`
