### ISSUE TITLE
SSE

### ISSUE THREAD

**Issue by damianoneill** [go-resty/resty#231]
Is there a way to do the client side of Server Side Events with go-resty?

**Comment by jeevatkm** [comment]
@damianoneill Currently no, maybe in an upcoming `v2`.

**Comment by damianoneill** [comment]
Thanks @jeevatkm, appreciate the quick reply.  Would be fantastic if you would consider this requirement.  Thanks for Resty, its a great library.

**Comment by jeevatkm** [comment]
@damianoneill Thanks for your appreciation. Once I wrap up currently planned items for `v2` then I will take up this one.

**Comment by jeremy-chua** [comment]
Just wondering if this feature is in the rodmap?
