### ISSUE TITLE
PATCH multipart/form-data

### ISSUE THREAD

**Issue by runeimp** [go-resty/resty#239]
Thank you for Resty! It's great but I'm currently being blocked on one of my projects as it only allows POST and PUT when sending multipart data per https://github.com/go-resty/resty/blob/master/request.go#L474 . The service I'm sending to uses PATCH to attach files to other data in their system and expect it using `Content-Type: multipart/form-data`. And while I think they should probably be using POST for this they require PATCH. And this functionality is supported in other tools. But I'm trying to avoid tricking applications or command line tools to process over 3,000 PATCH requests. My code is all done, if Resty will allow multipart PATCH.  👼

**Comment by jeevatkm** [comment]
@runeimp I understand your requirement. Could you submit a PR for v1 as well as for v2?

**Comment by runeimp** [comment]
Didn't have time to work on your code before delivery. I may work on it in the near future though. Just depends on the needs and workload. Thanks again for the tool. As is it is still awesome!  😃

**Comment by jeevatkm** [comment]
@runeimp I have added `PATCH` into the multipart in v1.x, this update would carry forward to v2 as well.

I'm closing this one 😄

**Comment by runeimp** [comment]
@jeevatkm thanks for the patch! 🙂

**Comment by jeevatkm** [comment]
You're welcome, I'm planning to move this change in v2 release. Since I'm very close in finishing docs.
