### ISSUE TITLE
Always try to parse response if SetResult has been called

### ISSUE THREAD

**Issue by pborzenkov** [go-resty/resty#240]
It's possible to get a 200 OK response with HTML contents from a JSON endpoint due to faulty backend configuration (e.g. a problem in API gateway, etc.).
Since resty only parses response if content type is JSON or XML the call won't return an error. Such errors could be hard to debug.

I suggest to fix the default behaviour and always parse response if SetResult has been called.

**Comment by jeevatkm** [comment]
@pborzenkov Thank you for reporting an issue. I will have a look and get back to you.

**Comment by jeevatkm** [comment]
@pborzenkov This I will take it up for `v2`.

**Comment by jeevatkm** [comment]
@pborzenkov I have written a small test case for the scenario you have described. I didn't see any errors (This is the upcoming v2 branch, notably this particular part should be same as v1).

Could you please have a look this https://github.com/go-resty/resty/commit/01e423c55b6f5cb2c8068be61f779b0c89593e26?

Let me know what you're trying to explain. If possible provide an example or test case to demonstrate.

**Comment by pborzenkov** [comment]
@jeevatkm 

> Let me know what you're trying to explain. If possible provide an example or test case to demonstrate.

That's exactly what I was talking about. I'd have expected the `err` to be non-nil, since the response doesn't have the expected structure (`AuthSuccess`). But since Content-Type isn't a JSON, resty doesn't even try to parse it. That's why I proposed to always try and parse the response if `SetResult` has been called, even if the response doesn't have proper Content-Type.

**Comment by jeevatkm** [comment]
@pborzenkov Currently resty have [ExpectContentType](https://pkg.go.dev/github.com/go-resty/resty/v2?tab=doc#Request.ExpectContentType) and I have added new method `ForceContentType` for #276 in the branch [result-parsing-enhancement](https://github.com/go-resty/resty/tree/result-parsing-enhancement)

Does it satisfy your use case, can you please check, let me know?

**Comment by pborzenkov** [comment]
@jeevatkm Yes, it does satisfy the describe use case. Thanks!

**Comment by jeevatkm** [comment]
@pborzenkov wow, quick response, appreciated. Sorry for the delay!
