### ISSUE TITLE
Allow Content-Length to be set for streams w/o buffering

### ISSUE THREAD

**Issue by jboelter** [go-resty/resty#241]
Recommend considering this for v2

The current library works, but buffers the entire stream into memory to set the content-length when requested. This allows the caller to specify the content-length. Caveat -- the solution below isn't sufficiently generic. A more complete solution might consider an io.Seeker ([caveat](https://github.com/golang/go/blob/46076c37578fba9b49059584ef896099c9240fb2/src/archive/tar/reader.go#L832-L851)) and skip the buffer read if an explicit content length was already set when considering the [this](https://github.com/go-resty/resty/blob/master/middleware.go#L401-L408) flow when client.SetContentLength() is set.

This allowed me to workaround an issue where I needed to set the required Content-Length for a PUT upload to a pre-signed AWS S3 URL for large files. [S3 PUT](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html). 

[https://github.com/go-resty/resty/compare/master...jboelter:master](https://github.com/go-resty/resty/compare/master...jboelter:master)

```` golang
// SetContentLengthValue method sets RawRequest ContentLength value for the current request.
// This is useful when you know the size of bytes a io.Reader will return, but don't have a
// io.Seeker and you don't want to buffer the stream to get the length before sending the
// request.
//
func (r *Request) SetContentLengthValue(l int64) *Request {
	r.contentLength = l

	return r
}
````

**Comment by jeevatkm** [comment]
@jboelter @pborzenkov Thank you for your inputs. It seems you have already read the code base and know the bufferless processing for `io.Reader`.  I think you could set header `Content-Length` using method `SetHeader`. Did you get a chance to try it out?

**Comment by jeevatkm** [comment]
@jboelter Kindly give it try on above suggestion and please let me know.

I'm closing this one.
