### ISSUE TITLE
Add  Content-MD5 entity-header field support?

### ISSUE THREAD

**Issue by lrita** [go-resty/resty#242]
The `Content-MD5` entity-header field, as defined in RFC 1864, is an MD5 digest of the entity-body for the purpose of providing an end-to-end message integrity check (MIC) of the entity-body. (Note: a MIC is good for detecting accidental modification of the entity-body in transit, but is not proof against malicious attacks.). eg.[aws-sdk-go](https://github.com/aws/aws-sdk-go/blob/f26268b77ea9619d95b1d04b6f3e3c5a03b61110/service/s3/body_hash.go#L30-L50) using it.

If we want support there entity-header field, we need add a new request middlewares after `parseRequestBody`. And there is an problem, how can we get a body snapshot when it is not an instance of `strings.Reader`/`bytes.Reader`/`buffer.Reader`/`io.Seeker`?

**Comment by jeevatkm** [comment]
@lrita I will look into it and get back to you.

**Comment by jeevatkm** [comment]
@lrita I think it's good to add hook/middleware after `parseRequestBody` so that resty users could to more than one operation of thier choices.

I'm moving this item to v2 series.

**Comment by jeevatkm** [comment]
@Irita Just wondering, `SetPreRequestHook` isn't helpful for this use case? Could you check and confirm?

**Comment by lrita** [comment]
I think `SetPreRequestHook` given user a good chance to do this. And it must provide a method like `http.Request.GetBody func() (io.ReadCloser, error)` which return a new copy of payload. Because the payload of given request maybe in `Request.bodyBuf` or `Request.Body` that make users to get payload easily even if they does not well known the internal of go-resty/resty.

**Comment by jeevatkm** [comment]
@lrita I have added `GetBody` method support in the branch `expose-request-body-copy`.  It is available for you to use in `PreRequestHook`. Please give it try and let me know.

**Comment by lrita** [comment]
Hi @jeevatkm, I have checkouted and tested the branch, it looks gooood.

**Comment by jeevatkm** [comment]
@lrita Thank you for your testing and confirmation 😄
