### ISSUE TITLE
Trying to import resty into a go module fails and refuses to build.

### ISSUE THREAD

**Issue by Galadros** [go-resty/resty#243]
I have a program that includes resty.  I'm trying to add gomodule support to it, but running into issues with importing `resty`.  The error message is:
```
go: github.com/go-resty/resty@v1.12.0: parsing go.mod: unexpected module path "gopkg.in/resty.v1"
go: error loading module requirements
```
I think I see that v2 will fix this error- but do you have any idea when v2 might be coming, or any suggestions I can use for a workaround to still let me use go modules?  I've been working at this for quite a while and can't easily find a solution- I can't actually figure out how to stop it trying to import `github.com/go-resty-resty` honestly.

**Comment by jeevatkm** [comment]
@Galadros Please try this solution https://github.com/go-resty/resty/issues/230#issuecomment-467911306 with your version number. 

I have to prepared v1 to v2 migration docs, once done I will make a release of v2.

**Comment by jeevatkm** [comment]
@Galadros Any updates?

**Comment by Galadros** [comment]
I managed to get this playing nicely after a while, which is good!  There are some other oddities about how our deployment/compile process works that proved to be problematic, but eventually I did get it working.  I still do appreciate your quick response!

Patrick

**Comment by jeevatkm** [comment]
@Galadros  Thank you for the updates.
