### ISSUE TITLE
Resty retries when deserialization fails

### ISSUE THREAD

**Issue by georgewilk01** [go-resty/resty#244]
When the GET call fails deserialization resty retries the request spontaneously w/o being asked.
Example:

resp, err := resty.New().
		SetTimeout(250 * time.Millisecond).
		SetRetryCount(4).   // RetryCount includes the original request, so 1 + 3
		SetRetryWaitTime(50 * time.Millisecond).R().
		SetResult(&Member{}).
		Get("http://localhost:8080/member/123")

When the response body deserialization fails resty retries the request.  How can I prevent this from happening?  My actual working production version explicitly sets retry conditions when client is initialized via AddRetryCondition and specifically limits list of retry-able status codes to 502, 503 and 504.  It was my understanding that setting retry conditions should provide an exclusive
 list of retry conditions.  Am I missing something here?

**Comment by jeevatkm** [comment]
@georgewilk01 Thanks for sharing your findings. I will verify at my end and get back to you.

**Comment by georgewilk01** [comment]
Any luck with recreating this condition?

**Comment by jeevatkm** [comment]
@georgewilk01 I'm sorry. Past of couple weeks I'm stuck with day work urgent deliverables. Maximum I will have a look and get back to you by this weekend.

**Comment by jeevatkm** [comment]
@georgewilk01 I have verified and also remembered this issue. It is related with retry condition design issue. It cannot be fixed without breaking changes.

So I have addressed retry condition issue in upcoming Resty v2. Once v2 migration docs is ready I will ping you.

**Comment by georgewilk01** [comment]
Great!  Thanks for the follow-up.  I look forward to trying Resty v2

**Comment by jeevatkm** [comment]
@georgewilk01 In the meantime, you could try out v2.0.0-rc2, please share the feedback. please refer to #235

**Comment by jeevatkm** [comment]
I'm closing this one, in favor of upcoming v2 release.
