### ISSUE TITLE
How to mock Response without executing a request?

### ISSUE THREAD

**Issue by smiklosovic** [go-resty/resty#245]
Hey,

I want to test my unmarshalling logic and I do not want to make a call to server, I just want to pretend I already got some response. `body` is package private in Response so how should I set that one?

**Comment by jeevatkm** [comment]
@smiklosovic you could use any http mocking library with Resty to mock request. for e.g. [readme reference](https://github.com/go-resty/resty#mocking-http-requests-using-httpmock-library)

**Comment by jeevatkm** [comment]
I'm closing this one.

**Comment by smiklosovic** [comment]
@jeevatkm no worries, I did this for reference

`	client.testResponse = &resty.Response{
		RawResponse: &http.Response{
			Body:       ioutil.NopCloser(bytes.NewReader([]byte(`{ "my": "json"}`))),
			Status:     "200 OK",
			StatusCode: 200,
		},
	}
`

Then I have some logic around that in my client ..

**Comment by Kolyunya** [comment]
@smiklosovic when you set a `http.Response` as a `RawResponse`, it wouldn't be used by e.g. `resty.Response.String()` which we use in production code.

This quirk makes `resty.Response` untestable... Illustration:
https://replit.com/@kolyunya/resty-response-mock#main.go

Have you managed to work around this somehow?

**Comment by jeevatkm** [comment]
@Kolyunya @smiklosovic I have added `Response.SetBody(b []byte)` will be released in `v2.10.0`. I should have done it earlier.
Currently, it's available in `v2.10.0-rc.2`.

**Comment by Kolyunya** [comment]
@jeevatkm thanks for a quick fix!
