### ISSUE TITLE
OnBeforeRequest and SetQueryParams/SetPathParams

### ISSUE THREAD

**Issue by RafPe** [go-resty/resty#248]
Hi, 

I'm trying to use resty client against one of our vendor APIs. In my case scenario I need to sign every request being sent. Therefore my idea was to use `OnBeforeRequest` to get the full URL exactly as it at the end is called and use it to create and add signature. 

However within `OnBeforeRequest` the path is not substituted when using SetPathParams ( would need to do it on my own ? ) nor the query params are in the URL as well ( when using SetPathParams ) . 

Is there an easy way to achieve this ?

**Comment by jeevatkm** [comment]
@RafPe for your use case I think [SetPreRequestHook](https://godoc.org/gopkg.in/resty.v1#Client.SetPreRequestHook) could be the one.

**Comment by RafPe** [comment]
@jeevatkm it exactly does - thanks
