### ISSUE TITLE
Disable warnings possible?

### ISSUE THREAD

**Issue by dahankzter** [go-resty/resty#25]
I get this continously:

RESTY 2016/04/13 16:28:18 WARNING - Using Basic Auth in HTTP mode is not secure.

It would be nice if it was (perhaps it already is!) possible to disable warnings.

**Comment by dahankzter** [comment]
Thanks for a nice package by the way! ;)

**Comment by jeevatkm** [comment]
Thanks @dahankzter 

This warning was added to recommend best practice. You know it already; exchange credentials in plain text exposes request to vulnerability.

Will provide option disable these warnings, however `resty` will log warning once. Sounds good?

**Comment by dahankzter** [comment]
Sounds perfect, thank you!

**Comment by jeevatkm** [comment]
Added method `SetDisableWarn` at client level, please try it out and let me know.

**Comment by dahankzter** [comment]
I will try it as soon as possible, thank you!

**Comment by dahankzter** [comment]
Seems to work just fine on a cursory test thank!

**Comment by jeevatkm** [comment]
Thanks for your feedback.
