### ISSUE TITLE
v2 Release error with go mod

### ISSUE THREAD

**Issue by jeevatkm** [go-resty/resty#251]
I have tried to make a release v2 with the following approach 
* Merging into master
* Having v2 branch

Not sure, what is missing? ran into an error. So reverted the master back to the previous state.

May be go mod vs `github.com/go-resty/resty` vs `gopkg.in/resty.v1` - Need an investigation!!

```
go: finding github.com/go-resty/resty/v2 v2.0.0
go: finding golang.org/x/net v0.0.0-20190619014844-b5b0513f8c1b
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding github.com/go-resty/resty v1.12.0
go: downloading github.com/go-resty/resty v1.12.0
go: extracting github.com/go-resty/resty v1.12.0
go: github.com/go-resty/resty@v1.12.0: parsing go.mod: unexpected module path "gopkg.in/resty.v1"
go: error loading module requirements
```

**Comment by jeevatkm** [comment]
Hello Resty users, if anyone has insights about an error and possible solution, please post your inputs here.

**Comment by 1995parham** [comment]
Hi, I have tried to do this in a forked repository [here](https://github.com/1995parham/resty) and test it with one of my project [here](https://github.com/I1820/tm/tree/master/client). I think this is working.

**Comment by jeevatkm** [comment]
@1995parham Thank you for your inputs, I will have a look at your reference and try it out.

**Comment by 1995parham** [comment]
@jeevatkm I am available if there is anything that I can do.

**Comment by jeevatkm** [comment]
@1995parham I have looked at your changes. I understand go mod expects the `/v2` suffixes across  on library/package side. 

However why it is needed on consumer side go mod definition with `/v2`-

https://github.com/I1820/tm/blob/b5f5457edb4da120c8899a26f54d4d3d8d0f0076/client/go.mod#L7

My understanding on consumer go mod is -

```
github.com/go-resty/resty v2.0.0
```

Am I missing something?

**Comment by 1995parham** [comment]
As you can find it [here](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher) major branches need a specific version on their module name. It protects the consumer from major upgrades that break compatibility.

**Comment by jeevatkm** [comment]
@1995parham Yes, you're correct on resty library side changes. I was checking with you about the resty users go mod file definition. I believe on resty user side only `github.com/go-resty/resty v2.0.0` needed without `/v2` suffix.

I need to verify my understanding and also thought to check with you.

**Comment by 1995parham** [comment]
I think you can do it without adding `/v2` on the user side but some libraries like [echo](https://github.com/labstack/echo) have done that.

**Comment by jeevatkm** [comment]
@1995parham okay, basically its a user choice 😄 to change their import path or not. Thanks.

I will get this mod part working for Resty.

**Comment by 1995parham** [comment]
@jeevatkm I want to thank you again for this awesome package 🙌

**Comment by 1995parham** [comment]
@jeevatkm Is there anything that I can help with to release the v2?

**Comment by jeevatkm** [comment]
@1995parham Nice timing, I just made v2.0.0 test tag. Can you please test it and ping me?

In the mean-time I will wrap up the release notes.

**Comment by 1995parham** [comment]
@jeevatkm Awesome 👍 I will test it and let you know

**Comment by 1995parham** [comment]
@jeevatkm I have tested the new version and I think its working 💪

**Comment by jeevatkm** [comment]
@1995parham Thanks for your testing and validation.
