### ISSUE TITLE
RESTY request is being called twice when the request handler at the API endpoint is taking a long to time to process

### ISSUE THREAD

**Issue by viseth** [go-resty/resty#255]
Hi

I've been using RESTY for 2 project and it'an amazing work.
I've come across the following issue after upgrading to RESTY v2.

It looks like the RESTY request is being called twice when the request handler at the API endpoint is taking a long to time to process and give an answer back. The final answer I got from the RESTY request is net::ERR_EMPTY_RESPONSE. 
I haven't noticed such behaviour in the previous release v1.

At the client side, the ajax is indeed being called only once but the client RESTY depending on the time the endpoint is taking to process the request.

browser -> ajax POST -> server API handler1 (RESTY) -> dataprocessing server (processing time can be high more than 1 minute) 

The final response on the browser side is net::ERR_EMPTY_RESPONSE. 

Test case with a "time.Sleep(20 * time.Second)" (for a processing time of 20 sec at the dataprocessing server side).

If I set a "time.Sleep(5 * time.Second)", the RESTY only execute the request once and the browser client does get the correct JSON answer.

Any idea ?

Thanks,

Regards,

Viseth

**Comment by jeevatkm** [comment]
@viseth Thank you for reporting an issue. Could please you help me with some test case? I will also look at my end.

**Comment by viseth** [comment]
@jeevatkm 

Please, here's a small test case. Hope this help.
https://github.com/viseth/TestCaseRESTY

Thanks,

**Comment by jeevatkm** [comment]
@viseth Thank you for the test case and detailed description, I appreciate it. I will look into to it.

**Comment by viseth** [comment]
@jeevatkm did you manage to reproduce the issue by any chance ?
Thanks,

**Comment by jeevatkm** [comment]
@viseth I did not verified yet, sorry for the delay. Once I finish my analysis I will get back to you.

Also one thing I noticed while going through your project. You're currently using `v1`; could you please try `v2` and let me know? There are fixes and improvements happened in retry logic and around it. Thanks!

**Comment by viseth** [comment]
@jeevatkm actually I'm using v2 (go-resty/2.0.0) ?
in the test case :
import (
	"fmt"
	"time"
	"github.com/gin-gonic/gin"
	// resty.v1
	//"gopkg.in/resty.v1"
	"github.com/go-resty/resty"
)
Thanks,

**Comment by viseth** [comment]
@jeevatkm any progress on this issue. Otherwise I will need to rework the ajax call with callback.
Thanks,

**Comment by jeevatkm** [comment]
@viseth I'm really sorry I couldn't get a chance to test and investigate it. 

Just for my understanding, are you able to use `v2` without using import of `github.com/go-resty/resty/v2`?

**Comment by viseth** [comment]
@jeevatkm actually I am using v2 with the following import: "github.com/go-resty/resty"

**Comment by viseth** [comment]
@jeevatkm any progress?

**Comment by jeevatkm** [comment]
@viseth I'm sorry for the delay. I have tested with your test case program from https://github.com/viseth/TestCaseRESTY

**Test result:** Issue is with your web application AJAX request is timing out. Both of your GoLang program of monitor and web server requests are working fine using Resty.

----
What did I do to test your use case?
* I took your test case code base
* Add go.mod file into both the program
* Updated the wait time from `60 sec` to `90 sec`
* build and run the both program 
* Go to URL http://localhost:9090/web/html/layout.html#
* Clicked the `Click` link and observed the program behavior

So outcome -
- HTML page sends AJAX request to "http://localhost:9090/runMonitor"
- Then WebServer makes the call to URL "http://localhost:8050/v2/myKey" using the Resty library
- Waiting for response ...
- Got the response from "monitor" program after 90 sec successfully
- So **request between two GoLang programs is successful via Resty**

But 
- WebServer sends the response back to AJAX request **HOWEVER** It seems AJAX request flow is already timeout.

Also submitted the PR to your test case repo https://github.com/viseth/TestCaseRESTY/pull/1

----
**Screenshot of Request and Response using Resty is successful**

<img width="775" alt="Screen Shot 2019-09-07 at 8 28 21 PM" src="https://user-images.githubusercontent.com/1175977/64483047-1304a980-d1b1-11e9-96eb-17480803a6d9.png">

**Screenshot of request and response of Monitor program**

<img width="767" alt="Screen Shot 2019-09-07 at 8 29 43 PM" src="https://user-images.githubusercontent.com/1175977/64483051-40e9ee00-d1b1-11e9-9ce4-69cebf1641c2.png">
