### ISSUE TITLE
http or https return stream, How to handle

### ISSUE THREAD

**Issue by zsspj12** [go-resty/resty#262]
Hi!
 As title, In your project, I don't find function to handle http or https request response stream(the request still run)。Can you help me? @jeevatkm

**Comment by jeevatkm** [comment]
@zsspj12 For stream scenario, Resty users have to handle it explicitly. 

* Use https://godoc.org/github.com/go-resty/resty#Request.SetDoNotParseResponse option 
* Read your stream response based on your use case using https://godoc.org/github.com/go-resty/resty#Response.RawBody

**Comment by jeevatkm** [comment]
I'm closing this issue.
