### ISSUE TITLE
How to use resty with github.com/golang/dep/?

### ISSUE THREAD

**Issue by sunsingerus** [go-resty/resty#264]
Tried to use *resty* with `dep`-enabled project and have the following issue.
Start point:
`Gopkg.toml` code:
```yaml
[[constraint]]
  name = "github.com/go-resty/resty"
  version = "v2.0.0"
```
Run `dep ensure` and got:
```text
Solving failure: No versions of github.com/go-resty/resty met constraints:
	v2.0.0: Could not introduce github.com/go-resty/resty@v2.0.0, as its subpackage github.com/go-resty/resty/v2 is missing. (Package is required by (root).)
```
Probably related to [this issue](https://github.com/golang/dep/issues/899)

Can you, please, give an advice?

**Comment by jeevatkm** [comment]
@sunsingerus I have only tested with `go mod` not `dep` I might have to try it out.  I'm sorry I don't have a suggestion or recommendation right now.

**Comment by avorima** [comment]
I would suggest moving everything in the master into a v2 subdirectory.

**Comment by jeevatkm** [comment]
@avorima Thank you for the updates. 

@sunsingerus Any updates?

**Comment by huzairuje** [comment]
@jeevatkm i am using v2.1.0 and add to Gokpg.toml like this 
`[[constraint]]
  name = "github.com/go-resty/resty"
  version = "v2.1.0"`
not having problem. with dep ensure
and i think this issue with version v2.1.0 is solved

**Comment by jeevatkm** [comment]
Thank you @huzairuje for verifying and confirmation for `v2.1.0`.

**Comment by sherodewo** [comment]
> @jeevatkm i am using v2.1.0 and add to Gokpg.toml like this
> `[[constraint]] name = "github.com/go-resty/resty" version = "v2.1.0"`
> not having problem. with dep ensure
> and i think this issue with version v2.1.0 is solved

thankyou mang ujeee wkkw
