### ISSUE TITLE
How to get content length without downloading the file

### ISSUE THREAD

**Issue by iveeshal** [go-resty/resty#272]
I want to show a progress bar in my console while downloading the file.. How can get size of file even without downloading the file. How to support such usecase?

**Comment by zhenzou** [comment]
You can try a HEAD request and get the Content-Length header field.

**Comment by jeevatkm** [comment]
@iveeshal As @zhenzou described, you will have to try that. If the server supports the `HEAD` request, you will be able to get the value. Also, this use case is not related to any HTTP client or Resty capabilities.
