### ISSUE TITLE
Support for multiple host urls

### ISSUE THREAD

**Issue by janekolszak** [go-resty/resty#274]
Hi!
It would be really, really practical if there was SetHostURLs() that accepts multiple addresses.  Resty would choose one of them upon each request. This could be configurable as well, but a random choice at first could suffice.

Cheers!

**Comment by jeevatkm** [comment]
@janekolszak Thanks for bringing up your thoughts.  I'm not sure how it will benefit to Resty users in a practical use case. Are you trying to say client-side load balancing?

**Comment by janekolszak** [comment]
Yeap - simple client side load balancing

**Comment by jeevatkm** [comment]
@janekolszak Thanks, I see a use case. However, I'm not sure about how much this feature going to helpful to the broader audience.

I will keep this open, will implement it later when I get a chance.
