### ISSUE TITLE
why doesn't SetResult work?

### ISSUE THREAD

**Issue by sgon00** [go-resty/resty#275]
My Code:

```go
package main

import (
	"fmt"
	"github.com/go-resty/resty/v2"
)

var client *resty.Client

type JSONModel struct {
	Errcode *int    `json:"errcode"`
	Errmsg  *string `json:"errmsg"`
}

func init() {
	client = resty.New()
}

func main() {
        url := "....."
	var obj JSONModel
	resp, _ := client.R().SetResult(&obj).Get(url)

	fmt.Printf("obj is: %v\n", obj)
	fmt.Printf("response is: %v\n", resp)
}
```

Output:

```
obj is: {<nil> <nil>}
response is: {"errcode":10029,"errmsg":"invalid code, hints: [ ... ]"}
```

I really can't figure out what's wrong with the code for a long time.

**Comment by sgon00** [comment]
I figured out why. The server returns content-type text/plain instead of json...

**Comment by clip-rain** [comment]
how to force resty use json to unmarshal reponse?

**Comment by moorereason** [comment]
@clip-rain, this issue has been closed for a long time.  Please open a new issue or discussion thread.

**Comment by mushroomlb** [comment]
只有首字母是大写的成员才可以序列化为JSON
只有可导出成员（变量首字母大写）才可以序列化为json。因成员变量note是不可导出的，故无法转成json。

可以在变量打上json标签，如Name旁边的json:"name"，那么转化成的json key就用该标签name而不是Name。
否则取变量名作为key，如ID，Colors。

**Comment by scrynaxx** [comment]
> how to force resty use json to unmarshal reponse?

```
res, err := restyClient.R().
    ForceContentType("application/json")
...
```
