### ISSUE TITLE
Is that possible to force response content-type when it's wrong? 

### ISSUE THREAD

**Issue by sgon00** [go-resty/resty#276]
I find out there is an option to provide fallback content-type when it's not available in response. But what if the response has a wrong content-type? Can I force a correct content-type? For example with the following code, I expect to see a application/json content-type:

```go
resp, _ := client.R().SetResult(&obj).Get(url)
```

But  the server incorrectly replies a json plain text with content-type text/plain. It's a json format in a plain text type. How can I handle this? 

Thanks a lot.

**Comment by jeevatkm** [comment]
@sgon00 Thank you for reporting your experience. 

Currently, you can provide fallback but you cannot force response content type. However, I see a similar nature of requirement in #240 

I will think about it and get back to you.

**Comment by jeevatkm** [comment]
@sgon00 I have added a new method `ForceContentType` method on the `Request` object that complements the [ExpectContentType](https://pkg.go.dev/github.com/go-resty/resty/v2?tab=doc#Request.ExpectContentType). It's available in the branch [result-parsing-enhancement](https://github.com/go-resty/resty/tree/result-parsing-enhancement)

Can you please try and let me know?
