### ISSUE TITLE
retry condition can't throw error

### ISSUE THREAD

**Issue by coolyrat** [go-resty/resty#278]
Thank you for creating such a useful library!

I check the response body in the RetryConditionFunc. And If the response body is invalid, I will return true to retry. But after maxRetry, it will still output the response. What I want is to return an error, so after maxRetry, it will return the error instead of the invalid response.

**Comment by jeevatkm** [comment]
@coolyrat Sorry for the delayed response. Can you please provide some unit tests to describe the problem?  So that I can understand better and think of what needs to be done.

**Comment by jeevatkm** [comment]
@coolyrat can you share some unit test case to describe the issue?

**Comment by jeevatkm** [comment]
@coolyrat I have analyzed it. In the resty v2 retry condition func only allows the decision of retry or not. 

I would like to know your suggestion or proposal to solve or workaround.

**Comment by jeevatkm** [comment]
@coolyrat I'm closing it with the above response.
