### ISSUE TITLE
Disable automatic content-type setting

### ISSUE THREAD

**Issue by smaheshs** [go-resty/resty#279]
Hi,

As per the documentation, for a request if we do not set the content-type, resty automatically detects the content and sets the header if the 'Content-Type' is not set by the client code.

Is there some way to disable this automatic content type detection and setting at a per request level?

Thanks.

**Comment by jeevatkm** [comment]
@smaheshs  Resty does not allow you to disable. It's either you can set or it's set it.

Typically HTTP request needs a `Content-Type` at least `application/octet-stream`. May I know your use case to better understand? That way we can think about it.

**Comment by smaheshs** [comment]
Hi,

Have received documentation for few REST endpoints to be integrated as per which there is no Content-Type mentioned for any of the requests.

Do not have access to these APIs yet, so not able to tell for sure if Resty's auto content-type setting causes problem, but raised issue preemtively to avoid delays later in case it causes issue.

Thanks.

**Comment by jeevatkm** [comment]
@smaheshs Okay, let me know after you get access to your APIs docs. For now, closing this one.
