### ISSUE TITLE
SetQueryParams does not support "Multi" inputs

### ISSUE THREAD

**Issue by guohuang** [go-resty/resty#28]
Does Resty support Multiple params? I am passing any array of statuses for query param, i am expecting the querystring is 
`?status=pending&status=approved`, but what i got from the debugger is only appending the first value,(status=pending)
here is my code 
```
	var status = []string {"pending","approved"}
	for _, value := range status {
		resty.R().SetQueryParam("status",value)
	}
```
fyi, i also tried SetQueryParams, but since it is a dictionary, you can't have multiple values, so it won't work either. I know the work around is converting status array to a comma separated strings, but I prefer to set multiple parameters.

are you going to add this feature in the near future?

cc @wing328

**Comment by jeevatkm** [comment]
Just had a look. It seem these two lines [L50](https://github.com/go-resty/resty/blob/master/middleware.go#L50) and [L53](https://github.com/go-resty/resty/blob/master/middleware.go#L53) requires change from method `Set` to method `Add`.

Would like to you send PR or I can do it over weekend?

**Comment by guohuang** [comment]
I tried it, it didn't work, i looked further in net/url package, it is also a dictionary, so either way it will not work.

```

// Set sets the key to value. It replaces any existing
// values.
func (v Values) Set(key, value string) {
	v[key] = []string{value}
}

// Add adds the value to key. It appends to any existing
// values associated with key.
func (v Values) Add(key, value string) {
	v[key] = append(v[key], value)
}

```

**Comment by guohuang** [comment]
see this, https://golang.org/pkg/net/url/

func (Values) Add

func (v Values) Add(key, value string)
Add adds the value to key. It appends to any existing values associated with key.

**Comment by jeevatkm** [comment]
You're correct. Yes query param name is unique in the URI, as per URI RFC.

So as per RFC, you can get multi-value after changing those two lines I mentioned above. 
```
for e.g.: ?status=pending,approved
```

**Comment by jeevatkm** [comment]
@guohuang I have updated the comment.

**Comment by guohuang** [comment]
yes, we can always use ` ?status=pending,approved` as work around, but we want ` ?status=pending&status=approved`, looking at https://github.com/go-resty/resty/blob/master/request.go#L91, your proposed solution doesn't work, as QueryParam is a dictionary.

**Comment by jeevatkm** [comment]
I will add this support, also I have updated the previous comment. Once done I will update this issue.

**Comment by jeevatkm** [comment]
I have added the support. It's available on master. Give it a try and let me know.

**Comment by guohuang** [comment]
yup, it works! thanks for the quick fix!

**Comment by jeevatkm** [comment]
Nice. I'm closing this one.

**Comment by jeevatkm** [comment]
BTW, I have added this new method [SetMultiValueQueryParams](https://godoc.org/github.com/go-resty/resty#Request.SetMultiValueQueryParams).

**Comment by guohuang** [comment]
Nice! you are really quick and professional!

**Comment by jvitoroc** [comment]
Has the function name changed overtime? It seems it is "SetQueryParamsFromValues" now.
