### ISSUE TITLE
Should not print body content under body for boundary

### ISSUE THREAD

**Issue by zhangguanzhang** [go-resty/resty#281]

**Comment by jeevatkm** [comment]
@zhangguanzhang Can you please describe the issue in detail with example?

**Comment by zhangguanzhang** [comment]
If I post a binary file, the file stream will be printed out by debug.

**Comment by zhangguanzhang** [comment]
or post a pic

**Comment by viennadd** [comment]
I got a similar requirement here, 
the `debugBodySizeLimit` of resty client works only on response logger, 
but not on request logger, resty will log the whole file content in strings when i try to post a file to some API 

i think we should apply debugBodySizeLimit on request logger as well
@jeevatkm

**Comment by jeevatkm** [comment]
@zhangguanzhang @viennadd Sure, I understand. We can apply it to request logger too.

If you're interested you can submit PR otherwise I will take it up later on 😄

**Comment by viennadd** [comment]
I would like to submit a PR later tomorrow @jeevatkm 😀

**Comment by jeevatkm** [comment]
PR #297 is merged, closing this one. Thanks.
