### ISSUE TITLE
How to disable error log when using SetRetryCount

### ISSUE THREAD

**Issue by j3ssie** [go-resty/resty#282]
Hi, My resty client look like this
```
client := resty.New()
client.SetRetryCount(3)
resp, err := client.R().Get("https://myerror.host")
```
Whenever I send request to error url I get this error.
`2019/11/05 13:40:40.504114 ERROR RESTY Get https://myerror.host: auto redirect is disabled, Attempt 1`

My question is how to disable it? because I need to send request to a list of urls so I might get to some error url like this. It's doesn't show this error if I'm not using `client.SetRetryCount(3)`.

Thanks.

**Comment by jeevatkm** [comment]
@j3ssie You can disable particular error logs. However, you can implement your own logger to control the output. Resty logging is interface -
https://github.com/go-resty/resty/blob/0b8565526124c3958f30ee0fe3d9a37886f73515/util.go#L30-L34

And then set it to the resty client using https://godoc.org/github.com/go-resty/resty#Client.SetLogger

**Comment by j3ssie** [comment]
Hi @jeevatkm,
I saw `SetLogger` function in the docs but still doesn't know how to use it (sorry because I still a beginner in golang) 😂.

Can you provide simple client config to disable it?
Regards,

**Comment by j3ssie** [comment]
I solved the problem by using this code below to disable error log.
```
logger := logrus.New()
logger.Out = ioutil.Discard
client := resty.New().SetLogger(logger)
```
