### ISSUE TITLE
Debug mode not working in 2.1.0

### ISSUE THREAD

**Issue by jose-sanchezm** [go-resty/resty#283]
I'm using resty v2.1.0 with Go version 1.13.4 in Linux and I'm unable to get debug information for resty calls. I've prepared a little test at https://github.com/jose-sanchezm/resty_test with a couple of calls setting setDebug as true and with and without a logger. Then running the test I get the following output:

```
INFO[0000] Initializing                                 
DEBU[0000] Sending request without logrus               
DEBU[0000] Request sent                                 
DEBU[0000] Sending request with logrus                  
DEBU[0000] Request sent
```

And no trace of the request or response sent to the server. Is there anything more that I have to set in order for resty to log requests and responses?

**Comment by jeevatkm** [comment]
@jose-sanchezm Thanks for reaching out.

There are two issues in your code.
* Incorrect URL is used in both requests
* Log level is not set in logger instance, before passing it to Resty

```diff
diff --git a/main.go b/main.go
index ed80d60..8fe8abf 100644
--- a/main.go
+++ b/main.go
@@ -9,10 +9,13 @@ func main() {
 	logrus.Info("Initializing")
 	logrus.SetLevel(logrus.DebugLevel)
 	logrus.Debug("Sending request without logrus")
-	resty.New().SetDebug(true).R().Get("www.google.com")
+	_, err := resty.New().SetDebug(true).R().Get("www.google.com")
+	logrus.Error(err)
 	logrus.Debug("Request sent")
 
-	logrus.Debug("Sending request with logrus")
-	resty.New().SetLogger(logrus.New()).SetDebug(true).R().Get("www.google.com")
-	logrus.Debug("Request sent")
+	logger := logrus.New()
+	logger.SetLevel(logrus.DebugLevel)
+	logger.Debug("Sending request with logrus")
+	resty.New().SetLogger(logger).SetDebug(true).R().Get("https://www.google.com")
+	logger.Debug("Request sent")
 }

```

**Comment by jeevatkm** [comment]
I'm closing it, answer provided above.
