### ISSUE TITLE
Trace context overrides request context if EnableTrace

### ISSUE THREAD

**Issue by xixinjie** [go-resty/resty#285]
If set a cancellable context and enable trace, the request context will be overridden by the trace context, thus cancellation not working any more.
```go
ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
...
res, err := resty.New().R().SetContext(ctx).EnableTrace().Get(url)
```

To fix it, we can create a trace context based on request context if specified, see PR https://github.com/go-resty/resty/pull/284

**Comment by jeevatkm** [comment]
Merged #284 👍
