### ISSUE TITLE
resty: concurrent map writes

### ISSUE THREAD

**Issue by volodimyr** [go-resty/resty#291]
```
fatal error: concurrent map writes
 goroutine 320238 [running]:
runtime.throw(0xd97d78, 0x15)
/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc001b518f8 sp=0xc001b518c8 pc=0x42e032
runtime.mapassign_faststr(0xcdd0e0, 0xc0002f8cc0, 0xc00170ea70, 0xc, 0x58)
/usr/local/go/src/runtime/map_faststr.go:199 +0x3da fp=0xc001b51960 sp=0xc001b518f8 pc=0x4144da
net/textproto.MIMEHeader.Set(0xc0002f8cc0, 0xd8f207, 0xc, 0xc000be7400, 0x20)
/usr/local/go/src/net/textproto/header.go:22 +0xaf fp=0xc001b519b0 sp=0xc001b51960 pc=0x684b2f
0xd8f207, 0xc, 0xc000be7400, 0x20)
/usr/local/go/src/net/http/header.go:32 +0x53 fp=0xc001b519e8 sp=0xc001b519b0 pc=0x6f40d3
gopkg.in/resty%2ev1.(*Client).SetHeader(0xc00030d800, 0xd8f207, 0xc, 0xc000be7400, 0x20, 0x0)
/go/pkg/mod/gopkg.in/resty.v1@v1.12.0/client.go:144 +0x57 fp=0xc001b51a20 sp=0xc001b519e8 pc=0x9f33f7

```

Recently my service panic due to this reason. As far as I understand it makes value copy of `http.Trasport{} ` somewhere and sometime when service calls `.SetHeader()` it panics.
A related issue in Golang community: https://github.com/golang/go/issues/31352

Service creates new resty client by using the next method and injects them in each controller:
```
func newRestyClient(host string) *resty.Client {
	return resty.New().
		SetHostURL(host).
		SetTimeout(15 * time.Second)
}
```
Can you help me?

**Comment by moorereason** [comment]
@volodimyr, did you run `go vet` on your project?  What release of Go and resty are you using?

**Comment by volodimyr** [comment]
@moorereason 
go: 1.11
We used gopkg.in/resty.v1 v1.12.0 and panic occurred. 
Now we use github.com/go-resty/resty/v2 v2.1.0 and panic still occurs. 

`go vet ./...` gives me nothing sufficient.

**Comment by volodimyr** [comment]
We shot ourselves in the foot. Basically, we share the client between controllers. In one of the case we simply did next:
`r.client.SetHeader("X-AUTH-TOKEN", xAuth).SetHeader("Content-Type", "application/json").`
instead of
`r.client.R().SetHeader("X-AUTH-TOKEN", xAuth).SetHeader("Content-Type", "application/json").`

**Comment by oyjjpp** [comment]
@volodimyr  Hello, how to solve this problem？We also have this problem

`
fatal error: concurrent map writes
goroutine 2712 [running]:
runtime.throw(0xc6e8b0, 0x15)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0015b2cd0 sp=0xc0015b2ca0 pc=0x4312f2
runtime.mapassign_faststr(0xbd04e0, 0xc001572a80, 0xc6120c, 0x5, 0x0)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x417 fp=0xc0015b2d38 sp=0xc0015b2cd0 pc=0x415427
net/url.Values.Set(...)
	/usr/local/go/src/net/url/url.go:846
github.com/go-resty/resty/v2.(*Request).SetQueryParam(...)
	/root/go/pkg/mod/github.com/go-resty/resty/v2@v2.2.0/request.go:121`

**Comment by moorereason** [comment]
@oyjjpp, see the last comment by @volodimyr for the solution to the original issue.  If you need any more assistance, please open a new issue.

**Comment by oyjjpp** [comment]
@moorereason  Okay,thanks

**Comment by bigfoot31** [comment]
> We shot ourselves in the foot. Basically, we share the client between controllers. In one of the case we simply did next:
> `r.client.SetHeader("Content-Type", "application/json").`
> instead of
> `r.client.R().SetHeader("Content-Type", "application/json").`

should add this to FAQ or highlighted in examples
