### ISSUE TITLE
Can't parse 'struct' body when http method is GET

### ISSUE THREAD

**Issue by pelly-ryu** [go-resty/resty#294]
https://github.com/go-resty/resty/blob/7a9880107942440bdca20fe3e7217022ee35da73/util.go#L236-L238

This function prevents it.

but If I pass a byte buffered body, then it works.

---

About HTTP GET and request body:

> The RFC2616 referenced as "HTTP/1.1 spec" is now obsolete. In 2014 it was replaced by RFCs 7230-7237. Quote "the message-body SHOULD be ignored when handling the request" has been deleted. It's now just "Request message framing is independent of method semantics, even if the method doesn't define any use for a message body" The 2nd quote "The GET method means retrieve whatever information ... is identified by the Request-URI" was deleted.

 - https://stackoverflow.com/a/983458

**Comment by jeevatkm** [comment]
@pelly-ryu Thanks for reporting an issue and discussing your concerns. I'm aware of the RFC updates in this aspect.  There was an option added to Resty in the PR #82 to allow sending the body in the GET request.

This method `SetAllowGetMethodPayload()` is the one you need here. Can you please try it out and share your feedback?

In the future, we can make this a default behavior to allow it.

**Comment by jeevatkm** [comment]
I'm closing it. Thanks.
