### ISSUE TITLE
Redirect History support

### ISSUE THREAD

**Issue by theblackturtle** [go-resty/resty#295]
Hi, I think it will be nice if you support Redirect history logs.

**Comment by jeevatkm** [comment]
@theblackturtle Thank you for suggesting a feature in the Resty.

**Comment by jeevatkm** [comment]
@theblackturtle FYI, until resty brings the redirect history support. I think you could build redirect history using custom redirect policy in the resty.

**Comment by theblackturtle** [comment]
Thanks, I'm using it. I just suggest the new feature xD

**Comment by jeevatkm** [comment]
Done!
