### ISSUE TITLE
Resty not binding for a non 200 response

### ISSUE THREAD

**Issue by rushmorem** [go-resty/resty#3]
Hi,

Thanks for the awesome library!

I have a struct that I'm filling with a `JSON` response from an API endpoint using `SetResult`. When the endpoint returns a `200` (success status), this struct is filled in just fine. However, when it returns say a `4XX` or `5XX` error message this struct is empty even though the response body itself has proper `JSON`.

**Comment by rushmorem** [comment]
Just noticed the documentation for `SetResult` says it will automatically unmarshal "if response status code is greater than 399". I guess you meant "less than" instead of "greater than". However, why this restriction?

**Comment by jeevatkm** [comment]
Thanks, will continue to make it better along with community.

I would say it is handled based on scenario Success and Failure/Error. I will describe how it is currently  structured then share your thoughts. *Good catch on documentation end, I have the corrected it*. 

* If status code is between 200 and 299 considered as success, you can retrieve via `response.Result()`
* If status code is greater than 399 considered as failure/error, you can retrieve via `response.Error()`

More info, please have a look at [parseResponseBody](https://github.com/go-resty/resty/blob/master/middleware.go#L257) middleware.

**Comment by jeevatkm** [comment]
Let's say, you have unified Error structure for all request. In that case, Resty has option of setting Error at client level, instead of every request.
```go
resty.SetError(&Error{})           // or  resty.SetError(Error{})  
```

**Comment by rushmorem** [comment]
Makes sense. Thanks for clarifying.
