### ISSUE TITLE
OnAfterResponse.

### ISSUE THREAD

**Issue by fewpiwork** [go-resty/resty#302]
I want to automatically process cookies, but. It seems that OnAfterResponse will not call when redirection occurs

any example?

![image](https://user-images.githubusercontent.com/32926982/73354031-b163e980-42cf-11ea-83a3-2d16fd79eac3.png)

**Comment by jeevatkm** [comment]
@fewpiwork By default Go HTTP client treats the redirects as a separate flow.  Resty provides the [RedirectPolicy](https://pkg.go.dev/github.com/go-resty/resty/v2?tab=doc#RedirectPolicy), so can try this for cookies processing when the redirect happens.

**Comment by jeevatkm** [comment]
@fewpiwork ping!

**Comment by jeevatkm** [comment]
@fewpiwork I'm closing it.
