### ISSUE TITLE
Unable to get latest v0 version with Go Modules

### ISSUE THREAD

**Issue by IvanRibakov** [go-resty/resty#303]
I'm using API bindings generated by `swagger-codegen` v2.2.3 which imports Resty like this:

```
import (
	...
	"gopkg.in/go-resty/resty.v0"
)
```

When I execute `go build` on the project, `go.mod` for my project is updated with following entries:

```
require (
        ...
	golang.org/x/net v0.0.0-20200114155413-6afb5195e5aa // indirect
	golang.org/x/tools v0.0.0-20200130002326-2f3ba24bd6e7 // indirect
	gopkg.in/go-resty/resty.v0 v0.4.1
)
```

and build fails with the following error:

```
rClient.SetTransport undefined (type *resty.Client has no field or method SetTransport)
```

If I manually change `v0.4.1` to `v0.13` I get `go.mod:8: no matching versions for query "v0.13"`.

I'm using Go Modules and go version `1.13.3`.

Any idea as to how I can use more recent v0 version with go modules?

**Comment by jeevatkm** [comment]
@IvanRibakov The issue you're facing is `go mod` requirement. go mod requires full semver so technically is supposed to be `v0.13.0`. 

`v0.13` was released in Jun 2017, it's not `go mod` compatible.  I think you can safely try `v1.7.0` and I don't recall any breaking changes.

Can you please try and share your feedback?

```
gopkg.in/go-resty/resty.v1 v1.7.0
```

**Comment by jeevatkm** [comment]
@IvanRibakov How did it go?
