### ISSUE TITLE
TraceInfo - TotalTime does not include DNSLookup time

### ISSUE THREAD

**Issue by sbengo** [go-resty/resty#304]
Hello,

First of all, thanks for this awesome library!
We are using resty to do some HTTP and API test and retrieve metrics from `EnableTrace`  and `TraceInfo` features.

After do some test, we have seen that `TotalTime` is not including `DNSLookupTime`

![image](https://user-images.githubusercontent.com/13196237/73456798-d8272c00-4372-11ea-8e9d-3cfd73fb7442.png)

On this repo README's example:

```
DNSLookup    : 2.21124ms
ConnTime     : 393.875795ms
TLSHandshake : 319.313546ms
ServerTime   : 71.109256ms
ResponseTime : 94.466µs
TotalTime    : 465.301137ms
IsConnReused : false
IsConnWasIdle: false
ConnIdleTime : 0s
=================
TotalTime = TLSHandshake + ConnTime + ServerTime + ResponseTime
```

Digging into net/http/httptrace/ and reviewing code from https://github.com/davecheney/httpstat (referenced on https://blog.golang.org/http-tracing), the `TotalTime` is the sum all times, including `DNSLookup`

So:
- Shouldn't `DNSLookup` time be included in `TotalTime` calc?

Thanks,
Regards!

**Comment by jeevatkm** [comment]
@sbengo Thanks for reporting an issue. Yes, the DNS lookup time should be counted against total time. I will have a look and update the logic.

**Comment by sbengo** [comment]
Great @jeevatkm ! Thanks for the answer and for accepting the issue!
Ask me if you need me to test it or something else!

Thanks,
Regards!

**Comment by jeevatkm** [comment]
@sbengo Can you please try the branch `next-dev-prep` and share your feedback?

**Comment by sbengo** [comment]
Hi @jeevatkm !

Thanks for the commit and sorry for the late answer. 

I have been reviewing the original issue and I think I missed something on my first analisis (sorry!), the original `TotalTime` seems not be the sum of all times (even excluding `DNSLookup` time).

I have tried your last version directly using your `README` example and got the following results:

```bash
...
Get("https://httpbin.org/get")
....

Request Trace Info:
--> DNSLookup    : 1.101667ms
--> ConnTime     : 430.76598ms
--> TLSHandshake : 322.586439ms
--> ServerTime   : 133.343242ms
--> ResponseTime : 214.442µs
--> TotalTime    : 564.245462ms
--> IsConnReused : false
--> IsConnWasIdle: false
--> ConnIdleTime : 0s
```

-  `TotalTime` is not the sum of all times: `TotalTime < DNSLookup+ConnTime+TLSHandshake+ServerTime+ResponseTime`
- `TotalTime` seems to be calculated correctly (reviewing the code), but seems that some of the generated times are being included in others. I tried to do some combinations but couldn't get it at all (best aproach is `ConnTime + ServerTime`)

So:
- What times need to be sum to retrieve exactly `TotalTime` 
- What time is being included on the others ?
- Could be possible that you are missing some other time?
- Sorry for any inconvenience it may cause, but can't be `TraceInfo` generated as https://github.com/davecheney/httpstat/blob/master/main.go#L221-L366 does?


Ask me if you need more test or other reports!

Thanks,
Regards!

**Comment by jeevatkm** [comment]
@sbengo Thanks, I have noticed the difference that you're described above during analysis.  Also, I have fixed it.

Can you please confirm "You tested using codebase from branch **next-dev-prep**"?

_PS: The fix is not merged into master yet or released._

**Comment by jeevatkm** [comment]
PR #321 addresses this bug. Thanks.

**Comment by sbengo** [comment]
Hi @jeevatkm , sorry for late answer.

First of all, the analysis done on https://github.com/go-resty/resty/issues/304#issuecomment-592462718 was using the branch `next-dev-prep` and commit `1b451e1`, referenced on my `go.mod` as follows (im not very familiar with go-modules, so correct me if I did something wrong):

```
github.com/go-resty/resty/v2 v2.2.1-0.20200225093539-1b451e1f9dd3 // indirect
```

I have repeated the same test with the merge commit on master (https://github.com/go-resty/resty/commit/b744699ec61e62b25f88d9b2d0411b0b490313ce) and as I have seen, the results seem have the same behaviour seen on previous comment:

```
github.com/go-resty/resty/v2 v2.2.1-0.20200302015200-b744699ec61e // indirect
```

```
Request Trace Info:
--> DNSLookup    : 45.771997ms
--> ConnTime     : 574.706095ms
--> TLSHandshake : 408.474887ms
--> ServerTime   : 235.133106ms
--> ResponseTime : 268.092µs
--> TotalTime    : 810.012315ms
--> IsConnReused : false
--> IsConnWasIdle: false
--> ConnIdleTime : 0s
```
-  `TotalTime` is not the sum of all times: `TotalTime < DNSLookup+ConnTime+TLSHandshake+ServerTime+ResponseTime`
- `TotalTime` seems to be calculated correctly (reviewing the code), but seems that some of the generated times are being included in others. I tried to do some combinations but couldn't get it at all (best aproach is `ConnTime + ServerTime`)

You can repro on the following playground (obviously not working due to forbidden http request): https://play.golang.org/p/98oRpRPbWIH

So (sorry for reasking the same the questions done above):

- What times need to be sum to retrieve exactly `TotalTime` 
- What time is being included on the others ?
- Could be possible that you are missing some other time?
- Sorry for any inconvenience it may cause, but can't be `TraceInfo` generated as https://github.com/davecheney/httpstat/blob/master/main.go#L221-L366 does?

Thanks again,
Regards!

**Comment by sbengo** [comment]
Hi @jeevatkm , excuse the insistence, but:

- Can you review the last comment and check if this issue needs to be reponed?

Thanks,
Regards

**Comment by moorereason** [comment]
For the record, I made a quick Go program (without resty) that just prints timestamps at each trace hook:

```
GetConn: 2020-03-09 09:51:07.196262433 -0500 CDT m=+0.000369901
DNSStart: 2020-03-09 09:51:07.197280433 -0500 CDT m=+0.001387801
DNSDone: 2020-03-09 09:51:07.218209735 -0500 CDT m=+0.022317203
ConnectStart: 2020-03-09 09:51:07.218567535 -0500 CDT m=+0.022675003
TLSHandshakeStart: 2020-03-09 09:51:07.254700839 -0500 CDT m=+0.058808207
TLSHandshakeDone: 2020-03-09 09:51:07.383215352 -0500 CDT m=+0.187322820
GotConn: 2020-03-09 09:51:07.383581652 -0500 CDT m=+0.187689120
WroteHeaders: 2020-03-09 09:51:07.383851152 -0500 CDT m=+0.187958520
WroteRequest: 2020-03-09 09:51:07.384023452 -0500 CDT m=+0.188130920
GotFirstResponseByte: 2020-03-09 09:51:07.422060056 -0500 CDT m=+0.226167424
Done: 2020-03-09 09:51:07.422157356 -0500 CDT m=+0.226264724
```

I just noticed that resty is using `GetConn` to check for zero DNS times instead of `ConnectStart`.  That needs to be fixed.

I think all of the timings that Resty prints are helpful for tracing/debugging.  I'd have to look more closely at what Resty's doing, but it may just bee that the docs need to be updated to make it clear how these hooks/timings relate to each other.

**Comment by sbengo** [comment]
Hi @moorereason , thanks for reviewing it

A first PR #331 is requested to fix this issue

@jeevatkm , can you reponen this issue?

Thanks,
Regards!
