### ISSUE TITLE
Add logging/exporting as curl request(s)

### ISSUE THREAD

**Issue by corvinusz** [go-resty/resty#305]
Hello.

Is it possible to add feature to log (or export to std/writer/...) go-resty requests as text curl commands?
Mb I just missed the way to do it.

Best...

**Comment by jeevatkm** [comment]
@corvinusz Is this similar to #292 request? can you please check.

**Comment by corvinusz** [comment]
Seems it is not.
This issue is about generation of bash-like command line parameters for /usr/bin/curl. It will be very helpful for integration go-resty with other tools (with different langs/frameworks).

Mentioned #292 request is about logging of real network packets sent

**Comment by jeevatkm** [comment]
@corvinusz Thanks for your response.  

If you're referring to the generation of curl CLI statements/commands from Resty.  Then it might take considerable effort to bring completion factors. What we can do, we can place this idea in a backlog and get to it later.

**Comment by moorereason** [comment]
Tightly coupling a log to the curl CLI would be a headache to maintain.  As a middle ground, you could consider logging the request properties as JSON and leave it up to the user to convert to curl or any other tool.

**Comment by jeevatkm** [comment]
@moorereason has a point. Yes, I agree. We should not couple this.

**Comment by jeevatkm** [comment]
@moorereason @corvinusz will work on providing demand way to get request attributes as JSON.

**Comment by lrita** [comment]
Using `github.com/moul/http2curl` in callback of `SetPreRequestHook()` will perform it easily.

**Comment by jeevatkm** [comment]
I'm closing this issue, in-favor of @lrita package reference https://github.com/go-resty/resty/issues/305#issuecomment-631984779
