### ISSUE TITLE
is there any reason for retries not to be configured per request?

### ISSUE THREAD

**Issue by renathoaz** [go-resty/resty#315]
Hi there,
I noticed that retries are configured per client, 
is there any reason not to be per request?

Should I always create a new client each time I want to change RetryCount, RetryMaxWaitTime or RetryCondition without affecting one another if it runs concurrently?

For example:
```
defaultClient := resty.New()


func One() error{
client.
   defaultClient.SetRetryCount(3).SetRetryMaxWaitTime(20 * time.Second)
   defaultClient.R().Post........
}

func Two() error{
client.
   defaultClient.SetRetryCount(5).SetRetryMaxWaitTime(10* time.Second)
   defaultClient.R().Post........
}
```
in that case I should create a new instance for each function, right ?

**Comment by jeevatkm** [comment]
@renathoaz Thanks for reaching out. 

Retries are usually gets configured at the client level.  E.g.:  let's say the application needs to integrate with two services. Then typically people create two dedicated client instances with appropriate settings for each service of nature and thrid one they will create for general usage.

Begin said that technically it is possible to add new enhancement for Retries that collect the following values which override the client level values-
```
RetryCount
RetryWaitTime
RetryMaxWaitTime
RetryConditions
```

**Comment by renathoaz** [comment]
I got it. maybe not worth the effort. Thank you for the excellent project.

**Comment by jeevatkm** [comment]
@renathoaz I thought to inform. RetryConditions at the request level enhancement PR #436 got submitted. Will close this one after the merge.

**Comment by aadog** [comment]
@雷纳索斯 I implemented session pattern, you can use
