### ISSUE TITLE
OnRequestLog, OnResponseLog fail if not SetDebug(true)

### ISSUE THREAD

**Issue by OJFord** [go-resty/resty#317]
```go
client.OnRequestLog(
    // ...
)
```

and
```go
client.OnResponseLog(
    // ...
)
```

have no effect without `client.SetDebug(true)`.

**Comment by jeevatkm** [comment]
@OJFord Yes, it's implemented that way. I think the better method name could have been `OnRequestDebugLog ` and `OnResponseDebugLog `.

**Comment by jeevatkm** [comment]
I'm closing it.
