### ISSUE TITLE
Proxies does not work

### ISSUE THREAD

**Issue by vlourme** [go-resty/resty#320]
Hi, I'm facing issues with proxies. When I use proxies with authentication (like Luminati) I'm always facing this issue : `Auth Failed (code: ip_forbidden)`

Actually I tried to set a proxy using this :
- `client.SetProxy("http://username:password@host:port")`
and I also tried to do with that :
- `client.SetProxy("http://host:port")` and putting a `Proxy-Authorization` header with `Basic <username:password in base64)` as value. This method comes from this library but it seems not working: https://github.com/Elph/luminati/

Both options did not work, I really need to get proxies to work :/
Thanks in advance.

Edit: It's maybe my fault, I retried with another proxy, and it seems to work, but it's still pretty unstable, even more with public proxies. It's weird, some others languages are able to handle proxies without any issues (C# for example works well with proxies).

**Comment by jeevatkm** [comment]
@vlourme Actually, resty handoff the proxy value to GoLang HTTP client. Could you research around to find more info?  I will also try at my end to share my inputs.

**Comment by vlourme** [comment]
> @vlourme Actually, resty handoff the proxy value to GoLang HTTP client. Could you research around to find more info? I will also try at my end to share my inputs.

Actually It’s clearly not a Resty issue, I’ve looked how Resty sets the proxy and the issues does not come from this. It looks like more a Go issue to not handle proxies correctly, but I did not see anything on the web about my problem yet, maybe I could try to open a issue at Go repository

**Comment by jeevatkm** [comment]
@vlourme That's sound good. We can find out from the Go repository. Keep me posted! thanks.

**Comment by vlourme** [comment]
The issue is now in "NeedInvestigation" label from go repository (https://github.com/golang/go/issues/37623). Maybe we should close this issue, I think go-resty is no more involved in the issue, thanks for helping!

**Comment by jeevatkm** [comment]
I'm closing it in favor of golang repo issue.

**Comment by aivencs** [comment]
Good example in here


```
# 1 you need parse the proxy url
uri, _ := url.Parse("http://username:password@host:port")
# 2 create new transport, base on proxy url 
client.SetTransport(&http.Transport{
	Proxy: http.ProxyURL(uri),
})
# 3 resty client set proxy
client.SetProxy("http://username:password@host:port")
```
