### ISSUE TITLE
Request level retry strategy support

### ISSUE THREAD

**Issue by NeoCN** [go-resty/resty#324]
Is there plan to support request level retry strategy? Currently request will use client retry strategy, and can not override at request level.

**Comment by jeevatkm** [comment]
FYI, yes - https://github.com/go-resty/resty/issues/315#issuecomment-593189957

**Comment by jeevatkm** [comment]
@NeoCN I thought to inform you. RetryConditions at the request level enhancement PR #436 got submitted by @rohitkg98. Will close this one after the merge.
