### ISSUE TITLE
how to properly use resty client with echo framework

### ISSUE THREAD

**Issue by ryanembregts** [go-resty/resty#326]
Good day, 

I am using echo framework to use different request and then using awesome resty client to forward those requests upstream. Thanks for great work.  

I need suggestions about the best way to use resty, 

1. Should i use a single client and share it between different routes?
`client := resty.New()`

2. Or each route should have its own client. 

Any suggestion is much appreciated. 
Thanks.

**Comment by jeevatkm** [comment]
@ryanembregts Thank you for your appreciation. 
I would suggest you to having a resty client **per upstream host** along with its respective settings.
