### ISSUE TITLE
option to not encode form data

### ISSUE THREAD

**Issue by alidhkh** [go-resty/resty#327]
Hi, I've been using resty for a while now, and man, this is superb! Thank you for this awesome library.

I'm trying to post using SetFromData, one of the fields contains JSON, so while sending request, resty encodes the JSON inside that field; But the receiving server rejects the request because it doesn't contain a valid JSON.

I know there's a `SetJSONEscapeHTML` method, but that only works when the whole body is JSON. I guess a method to ignore specific fields or the whole form like `SetFormBodyEscapeHTML`, would be awesome.

Thank you again.

**Comment by lrita** [comment]
I think it is your server endpoint's issue. 

I think you want send `x={"abc":"de"}` to server, server got `x=%7B%22abc%22%3A%22de%22%7D`, this is legally.

**Comment by jeevatkm** [comment]
@lrita Thank you.

@alidhkh Thanks for your appreciation. 
I'm not sure I fully understand your issue. Would you mind providing an example to describe the issue?

**Comment by alidhkh** [comment]
@jeevatkm Hi, this an example:
```
apps={"raider":false,"explorer":false,"vision":false}&app_version=1.19.6146
```
When I try to POST this to a server using resty, the server rejects the request because the JSON inside the request is encoded. I though it would be a good feature to choose if we want to send a raw request or encoded.

**Comment by jeevatkm** [comment]
@alidhkh I'm sorry for the delayed response.

It seems server endpoint design has an issue. Based on the above example, you're using typically FORM fields but sending JSON data in the field.  Technically the server endpoint has to decode it before processing.

**Comment by jeevatkm** [comment]
I'm closing this one.
