### ISSUE TITLE
Should I create a new client for each request? How to use http client pool?

### ISSUE THREAD

**Issue by xiaoxfan** [go-resty/resty#328]
My application is frequently requests third-party API, I create a new client for each request,but sometimes, when multiple goroutines request concurrently (eg. 1000 goroutines),
```go
for i:=0;i<1000;i++{
  go GetRawResp(url,headers,queryparams)
}

func GetRawResp(url string, headers map[string]string, queryParams map[string]string) (resp *resty.Response, err error) {
	client := resty.New()
	resp, err = client.R().
		SetHeaders(headers).
		SetQueryParams(queryParams).
		Get(url)
	return resp, err
}
```
I got an error :
` dial tcp REMOTEHOST:PORT: socket: too many open files`
Are there any suggestions for use in this situation? Such as http client pool?

**Comment by xiaoxfan** [comment]
Does the connection close automatically? Or is there any way I can close it manually?

**Comment by jeevatkm** [comment]
@xiaoxfan Thanks for reaching out.
* HTTP connection pooling is maintained by internal Go HTTP client automatically 
* Do not create a client for every request. Move this line `client := resty.New()` out of the func 
* Connection gets closed automatically sent to pool

**Comment by xiaoxfan** [comment]
@jeevatkm Thanks for your suggestion.

**Comment by bigfoot31** [comment]
Add this to the readme/FAQs
