### ISSUE TITLE
problem with  resty.Unmarshalc(..)

### ISSUE THREAD

**Issue by latenite4** [go-resty/resty#329]
running on ubuntu 18.04 sending GET request to rapidAPI "coronavirus/cases_by_country.php" API.
API server responds with correct JSON and the Unmarshalc routine returns err == nil.
here is partial example of JSON response:
{
  "countries_stat": [
    {
      "country_name": "",
      "cases": "721",
      "deaths": "13",
      "region": "",
      "total_recovered": "619",
      "new_deaths": "0",
      "new_cases": "0",
      "serious_critical": "10",
      "active_cases": "89",
      "total_cases_per_1m_population": "0"
    },
    {
      "country_name": "USA",
      "cases": "466,969",
      "deaths": "16,636",
      "region": "",
      "total_recovered": "25,316",
      "new_deaths": "1,845",
      "new_cases": "31,939",
      "serious_critical": "10,011",
      "active_cases": "425,017",
      "total_cases_per_1m_population": "1,411"
    },

i have tried unmarshaling into 
type AutoGenerated2 struct {
	CountriesStat []struct {
		CountryName               string `json:"country_name"`
		Cases                     string `json:"cases"`
		Deaths                    string `json:"deaths"`
		Region                    string `json:"region"`
		TotalRecovered            string `json:"total_recovered"`
		NewDeaths                 string `json:"new_deaths"`
		NewCases                  string `json:"new_cases"`
		SeriousCritical           string `json:"serious_critical"`
		ActiveCases               string `json:"active_cases"`
		TotalCasesPer1MPopulation string `json:"total_cases_per_1m_population"`
	} `json:"countries_stat"`
	StatisticTakenAt string `json:"statistic_taken_at"`
} and also into
type AutoGenerated2 struct {
	CountriesStat [212]struct {
		CountryName               string `json:"country_name"`
		Cases                     string `json:"cases"`
		Deaths                    string `json:"deaths"`
		Region                    string `json:"region"`
		TotalRecovered            string `json:"total_recovered"`
		NewDeaths                 string `json:"new_deaths"`
		NewCases                  string `json:"new_cases"`
		SeriousCritical           string `json:"serious_critical"`
		ActiveCases               string `json:"active_cases"`
		TotalCasesPer1MPopulation string `json:"total_cases_per_1m_population"`
	} `json:"countries_stat"`
	StatisticTakenAt string `json:"statistic_taken_at"`
}
in both cases, err is returned as nil but structures are empry - i.e. the unmarshal did not happen.

here is a sample of my golang code:
var stat statStruct

	cvUrl := CVURL + "coronavirus/cases_by_country.php"
	client := resty.New()
	resp, err := client.R().
		SetHeader("Accept", "application/json").
		SetHeader("x-rapidapi-host", "coronavirus-monitor-v2.p.rapidapi.com").
		SetHeader("x-rapidapi-key", tokenRapidAPI).
		Get(cvUrl)
	utilz.Check(err, "get CVURL error ", true)

	if resp.IsSuccess() {
		var hdrContentTypeKey = http.CanonicalHeaderKey("Content-Type")
		ct := resp.Header().Get(hdrContentTypeKey)
		err = resty.Unmarshalc(client, ct, resp.Body(), &responseStruct)
		utilz.Check(err, "CV response unmarshal fail\n", true)

... }
please tell me what I am doing wrong in the unmarshal.

i have attached a seperate file which has the full JSON response in it.
[tmpfile.txt](https://github.com/go-resty/resty/files/4459205/tmpfile.txt)

**Comment by latenite4** [comment]
note there are 212 entries in the JSON array

**Comment by latenite4** [comment]
note: i tried resty v1 and resty v2 and i see the same problem

**Comment by lrita** [comment]
What is the `Content-Type` header of response? Is it a validated json hit?

**Comment by jeevatkm** [comment]
@latenite4 Thanks for reporting your observation. Could you please provide a test case/code snippet which demonstrates an issue?

**Comment by mattfenwick** [comment]
I ran into something similar to this -- in my case, the value for the `Content-Type` header is `application/vnd.docker.distribution.manifest.v1+prettyjws`.

Is there a way to tell Resty to parse the response as JSON and use the `Result` struct anyway in this case?  @jeevatkm 

Thanks for the help, love the project!

**Comment by jeevatkm** [comment]
@mattfenwick @latenite4 you could make use these methods -
* https://pkg.go.dev/github.com/go-resty/resty/v2?tab=doc#Request.ForceContentType
* https://pkg.go.dev/github.com/go-resty/resty/v2?tab=doc#Request.ExpectContentType
