### ISSUE TITLE
SetMultiValueFormData

### ISSUE THREAD

**Issue by mdreizin** [go-resty/resty#33]
Hello,

It would be nice to have `SetMultiValueFormData` which should work in the same way as `SetMultiValueQueryParams` but for `FormData`:

```go
q, err := query.Values(struct {}{})

for p, v := range q {
	for _, pv := range v {
		client.FormData.Add(p, pv)
	}
}
```

```go
q, err := query.Values(struct {}{})

client.SetMultiValueFormData(q)
```

**Comment by jeevatkm** [comment]
Will take care, thanks!

**Comment by jeevatkm** [comment]
Closing this issue, PR #38 will be merged.
