### ISSUE TITLE
Bug:  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zbqyexingkong** [go-resty/resty#330]
for  resty@v2.2.0;
when i set debug is true, and  new a client with **NewWhiteClient(http.DefaultClient)**,
the client Jar is nil . in requestLogger func used composeHeaders

https://github.com/go-resty/resty/blob/ad527ebb23b1ffdeba0c8b9b096190c001061711/middleware.go#L275

https://github.com/go-resty/resty/blob/ad527ebb23b1ffdeba0c8b9b096190c001061711/middleware.go#L290

```golang
func composeHeaders(c *Client, r *Request, hdrs http.Header) string {
	str := make([]string, 0, len(hdrs))
	for _, k := range sortHeaderKeys(hdrs) {
		var v string
		if k == "Cookie" {
			cv := strings.TrimSpace(strings.Join(hdrs[k], ", "))
                       // Bug: c.GetClient().Jar maybe is nil
			for _, c := range c.GetClient().Jar.Cookies(r.RawRequest.URL) {  
				if cv != "" {
					cv = cv + "; " + c.String()
				} else {
					cv = c.String()
				}
			}
			v = strings.TrimSpace(fmt.Sprintf("%25s: %s", k, cv))
		} else {
			v = strings.TrimSpace(fmt.Sprintf("%25s: %s", k, strings.Join(hdrs[k], ", ")))
		}
		if v != "" {
			str = append(str, "\t"+v)
		}
	}
	return strings.Join(str, "\n")
}
```

**Comment by jeevatkm** [comment]
@zbqyexingkong Thanks for reporting an issue. Sure I will address the nil pointer issue with adding nill check.
