### ISSUE TITLE
An exception occurred while executing the go mod

### ISSUE THREAD

**Issue by 2030405043** [go-resty/resty#332]
go mod tidy

github.com/go-resty/resty: github.com/go-resty/resty@v1.12.0: parsing go.mod:
	module declares its path as: gopkg.in/resty.v1
	        but was required as: github.com/go-resty/resty

**Comment by 2030405043** [comment]
go version 1.13 
windows 10

**Comment by 2030405043** [comment]
github.com/go-resty/resty: github.com/go-resty/resty@v1.12.0: parsing go.mod:
        module declares its path as: gopkg.in/resty.v1
                but was required as: github.com/go-resty/resty

**Comment by jeevatkm** [comment]
@2030405043 Thanks for reporting your concern. I do not have complete insight into your problem. Do you mind taking a look at this issue https://github.com/go-resty/resty/issues/230 and share your feedback?

**Comment by jeevatkm** [comment]
@2030405043 Closing this one.
