### ISSUE TITLE
SetFormData() could support `mutlipart:form-data` by offloading to SetMultipartField?

### ISSUE THREAD

**Issue by ArcticSnowman** [go-resty/resty#336]
I've been trying to make a PUT request to an API that wants the form data as `multipart:form-data`.  Finally worked out (after digging into the code) that SetMultipartField can be used if you don't set the filename and pass in the values via `strings.NewReader(value)`.

```
client.R().
SetMultipartField("branch", "", "", strings.NewReader(branch)).
SetMultipartField("sourceBranch", "", "", strings.NewReader(sourceBranch)).
SetMultipartField("content", "", "", strings.NewReader(mergeLines(content))).
```

It got me thinking that SetFormData could be enhanced or a new SetMultipartFormData() added. Such that it you can simply pass in a `map(string)string` of key/values paris and it handles the `strings.NewReader` bits to pass to `SetMultipartField()`

**Comment by jeevatkm** [comment]
PR #337 is merged.
