### ISSUE TITLE
incorrect traceinfo upon timeout

### ISSUE THREAD

**Issue by rightjoin** [go-resty/resty#338]
When a request timesouts, the data is traceinfo is incorrect.

Often connection time, Response time etc will have max or min possible int64 values

**Comment by jeevatkm** [comment]
@rightjoin Thanks for reporting an issue, surely I will look into it. 

There is a recent contribution to trace info by @JoaquinJimenezGarcia on #331. Can you please give it a try and share some sample test case for the issue?

**Comment by jeevatkm** [comment]
Also, I have created [v2.3.0-rc.1](https://github.com/go-resty/resty/tree/v2.3.0-rc.1), you could try out.

**Comment by rightjoin** [comment]
Hi Jeevatkm,

I don't see it resolved in the rc1.

Here is a quick test case:

```
func TestTraceInfoCorerctOnTimeout(t *testing.T) {

	client := resty.New().EnableTrace()
	client.SetTimeout(10 * time.Millisecond)

	req := client.R()
	req.Get("http://123.123.123.123/")

	trace := req.TraceInfo()

	if trace.ConnTime == math.MinInt64 {
		t.Errorf("Conn time should not be MinInt64 or less than 0")
	}

	if trace.ResponseTime == math.MaxInt64 {
		t.Errorf("Response time should not be MaxInt64")
	}
}

```

Thanks for the amazing library.

**Comment by moorereason** [comment]
If the connection times out, how useful is the trace info?

**Comment by moorereason** [comment]
To be clear, I agree that the trace values are inaccurate in this scenario.  I'm just curious what your use case is for using the trace info on failed requests.

**Comment by rightjoin** [comment]
There are a number of requests generated for the server, and TraceInfo stats are being aggregated.
