### ISSUE TITLE
request.SetQueryParams with int value

### ISSUE THREAD

**Issue by haalcala** [go-resty/resty#343]
How can I pass an int value to request.setQueryParams if the signature only accepts map[string]string?

**Comment by moorereason** [comment]
[`strconv.Itoa`](https://golang.org/pkg/strconv/#Itoa)?

**Comment by inix** [comment]
I also have this issue,backend interfaces only accept int query value instead of string.

**Comment by moorereason** [comment]
@inix & @haalcala, help me understand.  I'm envisioning a request such as `https://host/path?param=99`.  How is resty failing to support such a request?  The URL is inherently a string when sent to the host.  What am I missing?

**Comment by jeevatkm** [comment]
@inix @haalcala Closing this one.  @moorereason has given direction and asked for clarification.
