### ISSUE TITLE
Getting improper value for TotalTime

### ISSUE THREAD

**Issue by smaheshs** [go-resty/resty#346]
Hi,

Wrote this simple program to check the effect of the total time when using a connection from a pool.

```
package main

import (
	"fmt"
	"github.com/go-resty/resty/v2"
)

func main() {
	httpClient := resty.New()

	for i := 0; i < 5; i++ {
		url := "http://httpbin.org/get"
		resp, _ := httpClient.R().EnableTrace().Get(url)

		ti := resp.Request.TraceInfo()

		fmt.Println("Loop count", i+1)
		fmt.Println("TotalTime    :", ti.TotalTime)
	}
}
```

In the first loop, the print for TotalTime is proper, however in the subsequent loops, the TotalTime is the same huge value as below:

Loop count 1
TotalTime    : 429.728934ms
Loop count 2
TotalTime    : **2562047h47m16.854775807s**
Loop count 3
TotalTime    : **2562047h47m16.854775807s**
Loop count 4
TotalTime    : **2562047h47m16.854775807s**
Loop count 5
TotalTime    : **2562047h47m16.854775807s**

Could someone please let me know if there is issue in the code above, or if it is caused by a bug in the library.

Thanks.

**Comment by smaheshs** [comment]
I confirmed that I am using the latest version. Go.mod:

`github.com/go-resty/resty/v2 v2.3.0`

**Comment by moorereason** [comment]
The issue is how the TotalTime is calculated when a connection is reused.  I'll work on a fix.
