### ISSUE TITLE
Does resty support RFC7386 ? I tried ,but failed . Will this feature be added in the future?

### ISSUE THREAD

**Issue by niroshea** [go-resty/resty#349]
![image](https://user-images.githubusercontent.com/30043244/85223331-fca0a500-b3f4-11ea-971f-644153b9dd16.png)
![image](https://user-images.githubusercontent.com/30043244/85223343-0d511b00-b3f5-11ea-875a-0d2fc0a1cee0.png)

**Comment by jeevatkm** [comment]
@niroshea Just looked around it seems I have added that support v1.11.0 release #203.
This is the line
https://github.com/go-resty/resty/blob/986808a2a70a71a69fbc463606307692dc7e9e62/client.go#L62

Can you please validate and provide some go test cases?

**Comment by jeevatkm** [comment]
@niroshea Do you have an update?

**Comment by jeevatkm** [comment]
@niroshea Any updates?

**Comment by niroshea** [comment]
I used version 2 before. In order to avoid this problem, I used other components to achieve the function. I am willing to do some tests to see if this problem still exists. wait a moment.

**Comment by niroshea** [comment]
![image](https://user-images.githubusercontent.com/30043244/95544619-3b06b200-0a2e-11eb-89f5-bc04bbd3408d.png)
![image](https://user-images.githubusercontent.com/30043244/95544632-435eed00-0a2e-11eb-9a4f-f10dfefcbae9.png)
![image](https://user-images.githubusercontent.com/30043244/95544640-49ed6480-0a2e-11eb-8ac4-94039d891136.png)

I tested v2.3.0, resty still has this problem

**Comment by niroshea** [comment]
![image](https://user-images.githubusercontent.com/30043244/95544792-be280800-0a2e-11eb-897c-dfb5ad8e8454.png)
![image](https://user-images.githubusercontent.com/30043244/95544812-cd0eba80-0a2e-11eb-8473-ca63f724b3d8.png)
![image](https://user-images.githubusercontent.com/30043244/95544820-d1d36e80-0a2e-11eb-94b2-6ddc481932bb.png)


I tested v2.3.0, resty still has this problem

**Comment by moorereason** [comment]
Can you construct a request with curl or the Go stdlib that is successful?  Can you enable debug to log the underlying request?

**Comment by niroshea** [comment]
> Can you construct a request with curl or the Go stdlib that is successful? Can you enable debug to log the underlying request?

In the first picture, the "patchRequest" function in the first line I marked with a red box is implemented by net/http. It runs very well, and the input parameters are the same as the "restyTest" function.

**Comment by jeevatkm** [comment]
I'm closing this one.
