### ISSUE TITLE
Multiple files posting with same key

### ISSUE THREAD

**Issue by avinash92c** [go-resty/resty#351]
If you check in postman, you can see that u can send an array of under one key in form body.
Using the same thing as reference someone developed a rest API which accepts multiple files as array which I'm trying to consume.

I see your api accepts map of files which if I use for my requirement will just overwrite all files and send only the last file. Could you some how add a new function which accepts slice of files to attach to form.

Please refer to SetFiles function in your code.

Please use the below function as enhancement
```
func (r *Request) SetFile(param, filePath []string) *Request {
	r.isMultiPart = true
	r.FormData.Set("@"+param, filePath)
	return r
}
```

As per url.Values, its a map of string and string slice

**Comment by jeevatkm** [comment]
@avinash92c I think you could achieve the behavior using [`SetFormDataFromValues`](https://pkg.go.dev/github.com/go-resty/resty/v2?tab=doc#Request.SetFormDataFromValues). Can you try and share your feedback?

**Comment by jeevatkm** [comment]
@avinash92c Any updates?

**Comment by LinkinStars** [comment]
@jeevatkm I met same problem. The request just like this:

````bash
curl --location --request POST 'http://127.0.0.1:8080/' \
--form 'name="test"' \
--form 'file=@"123.jpg"' \
--form 'file=@"456.png"'
````

Like you said, using `SetFormDataFromValues` function can solve it. Maybe like this: @avinash92c 
````go
    var urlValues url.Values
    urlValues = make(map[string][]string)
    for _, f := range files {
        urlValues.Add("@"+f.Name, f.AbsolutePath)
    }

    client := resty.New()
    request := client.R()
    request.SetFormDataFromValues(urlValues)
    request.Post(url)
    .....
````

So maybe we can actually implement a method to meet this requirement.
````go
    func (r *Request) SetFileArray(param, filePath []string) *resty.Request {
        r.isMultiPart = true
        for _, fp := range filePath {
            r.FormData.Add("@"+param, fp)
        }
        return r
    }
````

If you think need such a function, I can make a pr.

**Comment by avinash92c** [comment]
I already solved this before making this post. i just thought a simpler and straight forward function might make things much easier to use for others facing same issue.

**Comment by ViCrack** [comment]
I met same problem.

**Comment by youngsailor** [comment]
> I already solved this before making this post. i just thought a simpler and straight forward function might make things much easier to use for others facing same issue. @jeevatkm @LinkinStars Thanks for the responses. very cool alternative solutions.

How did you solve it?

**Comment by aol-nnov** [comment]
FYI, I've ended up with the following snippet:


```
files []string {"path1", "path2",... "pathN"}

req := client.R().SetFile("file", files[0])

for _, toUpload := range files[1:] {
	req.FormData.Add("@file", toUpload)
}
```

For sure, it's not the most intuitive way, but it works! (on my machine 😜)
