### ISSUE TITLE
Find a way to fetch the number of attempt

### ISSUE THREAD

**Issue by christophe-dufour** [go-resty/resty#352]
Retry comes with a nice retry system.
For monitoring reason, I would like to be able when I get a response, how many attempts Resty has to do to complete the request.

Something like that:
```
client := resty.New()SetRetryCount(3).OnAfterResponse(func(c *resty.Client, resp *resty.Response) error {
			metrics.ReportHTTPCall(resp.StatusCode(),resp.Request.Method, somewhere.NumberOfAttempt())
			return nil
		})

```

Is there a way to get that value?

**Comment by moorereason** [comment]
I'm not aware of the number of attempts being exposed by resty, but you can track the attempts yourself as in [here](https://github.com/go-resty/resty/blob/6ad880ce57f42586729e0e7e90be1bceefa68a68/retry_test.go#L180) (using `AddRetryCondition`).

**Comment by jeevatkm** [comment]
@christophe-dufour Did you get a chance to try out the @moorereason's input?

**Comment by jeevatkm** [comment]
@moorereason FYI, resty already have a value also I think it might good to expose in trace info too.
