### ISSUE TITLE
go-resty is support HTTP_CONNECT_POOL?

### ISSUE THREAD

**Issue by feiquan123** [go-resty/resty#353]
i can't see HTTP_CONNECT_POOL from code

**Comment by jeevatkm** [comment]
@feiquan123 HTTP connection pool is maintained by underlying Go HTTP client [`net/http.Client`](https://golang.org/pkg/net/http/#Client), Resty does not maintain any connection pool explicitly.

**Comment by feiquan123** [comment]
fine
