### ISSUE TITLE
User/pass proxies

### ISSUE THREAD

**Issue by jj0e** [go-resty/resty#358]
Is it possible to use proxies that are authenticated via username & password with resty? I was only able to see examples without user/pass.

**Comment by moorereason** [comment]
I haven't had to do this resty yet, but how does your proxy authentication work?  If it's via a basic auth header such as `Proxy-Authorization`, you should be able to add that header to your requests.

```go
client := resty.New()
client.SetProxy("http://proxyserver:8888")

basicAuth := "Basic " + base64.StdEncoding.EncodeToString([]byte("username:password"))
client.SetHeader("Proxy-Authorization", basicAuth)
```

**Comment by jj0e** [comment]
To be honest I'm not sure exactly how it works because I just buy the proxies and they are formatted like ``ip:port:username:pass``. However, I have been using the [Requests](https://requests.readthedocs.io/en/master/user/advanced/#proxies) module in Python where I formatted them like this:

```python
proxies = {'http': 'http://user:pass@10.10.1.10:3128/'}
```

and it worked. So, I'm not exactly sure what the requests module is doing in the background whether it's basic auth or not. I will try your suggestion asap and let you know if it works.

**Comment by moorereason** [comment]
In that case, you can probably just use `client.SetBasicAuth("username", "password")`.

**Comment by jeevatkm** [comment]
@jj0e I'm closing this one, @moorereason have answered your question. Thanks.
