### ISSUE TITLE
capture json request body in OnAfterResponse

### ISSUE THREAD

**Issue by tamal-appsbee** [go-resty/resty#359]
Hi,

I am trying to capture json request body in OnAfterResponse. but its giving me empty response

```
client.OnAfterResponse(func(c *resty.Client, resp *resty.Response) error {
   	req := resp.Request
	reqBody := ""
	rawReqBody, _ := req.RawRequest.GetBody()
	if rawReqBody != nil {
		bodyBytes, _ := ioutil.ReadAll(rawReqBody)
		reqBody = string(bodyBytes)
	}
	fmt.Printf("%+v\n", reqBody) // always coming empty

    return nil  // if its success otherwise return error
  })
```

**Comment by lggomez** [comment]
Since the request body is a buffered reader, once the request is executed that body will be empty

You should instead apply an `OnBeforeRequest` middleware, read the request body into a buffer of your choice and then from it recreate the request body so it can be read during request execution

**Comment by jeevatkm** [comment]
@tamal-appsbee Did you tried the suggestion given by @lggomez?

**Comment by jeevatkm** [comment]
@tamal-appsbee I'm closing this one.

**Comment by tamal-appsbee** [comment]
@jeevatkm @lggomez Sorry for late response. I will try it out.
Thank you.

**Comment by tamal-appsbee** [comment]
> @tamal-appsbee I'm closing this one.

ok
Thank You
