### ISSUE TITLE
No DNS failover possible with resty

### ISSUE THREAD

**Issue by szuecs** [go-resty/resty#36]
Hi!

I have a daemon, which polls some API endpoints. If the API endpoint switch traffic with DNS (changing the IP), then resty will not do a DNS lookup to get the new IP.
I use the default client use the following code:

	urlString := fmt.Sprintf("https://api.endpoint.foo.com/events/%v", ID) // DNS name changed
	resp, err := resty.R().
		SetHeader("Content-Type", "application/json").
		SetBody(body).
		SetAuthToken(cli.AccessToken).
		Put(urlString)

Maybe I can get resty to lookup DNS somehow, but I did not find it, yet.

**Comment by jeevatkm** [comment]
`go-resty` doesn't cache any DNS settings. It uses go httpclient directly.

**Comment by jeevatkm** [comment]
Closing this one, feel free to re-open when you find some issue. Thanks.
