### ISSUE TITLE
Repository should contain go.sum file

### ISSUE THREAD

**Issue by franta** [go-resty/resty#360]
[Should I commit my 'go.sum' file as well as my 'go.mod' file?](https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file)

**Comment by moorereason** [comment]
Agreed.  @jeevatkm, what was the reasoning behind not including `go.sum`?

**Comment by jeevatkm** [comment]
@moorereason @franta During the transition to go modules from gopkg.in also during the release of v2 major version. It caused an issue. Go mod was not friendly at that moment. Also resty has one only dependency, so it had very least impact/need.

**Comment by jeevatkm** [comment]
@franta I have recalled one thing. Go mod was causing an issue between `v2.0.0` and `v2.1.0` releases. Let's add go.mod and will see any issues pop up or not.
