### ISSUE TITLE
Missing error message when Marshal failed

### ISSUE THREAD

**Issue by cascax** [go-resty/resty#361]
If it fails during Marshal JSON or Marshal XML, the Marshal error message is lost. only get "unsupported 'Body' type/value" error. Can it return errors with the original error message?

master/middleware.go:477 
```
	if bodyBytes == nil && r.bodyBuf == nil {
		err = errors.New("unsupported 'Body' type/value")
	}

	// if any errors during body bytes handling, return it
	if err != nil {
		return
	}
```

**Comment by moorereason** [comment]
@cascax,
Can you provide a simple example program that exhibits this behavior?

**Comment by cascax** [comment]
> @cascax,
> Can you provide a simple example program that exhibits this behavior?

```
type MyContent struct{}

func (c MyContent) MarshalJSON() ([]byte, error) {
	return nil, errors.New("MyContent can't MarshalJSON")
}

func main() {
	req := MyContent{}
	_, err := resty.New().R().SetBody(req).Post("http://127.0.0.1:10000")
	if err != nil {
		panic(err)
	}
}
```

get `panic: unsupported 'Body' type/value`

**Comment by moorereason** [comment]
I've submitted a PR that should resolve this issue.
