### ISSUE TITLE
http2: response body closed

### ISSUE THREAD

**Issue by MrTreasure** [go-resty/resty#369]
when use ```resp.RawResponse.Body``` show me this err, but use http.Get is fine
```go
func DownloadFile(filename, url string) err {
	out, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer out.Close()
        // use http.Get() is fine
        // resp, err := http.Get(url)
	resp, err := resty.New().R().Get(url)
	if err != nil {
		return err
	}
	buffer := &bytes.Buffer{}
	_, err = io.Copy(out, io.TeeReader(resp.RawResponse.Body, buffer))
	if err != nil {
		return err // error: http2: response body closed
	}
} 
```
i just want to use this to show download progress

**Comment by jeevatkm** [comment]
@MrTreasure By default, Resty will read the body and parse it to struct if possible. If you want to take over the body read at your end. Tell resty via https://pkg.go.dev/github.com/go-resty/resty/v2?tab=doc#Request.SetDoNotParseResponse

**Comment by jeevatkm** [comment]
Thanks for the response, @MrTreasure
