### ISSUE TITLE
collect more http trace info like remote IP which is a import message

### ISSUE THREAD

**Issue by zhong-wx** [go-resty/resty#370]
to do that, we just add more field in TraceInfo struct
and remote IP can get from Request.clientTrace.ci.gotConnInfo.Conn.RemoteAddr()

**Comment by jeevatkm** [comment]
@zhong-wx Are you interested in sending in PR?

**Comment by zhong-wx** [comment]
I will send it.

**Comment by jeevatkm** [comment]
@zhong-wx I have added the remote address info, you can leave it.
