### ISSUE TITLE
Progress when uploading bit file

### ISSUE THREAD

**Issue by nandra** [go-resty/resty#379]
Hi,

I'm using multipart POST method to upload file to server. File is ~100M and it take some time when it is uploaded. Is there possibility to somehow show kind of progress when uploading? I checked library shortly but cannot spot anything like that. Many thanks.

**Comment by bhlin790** [comment]
+1

**Comment by jeevatkm** [comment]
Add callback for multipart progress if possible.

**Comment by zhangjinxu** [comment]
+1

**Comment by jeevatkm** [comment]
I recently added the multipart upload file streaming feature to Resty v3 development; it is currently available in the main branch.
Also, I have added a live progress callback for individual files uploaded as part of the multipart.
