### ISSUE TITLE
Default Authorization Key name change

### ISSUE THREAD

**Issue by felixd** [go-resty/resty#387]
Hello.

I am in need of changing default Authorization key name (**hdrAuthorizationKey** var) to **"X-Authorization"**

https://thingsboard.io/docs/reference/rest-api/

* client:go
https://github.com/go-resty/resty/blob/master/client.go#L56
https://github.com/go-resty/resty/blob/master/client.go#L92

* middleware.go
https://github.com/go-resty/resty/blob/master/middleware.go#L252

My proposition is to add new exported element in **Client** struct + exported method **SetAuthorizationKeyName**. middleware.go then should check if value is set and make proper changes. 

**Edit:** I have just found **OnBeforeRequest** method: https://github.com/go-resty/resty/blob/master/client.go#L359
I will use that to add header, but it still would be nice to have an option I have wrote about ;)

Cheers, Paweł.

**Comment by jeevatkm** [comment]
@felixd Thanks for reaching out. I understand what you mean. Let me think about a better way.

**Comment by jeevatkm** [comment]
@felixd After Resty v2.4.0 release, you could possibly do -

```go
var client = resty.New()
client.HeaderAuthorizationKey = "X-Authorization"
...
```
