### ISSUE TITLE
Don't set the transport's proxy settings to nil by default

### ISSUE THREAD

**Issue by neilotoole** [go-resty/resty#39]
In `client.go`, at this [location](https://github.com/go-resty/resty/blob/master/client.go#L631), there's this code:

```
	if req.proxyURL != nil {
		c.transport.Proxy = http.ProxyURL(req.proxyURL)
	} else if c.proxyURL != nil {
		c.transport.Proxy = http.ProxyURL(c.proxyURL)
	} else {
		c.transport.Proxy = nil
	}
```

The final `else` clause should be removed. If the caller provides a `transport`, it may already have a proxy configured, there's no reason to set the transport's proxy to `nil`.

**Comment by jeevatkm** [comment]
Make sense. Yes, we can leave that to caller.

Would you like to send PR?

**Comment by jeevatkm** [comment]
Taken care.
