### ISSUE TITLE
how to change 'Content-Type' when I call 'SetFormData'

### ISSUE THREAD

**Issue by Jexbat** [go-resty/resty#391]
Code:
``` go
headers := make(map[string]string)
headers["Authorization"] = getDigestAuthrization(digestParts)
headers["Content-Type"] = "application/x-www-form-urlencoded;charset=UTF-8"
resp, err = client.R().SetHeaders(headers).SetFormData(data).Put(URLHosts)
```

And `Content-Type` is still `application/x-www-form-urlencoded`. How to add `charset=UTF-8` in it?

**Comment by zhaogx** [comment]
it works.
`client.SetPreRequestHook(func(c *resty.Client, request *http.Request) error {
	if request.Method == http.MethodPut {
		request.Header.Set("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8")
	}
	return nil
})`

**Comment by radhikadentsu** [comment]
approve

**Comment by yjhmelody** [comment]
Are there any other methods to do it without hook or callback ?
I need to export these apis to more high level language, but I don't want to export these callback or hook apis.

**Comment by moorereason** [comment]
@jeevatkm, what do you think about the change below?  It should fix this issue by not overwriting an existing `Content-Type` header, but would you consider it a breaking change?

```diff
diff --git a/middleware.go b/middleware.go
index 50ff448..436d583 100644
--- a/middleware.go
+++ b/middleware.go
@@ -423,7 +423,9 @@ func handleFormData(c *Client, r *Request) {
        }

        r.bodyBuf = bytes.NewBuffer([]byte(formData.Encode()))
-       r.Header.Set(hdrContentTypeKey, formContentType)
+       if r.Header.Get(hdrContentTypeKey) == "" {
+               r.Header.Set(hdrContentTypeKey, formContentType)
+       }
        r.isFormData = true
 }

```

**Comment by jeevatkm** [comment]
@zhaogx @radhikadentsu Nice community collaboration, thank you.

@moorereason I like your suggestion. I think there is another approach we can do here. Basically, resty can define exported fields for appropriate constants so that Resty users can set it via `func init() { .... }` on their end. This enhancement will cover #387

**Comment by jeevatkm** [comment]
@Jexbat @moorereason I just did [bit of study](https://stackoverflow.com/questions/16819502/application-x-www-form-urlencoded-and-charset-utf-8) around this. It seems; better not to do any changes in the Resty. If needed Resty users could use PreRequestHook for customization.
