### ISSUE TITLE
Response.Result() lost fields in embedded struct

### ISSUE THREAD

**Issue by yx1989** [go-resty/resty#393]
```
type MetaResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type TestResponse struct {
	MetaResponse
	Data string `json:"data"`
}

resp, err := client.R().SetResult(TestResponse{}).Get(url)

result := resp.Result().(*TestResponse) // Code and Message are missing. Code is always 0, Message is always empty.

// But if use the following way there is no problem

result := &TestResponse{}
json.Unmarshal(resp.Body(), result)
```

**Comment by jeevatkm** [comment]
@yx1989 That's strange, typically `json.Unmarshal` function used internally. Could you share your JSON payload sample? I will try it out.

**Comment by yx1989** [comment]
the json payload like: 
{
  "code": 13,
  "message": "some error msg..",
  "details": [
  ]
}

**Comment by yx1989** [comment]
> @yx1989 That's strange, typically `json.Unmarshal` function used internally. Could you share your JSON payload sample? I will try it out.

**Comment by RiyaJohn** [comment]
@jeevatkm Even I have the same issue when status code is 400, but is it that by design result will be set only for status code > 199 and < 300?

**Comment by moorereason** [comment]
Use `SetError` to unmarshal error responses.

**Comment by jeevatkm** [comment]
@yx1989 @RiyaJohn You have to use `SetError` option as mentioned by @moorereason above. Since HTTP status code > 399, considered as Error then Resty uses Error reference for unmarshaling.

**Comment by bakatest-me** [comment]
@yx1989  my solution is set reference of error with `r.Result` 
P.S. im check r.Error because if my team want to manual use `.setError(...)` by themself
```go
r := resty.New().
		OnBeforeRequest(hookBeforeRequest)
...
func hookBeforeRequest(c *resty.Client, r *resty.Request) error {
	if r.Error == nil && r.Result != nil {
		r.SetError(r.Result)
	}
        return nil
}
```
