### ISSUE TITLE
`trace.dnsStart` will be zero if client was reused and transport got persistConn from idle queue

### ISSUE THREAD

**Issue by clannadxr** [go-resty/resty#396]
`clientTrace.dnsStart` and `clientTrace.dnsDone` will be set when `DNSStart`/ `DNSDone` or `ConnectStart` hook be called.

When `resty.Client` was reused and the transport delivered an already-idle connection, those hooks above won't be called thus leading to `clientTrace.dnsStart` and `clientTrace.dnsDone` be zero

**Comment by moorereason** [comment]
Isn't that by design since no new connection is established?  What would you expect them to be if not zero?  On a connection re-use scenario, several hooks are skipped (DNSStart, DNSDone, ConnectStart, ConnectDone, TLSHandshakeStart, & TLSHandshakeDone).

**Comment by clannadxr** [comment]
@moorereason sorry, the actual issue was `response.Time()` is calculated by `clientTrace.endTime.Sub(clientTrace.dnsStart)` when trace is enabled. So if when `dnsStart` is zero, `response.Time()` would be maximum duration.

**Comment by moorereason** [comment]
Are you using the latest resty?  This issue should be resolved in v2.4.0 (see #347).

**Comment by clannadxr** [comment]
@moorereason Oh sorry didn't check the latest codes. 

I noticed the v2.4.0 has not released yet, since it's a bug could you please merge it into v2.3.x and release a minor version if v2.4.0 is not ready for now

**Comment by moorereason** [comment]
My bad.  I forgot that v2.4.0 isn't released yet.

Cc: @jeevatkm

**Comment by git-hulk** [comment]
hi, @moorereason when the v2.4.0 would be released, we are suffering from this issue as well.

:) thanks

**Comment by jeevatkm** [comment]
@git-hulk @clannadxr I'm sorry will do the release in few days. 

@moorereason Thanks.

**Comment by jeevatkm** [comment]
@git-hulk @clannadxr v2.4.0 is released, can you try and let us know?

**Comment by git-hulk** [comment]
> @git-hulk @clannadxr v2.4.0 is released, can you try and let us know?

Thanks for your great work, I will try it out later.
