### ISSUE TITLE
RawResponse field in Response should be unexported 

### ISSUE THREAD

**Issue by whotakekajibu** [go-resty/resty#397]
I run the code snippet below ,there is a bug with error message  "http2: response body closed (Client.Timeout or context cancellation while reading body)" 

```
        response, err := GetClient().NewRequest().Get(url)
	if err != nil {
		logger.Errorf("cannot download image from url [%s],root cause [ %v]", url, err)
		return nil, err
	}
	config, ext, err := image.DecodeConfig(response.RawResponse.Body)
	if err != nil {
	       logger.Errorf("cannot decode image from url [%s],root cause [ %v]", url, err)
	       return nil, err
       }
```

`GetClient() ` is my teammate's func which  wrapped of resty。
after i debug a lot ,then i found this is the misuse of access the repose body, which means
`config, ext, err := image.DecodeConfig(response.RawResponse.Body)`
should be replaced by 
`config, ext, err := image.DecodeConfig(bytes.NewReader(response.Body()))`
although doc specify clearly [method ](https://github.com/go-resty/resty#features) one should  access the  reponse body `response.Body()`,
but the exported property of RawResponse always leads to misuse.

**Comment by jeevatkm** [comment]
@whotakekajibu Thanks for reaching out.  Technically, as a library, `RawResponse` should not be unexported. 

While reading your issue details, you're trying to access the response body and manipulating it. I think the following approach will improve performance.
```go
response, err := GetClient().NewRequest().SetDoNotParseResponse(true).Get(url)
if err != nil {
	logger.Errorf("cannot download image from url [%s],root cause [ %v]", url, err)
	return nil, err
}

responseBody = response.RawBody()
defer responseBody.Close()

config, ext, err := image.DecodeConfig(responseBody)
if err != nil {
	logger.Errorf("cannot decode image from url [%s],root cause [ %v]", url, err)
	return nil, err
}
```

Refer to Resty godoc for further reading.
