### ISSUE TITLE
resty not support  GoLand IDE Debug Mode

### ISSUE THREAD

**Issue by mrwenhui** [go-resty/resty#399]
when I debug resty application in goland IDE on Ubuntu 20.04,  always  response   500 Inner server Error.
IF  i  run the resty application  in command line,  it works fine.

**Comment by jeevatkm** [comment]
@mrwenhui I'm sorry, I could understand it. Could you please provide further details and examples to replicate the issue you're describing?

**Comment by mrwenhui** [comment]
I means   you can use resty  Post  Way to  request a restful api  like register user, login, or something else  with goland IDE debug step by step  mod,   the bug will always  show.   if you just run the request in command mod, it works fine.   It is difficult to show a server  and request here.

**Comment by mrwenhui** [comment]
mod  is mode.

**Comment by vijayrajah** [comment]
@mrwenhui I also use Goland IDE (from jetbrains), I do not have this issue..

**Comment by jeevatkm** [comment]
@vijayrajah Thanks.

@mrwenhui I do not know how to reproduce it. Plus library does not have anything specific to any IDE.

**Comment by mrwenhui** [comment]
Still have this issue. Thanks for your effort.  If anyone eles dont have this issue , I can close it.
