### ISSUE TITLE
Add custom timeout per client basis + FastHTTP support

### ISSUE THREAD

**Issue by kryptodev** [go-resty/resty#40]
So I'm looking for something like

``` go
myresty := resty.New()
req, err := myresty.R().
            SetHeader("User-Agent", UserAgent).
            SetProxy(proxyUrl).
            SetTimeout(duration)
            Get(link)
```

Also wanted to ask if it's possible to use fasthttp instead of net/http. From what I read it is significantly more performant:

Refer: https://medium.com/@valyala/net-http-client-has-the-following-additional-limitations-318ac870ce9d#.502tduhmn

Refer: https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779#.pla7aw7gz

Thanks!

**Comment by kryptodev** [comment]
Oh figured out the first part of my question. Do consider the fasthttp suggestion. Thank you again.

**Comment by jeevatkm** [comment]
Thanks you found a way. I will see about fasthttp.

**Comment by jeevatkm** [comment]
I'm closing this one, for now not adding fasthttp support.
