### ISSUE TITLE
Save response to file by custom middleware

### ISSUE THREAD

**Issue by pfdtk** [go-resty/resty#400]
https://github.com/go-resty/resty/blob/0de0d7e3240b249466241b87947fcdc87c543909/client.go#L842

I try to save the response to file by my custom middleware registered by `OnAfterResponse`, but the option `isSaveResponse` is default to false because i dont use the default middleware `saveResponseIntoFile`, so the response will auto download and set to `response.body` before my custom middleware can handle the response to file.

So, it there any way to save the response to file by custom middleware?

**Comment by jeevatkm** [comment]
@pfdtk If you want to save the file as part of your custom response middleware then please do not use the `SetOutput` option.

**Comment by jeevatkm** [comment]
I'm closing it.
