### ISSUE TITLE
SetRetryCount allows negative values that Backoff doesn't properly handle

### ISSUE THREAD

**Issue by moorereason** [go-resty/resty#404]
`SetRetryCount` allows values less than zero, but the [`Backoff` implementation assumes `opts.maxRetries` is zero or greater](https://github.com/go-resty/resty/blob/b90c855d687abc2b9efef0e936ea5462836954a1/retry.go#L92).  The result is that `Backoff` doesn't actually make a request but also doesn't return an error.

Two options for a solution:

1. Convert negative values to zero in `SetRetryCount`.
2. Convert a negative value into `math.MaxInt64` (retry forever) in `SetRetryCount`.

In either case, `Backoff` should be updated to return an error if `opts.maxRetries` is less than zero.

Related to #392

**Comment by moorereason** [comment]
@yjhmelody commented [here](https://github.com/go-resty/resty/pull/392#issuecomment-758527480) that option 2 (retry forever) is preferred.

I tend to agree.  Normally, a `-1` in this scenario means "no limit."

**Comment by jeevatkm** [comment]
@moorereason @yjhmelody Just wondering, the forever retry option is good or bad for the client library since it will result in DoS behavior on targeted application/service.

**Comment by jeevatkm** [comment]
Prevent -1 usage with error message

**Comment by jeevatkm** [comment]
The negative value is converted to zero for RetryCount as part of PR #894
