### ISSUE TITLE
The long connection function is currently not supported.

### ISSUE THREAD

**Issue by mmzhi** [go-resty/resty#405]
https://github.com/go-resty/resty/blob/61f4307870842f056ac439c0d627a9611846de02/client.go#L899

Currently, long connections are used to continuously obtain data, and HTTP will not be disconnected during this process. Since all data will be read here, it will cause the link to be blocked here, and we hope that developers will support the long connection function .

**Comment by jeevatkm** [comment]
@mmzhi Can you please explain what do you mean by the long connection function?

**Comment by mmzhi** [comment]
Sorry my bad English. It user google translate.
The client connects to the server through the HTTP protocol. After a successful connection, neither the server nor the client will disconnect, and will continue to transmit data, similar to the MQTT protocol.

**Comment by jeevatkm** [comment]
@mmzhi I'm not sure this long connection is possible with HTTP protocol. Typically, these long connections use direct TCP/UDP protocol to communicate.
