### ISSUE TITLE
example of  automatic unmarshalling?

### ISSUE THREAD

**Issue by miqui** [go-resty/resty#41]
example of  automatic unmarshalling?

**Comment by jeevatkm** [comment]
@miqui Please have a look [resty_test.go](https://github.com/go-resty/resty/blob/master/resty_test.go). You will find more examples.

Automatic marshaling & unmarshalling example:
1. https://github.com/go-resty/resty/blob/master/resty_test.go#L196
2. https://github.com/go-resty/resty/blob/master/resty_test.go#L239
3. https://github.com/go-resty/resty/blob/master/resty_test.go#L331

**Comment by miqui** [comment]
@jeevatkm , thanks for the reply, 

i am doing this:

```
res, err := resty.R().Get(....);

 var a  MyStruct
 json.Unmarshal(res.Body(),&a)
```

so that i can then inspect the a struct properties, ... i was not sure what you meant by "automatic" unmarshalling...

**Comment by jeevatkm** [comment]
You no need to call ` json.Unmarshal` manually. resty does it for you automatically based content type JSON or XML otherwise resty won't do any. Will keep your response body intact.

you might have saw the example, I gave you.

```go
var a  MyStruct
res, err := resty.R().SetResult(&a).Get(....)

// just print it, you will see your values
fmt.Printf("\n%#v\n", res.Result().(*MyStruct))
```

**Comment by miqui** [comment]
cool, let me try that...

**Comment by jeevatkm** [comment]
I'm glad to hear that. Thanks.

**Comment by sgon00** [comment]
Now 2019, the example code above should put in README.md. Without this issue and the code, I have no ideas what to do.
