### ISSUE TITLE
resty support for no_proxy

### ISSUE THREAD

**Issue by uvindra** [go-resty/resty#411]
resty currently supports setting proxies via `client.SetProxy()`, allowing it to work with values defined in HTTP_PROXY and HTTPS_PROXY env variables.

Is there any functionality that would allow bypassing hosts defined in no_proxy/NO_PROXY env variables from the resty proxy settings?

**Comment by moorereason** [comment]
Unless you create your own `http.Transport`, by default resty uses the `http.ProxyFromEnvironment` method from the stdlib, which looks to the env for proxy info.  Resty's `client.SetProxy` uses `http.ProxyURL`, which bypasses the env lookups.

**Comment by uvindra** [comment]
Ack @moorereason  thanks for the clarification. Tested and it does work as specified
