### ISSUE TITLE
SetRetryMaxWaitTime with negative number + RetryAfter callback doesn't work reliably (due to 32bit/64bit integer conflict)

### ISSUE THREAD

**Issue by jameshoulahan** [go-resty/resty#412]
`(*Client) SetRetryMaxWaitTime(time.Duration(-1))` should work, as shown in `retry_test.go`.

However, it seems to fail due to 32bit max integer value when used in collaboration with `(*Client) SetRetryAfter` due to the implementation of `func sleepDuration(...)` (in `retry.go`).

See my annotations here for an example when attempting to set max to -1 while the retry-after callback returns 5s:

```
func sleepDuration(resp *Response, min, max time.Duration, attempt int) (time.Duration, error) {
	// max == -1 

	const maxInt = 1<<31 - 1 // max int for arch 386

	if max < 0 {
		max = maxInt
	}

	// max == 2147483647

...

	// 1. Check for custom callback
	if retryAfterFunc := resp.Request.client.RetryAfter; retryAfterFunc != nil {
		result, err := retryAfterFunc(resp.Request.client, resp)
		if err != nil {
			return 0, err // i.e. 'API quota exceeded'
		}

		// result == 5000000000, supposing our callback returns 5 seconds

...

		if result < 0 || max < result {
			result = max // result is now max == 2147483647
		}

...
}
```

as you can see, due to the conflict between `maxInt` (max int32) and `result` (int64), the value of `maxInt` is preferred, even though the idea is that we want it to be a true "max int".

**Comment by jeevatkm** [comment]
@jameshoulahan There is an update that happened in the retry sleep duration method. do you mind trying the branch master?  if the issue persists can you provide a test case.

**Comment by jeevatkm** [comment]
@jameshoulahan Any update from your end?

**Comment by jameshoulahan** [comment]
No updates, sorry. Didn't get around to pursuing this issue any further.
