### ISSUE TITLE
Proposal: OnRetry hook

### ISSUE THREAD

**Issue by Blokje5** [go-resty/resty#416]
Currently the Retry interface of the Resty client supports a custom condition for when to retry and a custom callback to calculate the time between retries. What I am currently missing is an `OnRetry` hook to execute side effecting operations whenever a request is retried.

For example, I have a use case where I want to authenticate with an API after an access token has expired. One potential way to solve that with `resty` would be to authenticate with the API if the request returned a 403. While it is currently possible to achieve this with the `resty.Backoff`, it would be much cleaner to have an `OnRetry` hook.

**Comment by jeevatkm** [comment]
@Blokje5 Thanks for your proposal. I agree it will be a helpful feature for Resty users.
