### ISSUE TITLE
Implement easier adding of multi-value http headers

### ISSUE THREAD

**Issue by DazKins** [go-resty/resty#432]
There are currently 2 `SetHeaders` functions with the following types:

```
func(headers map[string]string) *resty.Request
func(header string, value string) *resty.Request
```

It might be convenient to add a 3rd:

```
func(headers map[string][]string) *resty.Request
```

As listed in RFC2616 HTTP headers can have multiple values: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

This would also be convenient as the inbuilt golang `http.Header` type is defined as `map[string][]string` so would allow for direct usage of that type:

```golang
headers := http.Header{}
restyClient.R().SetHeaders(headers)
```

**Comment by mhdiiilham** [comment]
Hey @DazKins is anyone already working on this? If not, I'd be glad if you assign this to me

**Comment by DazKins** [comment]
> Hey @DazKins is anyone already working on this? If not, I'd be glad if you assign this to me

Hey, I don't have permission to assign, but no I don't believe anyone is working on this
