### ISSUE TITLE
[not an issue] THANK YOU

### ISSUE THREAD

**Issue by wsw70** [go-resty/resty#437]
Sorry if I use the Issues for this message but I have to say

**THANK.YOU.**

For someone new to Golang and coming from a (mostly) Python background, `go-resty` brings sanity to the HTTS calls. This is truly a life saver.

I will close this "Issue" in a few days, after I made sure the world has seen it :)

Thanks again.

**Comment by kishaningithub** [comment]
@jeevatkm Can you enabled discussions in this repo? I think others can add their testimonials as well there :-) 

And can be a place for general Q and A as well

**Comment by wsw70** [comment]
OK, I think enough people have seen this.
The discussion suggestion by @jeevatkm is a great one
