### ISSUE TITLE
modularize accept and content-type as middleware functions

### ISSUE THREAD

**Issue by chb0github** [go-resty/resty#439]
Right now there is no way to set a custom accept/content-type - you can set the header, but you can't actually manipulate the data. This means that resty has no way to handle anything that isn't

1. `JSON`-ish
2. text
3. Sniffed mime

Ideally, something like 
```go
resty.New().R().addContentTypeHandler("application/vnd.json+api", func (reader io.Reader) interface{}{
 // marshal to json or whatever here
})
```
The current code could be migrated to a map of accept/content handlers

Here is the relevant code currently in use:

```go
func DetectContentType(body interface{}) string {
	contentType := plainTextType
	kind := kindOf(body)
	switch kind {
	case reflect.Struct, reflect.Map:
		contentType = jsonContentType
	case reflect.String:
		contentType = plainTextType
	default:
		if b, ok := body.([]byte); ok {
			contentType = http.DetectContentType(b)
		} else if kind == reflect.Slice {
			contentType = jsonContentType
		}
	}

	return contentType
}
```

**Comment by jeevatkm** [comment]
@chb0github Thanks for reaching out.
Just to clarify, the above suggestion is for Request or Response?

**Comment by chb0github** [comment]
Both, actually. So can set the accept and content type handlers. And, as it's a list, i suggest the verb "AddContentTypeHandler" (and AddAccept...)

Then, reimplement the current code to follow this paradigm.

I'm willing to commit time and implement it if it's an agreed upon design

**Comment by jeevatkm** [comment]
@chb0github Got it. I'm sorry for the above-delayed response. I need to think about it, I will get back to you.

**Comment by chb0github** [comment]
I could have handily used this when marshalling form encoded data. The current code didn't like that

**Comment by jeevatkm** [comment]
@chb0github I surely understand your suggestion. I'm glad to hear about your commitment too. Just I need time to think about it without introducing a breaking change.
