### ISSUE TITLE
Form request processing speed is too slow 

### ISSUE THREAD

**Issue by xbabybus** [go-resty/resty#445]
POST request is too slow, I tested the original Post Form request and RESTY POST FORM request, the same URL wants query string, all 5S test duration, the original can request 780 in the specified time, average 156 / s And RESTY can only request about 180 or more in the same time, with average 36 / s, I hope to optimize the request processing speed.

**Comment by jeevatkm** [comment]
@WSZ9527 Thanks for reaching out. 
Typically, the term "speed" is a variable factor based on consumer use cases and data.

It will be helpful for analyzes/investgation; if could provide the test cases to showcase your use case and exact sample data.
