### ISSUE TITLE
resty parse Set-Cookie header incorrectly

### ISSUE THREAD

**Issue by codenoid** [go-resty/resty#466]
![Screenshot from 2021-09-24 12-35-56](https://user-images.githubusercontent.com/14269809/134623607-5e8ed9f1-0d79-4ab9-b6fd-03d5a1a21c94.png)

http.Cookie from parsed resty are only contains `name` and `value`

**Comment by jeevatkm** [comment]
@codenoid FYI, Resty does not process Cookie from the response; it returns as-is from the actual response object. 
https://github.com/go-resty/resty/blob/3face0dac0f7fb765bf637f51f1f5343b3c7a235/response.go#L91
