### ISSUE TITLE
[QUESTION] Logging in retry

### ISSUE THREAD

**Issue by bynov** [go-resty/resty#469]
Hi!
My goresty client configuration:
```
resty.NewWithClient(&http.Client{
			Timeout: httpTimeout,
		}).SetHostURL("<host>").
			SetRetryCount(3).
			SetRetryMaxWaitTime(time.Second * 60).
			SetRetryWaitTime(time.Second * 60).
			AddRetryCondition(func(r *resty.Response, err error) bool {
				return r.StatusCode() == http.StatusTooManyRequests
			}),
```
I have response from API with 409 status code, so retry condition is not work. But response is logged to console. I there any way to disable logging?

Response:
```
ERROR RESTY API error: already exists, Attempt 1
```

**Comment by josegonzalez** [comment]
I have a test case here:

```
client := resty.New()
client.SetRetryCount(2)
client.SetTimeout(3 * time.Second)
resp, err := client.R().
	Get("http://172.17.0.255:5000/")
```

This assumes there is something listening at that ip/port. I get an error message printed out, regardless of what the actual error is (in my case, its that I'm hitting a timeout).

I'd like to have no error messages at all if possible, and just get the error back from `err`.

**Comment by jeevatkm** [comment]
I will work on logging improvement in v3.0.0 because it could be breaking behavioral change.
