### ISSUE TITLE
Enable proper retrying of POST requests

### ISSUE THREAD

**Issue by drichelson** [go-resty/resty#47]
It looks like retries on POST requests do not resend the request body. Some would suggest that POSTs should not be retried, but in my case the request is idempotent, so it's fine. It should be noted that the log indicates the retried attempt contains the post body, but it's not actually there.

**Comment by jeevatkm** [comment]
@drichelson Thanks for reporting, I will have a look. If you have a sample code, please post it here.

**Comment by drichelson** [comment]
I created a failing test (with some heavy logging) to illustrate this issue: https://github.com/go-resty/resty/pull/48/files

**Comment by jeevatkm** [comment]
Thanks for the PR. I will have a look.

**Comment by drichelson** [comment]
Thanks @jeevatkm !

**Comment by jeevatkm** [comment]
@drichelson You're welcome.
