### ISSUE TITLE
Goroutines are not being closed - memory leaks

### ISSUE THREAD

**Issue by kotyara85** [go-resty/resty#482]
Hello,
Running this simple code

```
func main() {
	i := 0
	for i < 10 {
		fmt.Println(runtime.NumGoroutine())
		time.Sleep(1 * time.Second)
		// Create a Resty Client
		client := resty.New()
		resp, err := client.R().
			EnableTrace().
			Get("http://localhost:8080")
		if err != nil {
			return
		}
		if resp.StatusCode() != http.StatusOK {
			return
		}
		i++
	}

	time.Sleep(5 * time.Second)
	fmt.Println(runtime.NumGoroutine())
}
```

```
$ go run main.go
1
3
5
7
9
11
13
15
17
19
21
```

and seeing that goroutines are increasing.
Is there any way to termintae idle connections somehow? This results into memory leaks.
Thanks

**Comment by wcig** [comment]
> 

how did you solve this problem, not create client every time but use one client?

**Comment by pengjun1128** [comment]
why?

**Comment by wcig** [comment]
We don't need to create a new *resty.Client every time, but should reuse the *resty.Client, this is my test:

`func main() {
	i := 0
	client := resty.New()
	fmt.Println("start goroutine num:", runtime.NumGoroutine())
	for i < 10 {
		fmt.Println("goroutine num:", runtime.NumGoroutine())
		time.Sleep(1 * time.Second)
		resp, err := client.R().
			EnableTrace().
			Get("http://localhost:80")
		if err != nil {
			return
		}
		if resp.StatusCode() != http.StatusOK {
			return
		}
		i++
	}
	time.Sleep(5 * time.Second)
	fmt.Println("end goroutine num:", runtime.NumGoroutine())

	// Output:
	// start goroutine num: 1
	// goroutine num: 1
	// goroutine num: 3
	// goroutine num: 3
	// goroutine num: 3
	// goroutine num: 3
	// goroutine num: 3
	// goroutine num: 3
	// goroutine num: 3
	// goroutine num: 3
	// goroutine num: 3
	// end goroutine num: 3
}`
