### ISSUE TITLE
Form Data Does Not Allow Multi-Valued Parameters

### ISSUE THREAD

**Issue by AlskiOnTheWeb** [go-resty/resty#49]
SetFormData currently only accepts map[string]string but the HTTP form data really supports a model of map[string][]string (a map of string to list-of-strings).

**Comment by jeevatkm** [comment]
Please use method `SetMultiValueFormData`.

**Comment by jeevatkm** [comment]
does it solve your need?

**Comment by jeevatkm** [comment]
I'm closing it. Please let me know.

**Comment by gungdr** [comment]
hi @jeevatkm 
is it possible do Post request like this? 
```go
SetFormData(...).
SetFormDataFromValues(...).
Post("")
```
