### ISSUE TITLE
Issue while uploading csv file

### ISSUE THREAD

**Issue by KshitijGugale** [go-resty/resty#490]
Hi Team,

I am facing one weird issue while uploading a csv file. When there are 3 lines in csv file then SetFile() works perfectly but when I add 4th line in csv i am getting an error as "Invalid file type or fie is empty"

Sample code:
res, err := client.R().SetFile("file", "abc.csv").Post("<my_url>")

Any suggestion would be much appreciated.

**Comment by jeevatkm** [comment]
@KshitijGugale Typically, SetFile does not care about file content but processes it. Maybe something needs to be corrected at your end. So I'm sorry, I cannot help with user/development issues.
