### ISSUE TITLE
Big file as request body

### ISSUE THREAD

**Issue by Myriad-Dreamin** [go-resty/resty#495]
I'm uploading a file as request body with size of 4GB and found that resty [copies full file content into memory](https://github.com/go-resty/resty/blob/master/middleware.go#L521) (to handle `http.Request.GetBody` callback?). However, it is not necessary because `net/http.Client` only views the body as an `io.ReadCloser`.

https://github.com/go-resty/resty/blob/7dda6159eceee10c6cacc6f9d1637042f67423b0/middleware.go#L521-L543

After reading [closed issue](https://github.com/go-resty/resty/issues/133) and full code of resty, no api can help me avoid the http client reading all file content. It is expected that resty can expose a stream-like api or handle a cloneable reader implicitly to get request retrying functionality.

```go
    client.R().SetClonableBody(reqBody.Reader)
```

or

```go
    sink, err := detectBodyCloner(r) // replace getBodyCopy
    if err != nil && err != ErrBodyIsNotCloneable {
        return err
    }

    var bodyIsNotCloneable = err == ErrBodyIsNotCloneable

    // assign get body func for the underlying raw request instance
    r.RawRequest.GetBody = func() (io.ReadCloser, error) {
        if sink != nil {
            cReader := sink.Clone()
            if reader, ok := cReader.(io.Reader); ok {
                return ioutil.NopCloser(reader), nil
            }
            if reader, ok := cReader.(io.ReadCloser); ok {
                return reader, nil
            }
            return nil, ErrBodyIsNotStream
        }
        if bodyIsNotCloneable {
            return nil, ErrBodyIsNotCloneable
        }
        return nil, nil
    }
```

The second approach is better in the case of `net/http.Client` never calling `GetBody` callback

**Comment by kklinan** [comment]
I need it, too

**Comment by florentgluck** [comment]
I need the ability to upload files of many GB, thus a stream-like implementation is mandatory.
@kklinan could you please post your fix here?
Thanks!

**Comment by gospider007** [comment]
this can help you: https://github.com/gospider007/requests/blob/master/test/request/file_test.go

**Comment by pcfreak30** [comment]
I have just run into this and will have to jump libraries—a bit of a shame. Trying to copy an `io.Reader` into memory vs streaming is a _really_ bad assumption. 

I looked, and I think both https://github.com/monaco-io/request and https://github.com/imroc/req handle this correctly.

**Comment by jeevatkm** [comment]
Done, refer to PR.

**Comment by jeevatkm** [comment]
@thxbb12 Thanks. I have added this feature as part of the upcoming Resty v3.

**Comment by thxbb12** [comment]
Thanks @jeevatkm. I was hoping it would be available in the next 2.15.x release.
Any ETA as to when Resty v3 will be released?

**Comment by jeevatkm** [comment]
@thxbb12 Resty v3 will take time (possibly around the new year). It will have more features and options than v2 and be more efficient. Is this okay for your timeline?

**Comment by thxbb12** [comment]
Yes, that's fine. I cannot really complain as I'm not the one working on it myself (although I wish I had enough time to contribute).
Thanks for your great work!

**Comment by jeevatkm** [comment]
Thank you @thxbb12. You can watch [v3 progress here](https://github.com/go-resty/resty/milestone/34).

I will be heading to work in a while before leaving. I saw your comment. Good chat.
