### ISSUE TITLE
Cancelling Requests in Middleware

### ISSUE THREAD

**Issue by npalladium** [go-resty/resty#498]
Is there anyway to cancel the request in Middleware?
My use-case is printing the `curl` command for the request and exiting if a `--dry-run` flag is set.

PS. Amazing utility! ❤️

**Comment by kecci** [comment]
I think you could set conditions on the use case / outbound layer, before it's going to the resty client.
Or do you have any example codes ?

**Comment by jeevatkm** [comment]
@npalladium You could add middleware and return an error to halt the request, and you could do the same in the `PreRequestHook` too.
