### ISSUE TITLE
Some questions about retrying

### ISSUE THREAD

**Issue by mingzaily** [go-resty/resty#499]
First of all, thank the author for providing such an excellent plug-in.
But how do I set it so that one of the parameters can be replaced when retrying？

```golang
_, err = m.wx.Resty.R().
  SetQueryParam("access_token", m.wx.GetAccessToken()).
  SetHeader("Content-Type", "application/json; charset=UTF-8").
  SetBody(body).
  SetResult(&response).
  SetError(&response).
  AddRetryCondition(func(response *resty.Response, err error) bool {
	  if response.StatusCode() != http.StatusForbidden {
		  return true
	  }
	  return false
  }).
  Post(m.path)
```

My retry condition means that I will retry when the access_token expires, but I should replace the token with a new valid token. What should I do?

**Comment by kecci** [comment]
I think the retry on resty is isolated for one request. It's to handle with same request, but expected next success response.

So I suggest these options:

Option 1:
- First, check the access token first, if expired, renew one.
- Then, after new valid token, call with resty client.

Option 2: (You can use while conditions also)
- First, call with resty client.
- Then, if expired returns to err specific for token expired. 
- If token expired, generate new valid token, then call with resty client.

I hope this could help more your discussion.

**Comment by jeevatkm** [comment]
@mingzaily, I hope @kecci's comment provided you with direction and insight. Thanks for your compliments.
