### ISSUE TITLE
How to use http2 in resty

### ISSUE THREAD

**Issue by culionbear** [go-resty/resty#505]
how to use http2.0 in resty?
go version : 1.15

**Comment by moorereason** [comment]
HTTP/2 works out of the box with Go 1.16+.  Prior to that you need to [use a custom transport](https://pkg.go.dev/github.com/go-resty/resty/v2#Client.SetTransport) from [`golang.org/x/net/http2`](https://pkg.go.dev/golang.org/x/net/http2).

**Comment by josegonzalez** [comment]
I'm not able to force an HTTP/2 connection with go-resty on go 1.19.4. Here is a snippet of code:

```go
	client := resty.New()
	client.SetDebug(true)
	_, err := client.R().
		SetQueryParams(map[string]string{
			"q":    config.Tag,
			"type": "link",
			"sort": "updated",
		}).
		SetHeaders(map[string]string{
			"user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
		}).
		Get("https://www.reddit.com/search.json")
```

And the headers:

```
2023/01/08 18:33:57.116547 DEBUG RESTY
==============================================================================
~~~ REQUEST ~~~
GET  /search.json?q=dokku&sort=updated&type=link  HTTP/1.1
HOST   : www.reddit.com
HEADERS:
	User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
```

Curl seems to default to negotiating an http 2 connection by default. Not sure if there is a way to do that with go-resty.

**Comment by jeevatkm** [comment]
@culionbear As @moorereason already provided the info above. Golang http client negotiates the HTTP/2 of server supports; otherwise, it falls back to HTTP/1.1; Resty is built on top of the go http client.
