### ISSUE TITLE
How do I get all my cookies?

### ISSUE THREAD

**Issue by Esword618** [go-resty/resty#506]
How do I get all my cookies?

This is my code.
`
	client := resty.New()

	client.SetHeader("user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36")

	res, err := client.R().Get("https://www.icourse163.org/logonByQRCode/code.do?width=182&height=182")

	if err != nil {
		panic(err)
	}

	fmt.Println(res.String())

	fmt.Println(res.Cookies())

	fmt.Println(client.Cookies)

	s := "icourse163.org"

	u, _ := url.Parse(s)

	fmt.Println(client.GetClient().Jar.Cookies(u))
`
fmt.Println(client.GetClient().Jar.Cookies(u))
I can't get a cookie at all

What should I do？Please answer, thank you very much!
My English is limited, please understand if there are mistakes

**Comment by jeevatkm** [comment]
These two articles provide a good insight into Cookie and its usage.

https://golangbyexample.com/read-cookie-http-golang/
https://www.alexedwards.net/blog/working-with-cookies-in-go
