### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Esword618** [go-resty/resty#508]
I found a bug, the request response header says csp is not safe, I checked a lot of information can not get the answer, so I came to you to see if you know, to get the solution.

This is the message from that response.
`
Content-Security-Policy:[upgrade-insecure-requests]
`

**Comment by moorereason** [comment]
Can you provide the full headers for the request?

**Comment by Esword618** [comment]
This is my request head.
`
map[string]string{
		"Accept":          "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
		"user-agent":      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
		"Accept-Encoding": "gzip, deflate, br",
	}
`

**Comment by moorereason** [comment]
Makes requests to that host with HTTPS.  If you're already doing that, then I don't understand what the problem is.
