### ISSUE TITLE
Can resty client auto close tcp connection when client request many times on one connection with keep-alive mode.

### ISSUE THREAD

**Issue by ldnvnbl** [go-resty/resty#509]
I use resty client access k8s service with http keep-alive, but the load is not balance. if I SetCloseConnection as true, the performance will be low.

so can i close the connection after request many times, like 1000 this value can be set.

**Comment by libaochuan90** [comment]
I have encountered the same problem. Have you solved this problem @ldnvnbl

**Comment by jeevatkm** [comment]
@ldnvnbl @libaochuan90 The Golang http package manages the HTTP client connections. Resty does not manage connections explicitly.
