### ISSUE TITLE
Is there a way to maintain header order?

### ISSUE THREAD

**Issue by jj0e** [go-resty/resty#510]
Hello, 

I really like Resty, but I noticed the order of my headers are not always preserved. Is there a way to make it so the order is what I specify? It is important for my use-case because the request will fail if the order is wrong.

**Comment by moorereason** [comment]
AFAIK, it's not possible with the Go `http` package, which is what Resty is built upon.  See https://github.com/golang/go/issues/24375 for more details.

**Comment by chb0github** [comment]
@jj0e - for the record, that is not at all part of the http spec.
