### ISSUE TITLE
4 advice to resty

### ISSUE THREAD

**Issue by Nyx2022** [go-resty/resty#514]
i used resty for long time,but found 2 features or bugs need to be implemented

i hope resty will supprt concurrent safe
i hope resty can handle special encoding,like this photo

https://user-images.githubusercontent.com/51039208/149131272-60f94022-6fa7-4a3e-b699-775974854b47.png

sometimes i actually need some special encoding，but resty can't deal with it
resty.Request can set proxy，now only resty.Client can set proxy,i hope resty.request can support it too
more easy way to set redirect policy,i think the way now to set redirect policy is a little difficultto call

**Comment by chb0github** [comment]
Generally, I think resty needs a better middleware model with sensible, but overridable or augmentable defaults. Then you can actually install middleware that can do the encoding correctly

**Comment by jeevatkm** [comment]
@Nyx2022 @chb0github improved middleware model is coming up in the v3.

@Nyx2022 resty is concurrent safe. Did you mean modify the client settings from multiple goroutine?

**Comment by jeevatkm** [comment]
@Nyx2022 In golang, the proxy is a property of the client's Transport, not the request.

**Comment by gospider007** [comment]
> 我使用 resty 很长时间了，但发现有 2 个功能或错误需要实现
> 
> 我希望 Resty 能够支持并发安全，我希望 Resty 可以处理特殊的编码，就像这张照片一样
> 
> https://user-images.githubusercontent.com/51039208/149131272-60f94022-6fa7-4a3e-b699-775974854b47.png
> 
> 有时我实际上需要一些特殊的编码，但 Resty 无法处理它。请求可以设置代理，现在只有resty。客户端可以设置代理，希望resty.request能支持它更简单的方式设置重定向策略，我觉得现在设置重定向策略的方式有点难调用

this can help you : https://github.com/gospider007/requests/blob/master/test/proxy_test.go

**Comment by gospider007** [comment]
> 我使用 resty 很长时间了，但发现有 2 个功能或错误需要实现
> 
> 我希望 Resty 能够支持并发安全，我希望 Resty 可以处理特殊的编码，就像这张照片一样
> 
> https://user-images.githubusercontent.com/51039208/149131272-60f94022-6fa7-4a3e-b699-775974854b47.png
> 
> 有时我实际上需要一些特殊的编码，但 Resty 无法处理它。请求可以设置代理，现在只有resty。客户端可以设置代理，希望resty.request能支持它更简单的方式设置重定向策略，我觉得现在设置重定向策略的方式有点难调用

this can help you:
```go
package main

import (
	"log"

	"github.com/gospider007/requests"
)

func main() {
	session, _ := requests.NewClient(nil)
	resp, err := session.Get(nil, "https://httpbin.org/anything", requests.RequestOption{
		Proxy: "", //set proxy,ex:"http://127.0.0.1:8080","https://127.0.0.1:8080","socks5://127.0.0.1:8080"
	})
	if err != nil {
		log.Panic(err)
	}
	if resp.StatusCode() != 200 {
		log.Panic("status code is not 200")
	}
}
```

**Comment by gospider007** [comment]
> Transport

Transport supports a separate agent for requesting requests, but it is more complicated

**Comment by jeevatkm** [comment]
@Nyx2022 @chb0github In the Reasty v3 development, I have added the ContentTypeDecoder feature so users can easily add their custom response parsing logic to parse Result Object. The development version is available in the `main` branch. 

Also, the client instance comes with a mutex to make all client setting manipulation concurrent-safe.

You could share feedback. 
Note: I do not have v3 documentation ready, so please follow the godoc, code, and test cases.

**Comment by chb0github** [comment]
To be clear, @jeevatkm - It's for send/receive of objects. 

Content-Type: Client posts to server
Accept: Client will accept content of type(s)

Hence, the 
string -> string[] because you offer the server options for how to respond.

**Comment by jeevatkm** [comment]
@chb0github Yes, in the Resty v3, I have added 
https://github.com/go-resty/resty/blob/0d0bc1b1d873414d17ca6fb4e5240165672dd022/stream.go#L22-L26

Act based on content type on request and response.

You could review and share your input. v3 is in development I have opportunities to improve it.
