### ISSUE TITLE
RawRequest is nil in BeforeOnRequest method

### ISSUE THREAD

**Issue by belek** [go-resty/resty#517]
My goal is to store body from request to particular URLs.
To do that I implemented OnBeforeRequest interceptor where I am trying to use httputil.DumpRequest to get the body and then save it to DB. But I can't use request.RawRequest because it's nil. Also I enabled debug mode in client.

```
func (irc *RestyResponseInterceptorNomad) OnBeforeRequest(rc *resty.Client, req *resty.Request) error {
	fmt.Println("*** Is debug? ", rc.Debug)
	fmt.Println("*** Raw request: ", req.RawRequest)
	reqDump, err := httputil.DumpRequest(req.RawRequest, true)
	if err != nil {
		logrus.WithError(err).Error("failed to dump request in onAfterResponse method")
		return nil
	}

        .....
        .....
        .....
	return err
}
```
Output is:

```
*** Is debug?  true
*** Raw request:  <nil>
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
```
Why RawRequest is nil and what should I do to make it work well?

**Comment by 0140454** [comment]
Just share what I found.

There are three types of request middleware, and they are performed in sequence:
1. `udBeforeRequest` chain (registered by `Client.onBeforeRequest`)
2. `beforeRequest` chain (default middleware registered by resty)
3. `preReqHook` hook (registered by `Client.SetPreRequestHook`)

`req.RawRequest` is initialized at the second chain. Therefore, we will get a `nil` in our `onBeforeRequest` function.

To access a valid `Http.Request` instance, we need to register hook via `Client.SetPreRequestHook`.

See also https://github.com/go-resty/resty/blob/master/client.go#L899-L923

**Comment by x-EricH-x** [comment]
@0140454  great thanks, just faced the exactly the same issue : D

**Comment by jeevatkm** [comment]
@belek Please use the SetPreRequestHook. @0140454 mentioned the correct execution sequence.
