### ISSUE TITLE
How can I delete a cookie which is set using SetCookie

### ISSUE THREAD

**Issue by astha2098** [go-resty/resty#518]
How can I delete a cookie which is set using SetCookie (CookieJar is not used). I would like to delete that single cookie and not all the cookies.

**Comment by jeevatkm** [comment]
@astha2098 I'm not sure I understand your question. Can you explain it with an example program?

**Comment by zhujintao** [comment]
cookie is created by  http.Client `makeHeadersCopier` cannot be deleted, you can initialize a new client:
`
client=resty.New().SetBaseURL(client.BaseURL())
`
