### ISSUE TITLE
Add support for automatic json unmarshalling using map on response

### ISSUE THREAD

**Issue by moorara** [go-resty/resty#52]
Can you please bring automatic JSON unmarshalling using `map` on response like `struct`?

I'm trying to do something like the following:

```go
resp, err := resty.R().SetResult(map[string]interface{}{}).Get(url)
result := resp.Result().(*map[string]interface{})
fmt.Printf("%+v", result["message"])
```

**Comment by jeevatkm** [comment]
Sure, I will add support for `map` for `JSON` content type.

**Comment by jeevatkm** [comment]
@moorara - It seems resty already supports `map` type.

I have created this test case method for resty. Have a look and share your thought.

```go
func TestPostJSONResultMapSuccess(t *testing.T) {
	ts := createPostServer(t)
	defer ts.Close()

	c := dc()
	c.SetDebug(false)

	resp, err := c.R().
		SetBody(map[string]interface{}{"username": "testuser", "password": "testpass"}).
		SetResult(map[string]interface{}{}).
		Post(ts.URL + "/login")

	assertError(t, err)
	assertEqual(t, http.StatusOK, resp.StatusCode())

	result := (*resp.Result().(*map[string]interface{}))
	fmt.Println("result[id]:", result["id"])
	fmt.Println("result[message]:", result["message"])
}
```

Also added dereferencing for your code snippet. It works.

```go
resp, err := resty.R().SetResult(map[string]interface{}{}).Get(url)
result := (*resp.Result().(*map[string]interface{}))
fmt.Printf("%+v", result["message"])
```

**Comment by jeevatkm** [comment]
@moorara can you please share your feedback?

**Comment by jeevatkm** [comment]
@ChristianLohmann I saw thumps up for map support. Can you please see my above responses and share your feedback?

**Comment by ChristianLohmann** [comment]
Nice idea would appreciate to have. Is there also the demand of having slices marshaled to result? For me it would make sense to have response bodys like 
```
[
  {
    "prop1": {},
    "prop2": "",
    "prop3": 1,
    "prop4": []
  }
]
```
automatically get unmarshaled to result?

**Comment by jeevatkm** [comment]
@ChristianLohmann - actually resty already supports map. Key point is; you have to `dereference` it before using a map.

```go
resp, err := resty.R().SetResult(map[string]interface{}{}).Get(url)
result := (*resp.Result().(*map[string]interface{}))
fmt.Printf("%+v", result["message"])
```

I have tested at my end for `map` and Can you please try and let me know?

**Comment by jeevatkm** [comment]
Since resty already has map support, it just user have to deference it before use.

I'm closing it. Thanks @moorara @ChristianLohmann

**Comment by sidtelco** [comment]
I tried but it not works 

`require github.com/go-resty/resty/v2 v2.1.0`

`
resp, err = client.R().
		EnableTrace().
		SetHeader("Accept", "application/json").
		SetResult(map[string]interface{}{}).
		Get("https://...../person/filtered")

	if err != nil {
		panic(err)
	}
`
panic: json: cannot unmarshal array into Go value of type map[string]interface {}
