### ISSUE TITLE
is there a way to catch `tcp dial temporarily failed` error in linux?

### ISSUE THREAD

**Issue by rew1nter** [go-resty/resty#523]
The above error is caused by less ulimit. But is there a way to catch it and act?

**Comment by moorereason** [comment]
I haven't tested this, but...you should be able to check if the error is a `net.Error` and then check to see if `Error.Temporary()` is true.  If it's a `net.OpError`, you may have to check `OpError.Error()` to get at the `net.Error` value.

See https://pkg.go.dev/net#Error

**Comment by rew1nter** [comment]
How do you catch these two errors
1. `tcp dial timeout`
2. `server response with unsolicited /r/n..`
