### ISSUE TITLE
What is BaseURL ?

### ISSUE THREAD

**Issue by henri9813** [go-resty/resty#531]
Hello,

What is BaseURL ?

I searched in the resty code but i don't find the usage of baseURL variable ?

Do you have an example of code which use baseurl ?

Best regards

**Comment by henri9813** [comment]
Okay, code present in this issue seems to be a good example: https://github.com/go-resty/resty/issues/491

**Comment by moorereason** [comment]
https://pkg.go.dev/github.com/go-resty/resty/v2#Client.SetBaseURL

**Comment by Abhimanyuaj001** [comment]
Make sure you are using the latest version currently v2.11.0.
