### ISSUE TITLE
Support socks5 proxies

### ISSUE THREAD

**Issue by ssut** [go-resty/resty#54]
Seeing resty allows proxies to be set by URL which involves parsing and identifying its scheme, most people would expect that it supports other proxy schemes such as socks5. However, when I try to set socks5 proxy, It connects to the socks5 proxy host by using a http proxy model.

The reason why I need this is typically Tor listens only for socks5 connections. I know of no project using golang that currently supports socks5 proxy, but is there any way this could be built into the resty?

**Comment by jeevatkm** [comment]
@ssut Thanks for your question.

I have added example of socks5 proxy in this [commit](ef723efa2a1b4fcdbafb5b1e7c6cf42065519728).  Later I will added built-in support in the `resty`.

**Comment by ssut** [comment]
Thanks for your help. By the way, I attempted to do that with [`.SetTimeout`](https://github.com/go-resty/resty/blob/master/client.go#L501-L513), but it didn't work out. I'm guessing it will not work with a way of this. Wht do I have to do to get it work?

**Comment by jeevatkm** [comment]
Yes, `SetTimeout` won't work in your scenario. Because as per example you're using custom `http.Transport`. I'm not sure this library `golang.org/x/net/proxy` supports timeout. I need to verify it.
