### ISSUE TITLE
Resty not exponentially backing off when retrying

### ISSUE THREAD

**Issue by mhandrea** [go-resty/resty#543]
I'm unable to get resty to exponentially backoff while retrying. Regardless of the different settings I try to use it still just retries with about 1/2 second waits between retries.

My understanding was the default functionality would be to exponentially backoff the SetRetryCount over a period of time up to your SetRetryMaxWaitTime.

My example below creating a Resty Client:

```
return resty.New().
SetLogger(logDiscard).
SetRetryCount(retryCount).
SetRetryMaxWaitTime(time.Duration(maxSeconds)*time.Second).
AddRetryCondition(func(r *resty.Response, err error) bool {
	fmt.Println(">>>>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>>>")
	fmt.Println(time.Now())
	fmt.Println(time.Duration(maxSeconds) * time.Second)
	return r.StatusCode() == http.StatusTooManyRequests
}).
SetHeader("User-Agent", UserAgent).
SetHeader("Content-Type", "application/json")
```

Below is the output of retryCount = 6 and maxSeconds = 90:

```
>>>>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>>>
2022-05-16 21:45:54.589845177 +0000 UTC m=+2.601093806
1m30s
>>>>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>>>
2022-05-16 21:45:54.838507679 +0000 UTC m=+2.849756308
1m30s
>>>>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>>>
2022-05-16 21:45:55.114213311 +0000 UTC m=+3.125461941
1m30s
>>>>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>>>
2022-05-16 21:45:55.48139674 +0000 UTC m=+3.492645369
1m30s
>>>>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>>>
2022-05-16 21:45:56.079903824 +0000 UTC m=+4.091152473
1m30s
>>>>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>>>
2022-05-16 21:45:57.378905351 +0000 UTC m=+5.390153979
1m30s
>>>>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>>>
2022-05-16 21:46:00.140447914 +0000 UTC m=+8.151696543
1m30s
```

As you can see it did all 6 retries back to back, not backing off over the max retry time of 90 seconds.

I notice the documentation lists a Backoff() but I feel the documentation talking about the Backoff functionality does not reflect what is going on currently (Backoff function deprecated?).

If anyone has any tips on how to get exponential backoff to work please let me know. Thanks.

**Comment by mhandrea** [comment]
I see that I misunderstood SetRetryMaxWaitTime. I thought it was the total time retrying, but it's the max time between wait times.

However, I still don't understand why backoff is not working.

**Comment by mhandrea** [comment]
Bump. I still don't understand how exponential backoff works with Resty and cannot find an explicit example online anywhere either using the Backoff function or configuring it off resty.New(). Thanks.

**Comment by moorereason** [comment]
After doing some testing myself today, the backoff implementation appears to work fine, but you're probably not noticing it working since the default initial RetryWaitTime is 100ms.  Try adding `SetRetryWaitTime(1 * time.Second)` to your client setup.

Here's a crude example:

```go
package main

import (
        "fmt"
        "net/http"
        "time"

        "github.com/go-resty/resty/v2"
)

func main() {
        var last time.Time

        _, _ = resty.New().
                SetRetryCount(10).
                SetRetryWaitTime(1 * time.Second).
                SetRetryMaxWaitTime(90 * time.Second).
                AddRetryCondition(func(r *resty.Response, err error) bool {
                        if !last.IsZero() {
                                fmt.Println(time.Now().Sub(last))
                        }
                        last = time.Now()
                        return r.StatusCode() == http.StatusTooManyRequests
                }).
                R().
                Get("https://httpbin.org/status/429")
}
```

**Comment by mhandrea** [comment]
> After doing some testing myself today, the backoff implementation appears to work fine, but you're probably not noticing it working since the default initial RetryWaitTime is 100ms. Try adding `SetRetryWaitTime(1 * time.Second)` to your client setup.

Fantastic! Thank you. I changed RetryWaitTime to 30 seconds and am getting the exponential backoff I expected. Over the course of 5 retries with a RetryWaitTime of 30 seconds, the waiting times were approx 30s, 40s, 100s, 200s, 480s (succeeded here)...

```
>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>
retry count: 1/10, retryWaitTime: 30*time.Second, retryMaxWaitTime: 900*time.Second
2022-06-08 15:45:54.439941487 +0000 UTC m=+1.196011608

>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>
retry count: 2/10, retryWaitTime: 30*time.Second, retryMaxWaitTime: 900*time.Second
2022-06-08 15:46:24.562109665 +0000 UTC m=+31.318179796

>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>
retry count: 3/10, retryWaitTime: 30*time.Second, retryMaxWaitTime: 900*time.Second
2022-06-08 15:47:02.118173242 +0000 UTC m=+68.874243353

>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>
retry count: 4/10, retryWaitTime: 30*time.Second, retryMaxWaitTime: 900*time.Second
2022-06-08 15:48:39.35460013 +0000 UTC m=+166.110670231

>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>
retry count: 5/10, retryWaitTime: 30*time.Second, retryMaxWaitTime: 900*time.Second
2022-06-08 15:51:53.810086343 +0000 UTC m=+360.566156444

>>>>>>>>>>>>>RETRY CONDITION>>>>>>>>>>>>>
retry count: 6/10, retryWaitTime: 30*time.Second, retryMaxWaitTime: 900*time.Second
2022-06-08 15:59:27.274193503 +0000 UTC m=+814.030263623
```

When messing around with RetryWaitTime I must not have had a large enough RetryWaitTIme coupled with a large enough RetryCount to actually see the backoff working. It stems from me thinking the RetryMaxWaitTime was the upper bound that the exponential backoff was being scaled to (smaller RetryMaxWaitTime, backoff ramps up faster, etc). But now that I know that's not what that does, setting the RetryWaitTime makes much more sense as the starting point the backoff is calculated from. 

I know it's unusual to need retries over a course of 10 minutes, but thank you thank you for taking the time to take a look into my issue!!!
