### ISSUE TITLE
implement `SetTimeout` without touching http.Client.Timeout

### ISSUE THREAD

**Issue by okhowang** [go-resty/resty#545]
currently `SetTimeout` just modify `http.Client.Timeout`
```golang
func (c *Client) SetTimeout(timeout time.Duration) *Client {
	c.httpClient.Timeout = timeout
	return c
}
```
when we create `resty.Client` with `NewWithClient`. it do side effect if we use http.Client in other code.
maybe we should keep timeout in `resty.Client`, and do `context.WithTimeout` before every request?

**Comment by yunduan16** [comment]
+1

**Comment by aadog** [comment]
https://github.com/go-resty/resty/issues/574

**Comment by aadog** [comment]
I implemented session pattern, you can use
