### ISSUE TITLE
Add an option to support meta redirection

### ISSUE THREAD

**Issue by ssut** [go-resty/resty#55]
This is not a standard yet but it'd be great if Resty support redirection using meta refresh such as:
```html
<meta http-equiv="refresh" content="0; url=/index.jsp">
```
```go
resty.FollowMetaRedirects(true)
```
Most websites follow the HTTP standard, which contains declarations for standard redirection method, but some don't. However, this is not so important because it's often not the case and can cause performance issues.

**Comment by jeevatkm** [comment]
It seems useful, will give it a try later on. Thanks.
