### ISSUE TITLE
Allow SetOutput and SetResult to be used together

### ISSUE THREAD

**Issue by Southclaws** [go-resty/resty#552]
It seems SetOutput reads the entire stream then SetResult will error with `unexpected end of JSON input`

Would be useful to allow these together.

Use case:

We use resty in end-to-end API tests and one pattern we use is dumping outputs of specific endpoints to files which can be used for frontend fixtures/examples for the frontend team. I like to keep test code simple so it would be awesome to be able to make these HTTP requests for tests concise using Resty:

```go
				r, err := cl.R().
					SetHeader("Authorization", user.SeedUser_11_Account.AuthToken).
					SetOutput(testhelpers.OutputPath(t, "api", path)("get.json")). // outputs the result of this test to a file
					SetResult(&result). // also parse the response and store in a variable for test assertions
					Get(path)
				testhelpers.AssertResponseNoError(t, err, r)

				assert.Equal(t, expected, result)
```

**Comment by jeevatkm** [comment]
@Southclaws I think if both options get used together, it will double the memory consumption. Any thoughts?

**Comment by jeevatkm** [comment]
This is possible with the upcoming Resty v3 using `SetResponseBodyUnlimitedReads(true)`

Refer to test case - https://github.com/go-resty/resty/blob/13e4cad15dd051198d22cf8e53a4f92de8cad535/request_test.go#L2175-L2202
