### ISSUE TITLE
Expect support R() to support SetDebug()

### ISSUE THREAD

**Issue by fitan** [go-resty/resty#558]
client.SetDebug is global. There's a lot of distracting information

client.R().SetDebug. Can control the range very well

**Comment by aadog** [comment]
https://github.com/go-resty/resty/issues/574
I implemented session pattern, you can use

**Comment by fitan** [comment]
> #574 我实现了会话模式，你可以使用

Thank you, but he didn't merge

**Comment by fitan** [comment]
> #574 I implemented session pattern, you can use

Thank you, but he didn't merge

**Comment by jeevatkm** [comment]
@fitan SetDebug method added to Request level - https://github.com/go-resty/resty/pull/693/commits/a3685f948fb89a7601c0cedefc2f2bffe0e617d7 released with v2.8.0
