### ISSUE TITLE
WARNING: DATA RACE in resty when trace is enabled

### ISSUE THREAD

**Issue by robert-deepnorth** [go-resty/resty#559]
I have a long running app which sends hundreds of GET requests per second using 3rd-party library(https://github.com/polygon-io/client-go) which uses resty under the hood.

1. Each GET request is a separate go routine.
2. client-go library shares a single resty client across those go routines
3. client-go library create a new request struct for every request we execute (client. R())
4. trace is enabled by calling resty client EnableTrace()
5. trace info is fetched in resty client OnAfterResponse(). This is the only way I can access TraceInfo() because client-go library wrap the response and request.

Any idea what's the problem here? Thanks

Go version is 1.18. Resty version is 2.7.0

`==================
WARNING: DATA RACE
Write at 0x00c0065c2f48 by goroutine 2691:
  github.com/go-resty/resty/v2.(*clientTrace).createContext.func4()
      go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/trace.go:110 +0x56
  net.(*sysDialer).dialSingle.func1()
      go/go1.19beta1/src/net/dial.go:575 +0xde
  runtime.deferreturn()
      go/go1.19beta1/src/runtime/panic.go:476 +0x32
  net.(*sysDialer).dialSerial()
      go/go1.19beta1/src/net/dial.go:550 +0x47d
  net.(*sysDialer).dialParallel()
      go/go1.19beta1/src/net/dial.go:451 +0x5bd
  net.(*Dialer).DialContext()
      go/go1.19beta1/src/net/dial.go:428 +0xb1d
  net.(*Dialer).DialContext-fm()
      <autogenerated>:1 +0x99
  net/http.(*Transport).dial()
      go/go1.19beta1/src/net/http/transport.go:1169 +0x273
  net/http.(*Transport).dialConn()
      go/go1.19beta1/src/net/http/transport.go:1607 +0xd97
  net/http.(*Transport).dialConnFor()
      go/go1.19beta1/src/net/http/transport.go:1449 +0x13a
  net/http.(*Transport).queueForDial.func3()
      go/go1.19beta1/src/net/http/transport.go:1430 +0x47

Previous write at 0x00c0065c2f48 by goroutine 2478:
  github.com/go-resty/resty/v2.(*clientTrace).createContext.func4()
      go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/trace.go:110 +0x56
  net.(*sysDialer).dialSingle.func1()
      go/go1.19beta1/src/net/dial.go:575 +0xde
  runtime.deferreturn()
      go/go1.19beta1/src/runtime/panic.go:476 +0x32
  net.(*sysDialer).dialSerial()
      go/go1.19beta1/src/net/dial.go:550 +0x47d
  net.(*sysDialer).dialParallel()
      go/go1.19beta1/src/net/dial.go:451 +0x5bd
  net.(*Dialer).DialContext()
      go/go1.19beta1/src/net/dial.go:428 +0xb1d
  net.(*Dialer).DialContext-fm()
      <autogenerated>:1 +0x99
  net/http.(*Transport).dial()
      go/go1.19beta1/src/net/http/transport.go:1169 +0x273
  net/http.(*Transport).dialConn()
      go/go1.19beta1/src/net/http/transport.go:1607 +0xd97
  net/http.(*Transport).dialConnFor()
      go/go1.19beta1/src/net/http/transport.go:1449 +0x13a
  net/http.(*Transport).queueForDial.func3()
      go/go1.19beta1/src/net/http/transport.go:1430 +0x47

Goroutine 2691 (running) created at:
  net/http.(*Transport).queueForDial()
      go/go1.19beta1/src/net/http/transport.go:1430 +0x425
  net/http.(*Transport).getConn()
      go/go1.19beta1/src/net/http/transport.go:1372 +0x8e4
  net/http.(*Transport).roundTrip()
      go/go1.19beta1/src/net/http/transport.go:581 +0xd13
  net/http.(*Transport).RoundTrip()
      go/go1.19beta1/src/net/http/roundtrip.go:17 +0x36
  net/http.send()
      go/go1.19beta1/src/net/http/client.go:251 +0x942
  net/http.(*Client).send()
      go/go1.19beta1/src/net/http/client.go:175 +0x164
  net/http.(*Client).do()
      go/go1.19beta1/src/net/http/client.go:715 +0x10c8
  net/http.(*Client).Do()
      go/go1.19beta1/src/net/http/client.go:581 +0x88c
  github.com/go-resty/resty/v2.(*Client).execute()
      go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/client.go:932 +0x836
  github.com/go-resty/resty/v2.(*Request).Execute.func1()
      go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:769 +0x184
  github.com/go-resty/resty/v2.Backoff()
      go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/retry.go:105 +0x207
  github.com/go-resty/resty/v2.(*Request).Execute()
      go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:763 +0x9c4
  github.com/polygon-io/client-go/rest/client.(*Client).CallURL()
      go/pkg/mod/github.com/polygon-io/client-go@v1.0.1/rest/client/client.go:81 +0x8ae
  github.com/polygon-io/client-go/rest/client.(*Client).Call()
      go/pkg/mod/github.com/polygon-io/client-go@v1.0.1/rest/client/client.go:64 +0x15b
  github.com/polygon-io/client-go/rest.(*ReferenceClient).GetTickerDetails()
      go/pkg/mod/github.com/polygon-io/client-go@v1.0.1/rest/reference.go:61 +0x14d
  foresight.io/polygon.Polygon.GetTickerDetail()
      go/src/foresight/backend/polygon/ticker.go:33 +0x1e4
  foresight.io/app/cmd.getShares.func1()
      go/src/foresight/backend/app/cmd/update.go:132 +0xf2
  foresight.io/app/cmd.getShares.func2()
      go/src/foresight/backend/app/cmd/update.go:142 +0x66

Goroutine 2478 (running) created at:
  net/http.(*Transport).queueForDial()
      go/go1.19beta1/src/net/http/transport.go:1430 +0x425
  net/http.(*Transport).getConn()
      go/go1.19beta1/src/net/http/transport.go:1372 +0x8e4
  net/http.(*Transport).roundTrip()
      go/go1.19beta1/src/net/http/transport.go:581 +0xd13
  net/http.(*Transport).RoundTrip()
      go/go1.19beta1/src/net/http/roundtrip.go:17 +0x36
  net/http.send()
      go/go1.19beta1/src/net/http/client.go:251 +0x942
  net/http.(*Client).send()
      go/go1.19beta1/src/net/http/client.go:175 +0x164
  net/http.(*Client).do()
      go/go1.19beta1/src/net/http/client.go:715 +0x10c8
  net/http.(*Client).Do()
      go/go1.19beta1/src/net/http/client.go:581 +0x88c
  github.com/go-resty/resty/v2.(*Client).execute()
      go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/client.go:932 +0x836
  github.com/go-resty/resty/v2.(*Request).Execute.func1()
      go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:769 +0x184
  github.com/go-resty/resty/v2.Backoff()
      go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/retry.go:105 +0x207
  github.com/go-resty/resty/v2.(*Request).Execute()
      go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:763 +0x9c4
  github.com/polygon-io/client-go/rest/client.(*Client).CallURL()
      go/pkg/mod/github.com/polygon-io/client-go@v1.0.1/rest/client/client.go:81 +0x8ae
  github.com/polygon-io/client-go/rest/client.(*Client).Call()
      go/pkg/mod/github.com/polygon-io/client-go@v1.0.1/rest/client/client.go:64 +0x15b
  github.com/polygon-io/client-go/rest.(*ReferenceClient).GetTickerDetails()
      go/pkg/mod/github.com/polygon-io/client-go@v1.0.1/rest/reference.go:61 +0x14d
  foresight.io/polygon.Polygon.GetTickerDetail()
      go/src/foresight/backend/polygon/ticker.go:33 +0x1e4
  foresight.io/app/cmd.getShares.func1()
      go/src/foresight/backend/app/cmd/update.go:132 +0xf2
  foresight.io/app/cmd.getShares.func2()
      go/src/foresight/backend/app/cmd/update.go:142 +0x66
==================`

**Comment by jeevatkm** [comment]
@robert-deepnorth, as far as I understand, the trace feature will not result in a data race. It would be helpful for you to get some insight from client-go team. I'm glad to take care of it if anything needs to be done.

My 2 cents: it seems you're exploring go 1.19beta1 version. Ideally, I would recommend using the Go release version to validate.
