### ISSUE TITLE
Warn-level logging on retries attempts

### ISSUE THREAD

**Issue by ThePsina** [go-resty/resty#561]
Current implementation of (r *Request) Execute(method, url string) (*Response, error) uses Backoff function with hardcoded attempts errors log on Error level:

`r.client.log.Errorf("%v, Attempt %v", err, r.Attempt)`

With enabled retry feature it may be unnecessary for someone to log unsuccessful attempts on Error level. Desired approach would be to log attempts errors on Warning level and only log on Error level if all retries are exceeded with no success.

Can it be achieved with current versions of resty?

Can this behavior be configurable? Maybe even add custom callbacks to handle retry errors?

**Comment by jj0e** [comment]
I am wondering the same thing. I do not want ERROR level logging yet it is being printed to stdout. How can I prevent this?

**Comment by ThePsina** [comment]
May be someday one of the contributors will answer this question....

**Comment by segev-indegy** [comment]
This actually duplicates #554 . I will be happy to make the change if I get the ok from @jeevatkm
