### ISSUE TITLE
Make Client.SetHeader concurrent-safe with mutex

### ISSUE THREAD

**Issue by jinleileiking** [go-resty/resty#564]
c.RestyClient.SetHeaders(headers)    will be concurrent map issue.

Only use R().SetHeaders

**Comment by moorereason** [comment]
Why do you consider this a bug?

**Comment by sandyydk** [comment]
If it causes concurrent map issue it could be fixed in two ways 
* Un-expose the method.
* Or use a syncMap to implement the same.

I can pick this up if this is to be done. Let me know. @jeevatkm

**Comment by jeevatkm** [comment]
@jinleileiking Typically, a client happens before using the clients. Can you provide more details on your usage?

@sandyydk FYI, the approaches you mentioned do not apply to this scenario.

**Comment by jeevatkm** [comment]
Resty v3 Client has a `sync.RWMutex` to make property modification concurrent-safe. Currently, the development version is available on the branch `main`.
