### ISSUE TITLE
OnBeforeRequest does not change Request.RawRequest attributes

### ISSUE THREAD

**Issue by ChristianLohmann** [go-resty/resty#57]
Trying to manipulate `*resty.Request` fields inside an `OnBeforeRequest` function does not affect the actual request,  which is finally executed:

https://github.com/go-resty/resty/blob/master/client.go#L627-L645
```
for _, f := range c.beforeRequest {
		err = f(c, req)
		if err != nil {
			return nil, err
		}
	}

	c.mutex.Lock()

	if req.proxyURL != nil {
		c.transport.Proxy = http.ProxyURL(req.proxyURL)
	} else if c.proxyURL != nil {
		c.transport.Proxy = http.ProxyURL(c.proxyURL)
	}

	req.Time = time.Now()
	c.httpClient.Transport = c.transport

	resp, err := c.httpClient.Do(req.RawRequest)
```
All `OnBeforeRequest` functions will be executed but they have no effect when they call methods directly on `*resty.Request` because the `RawRequest` stays untouched until real request execution.

For example setting an auth token header inside an `OnBeforeRequest` function won't work with 
```
	httpClient.OnBeforeRequest(func(c *resty.Client, r *resty.Request) error {
		r.SetAuthToken("bla")
                return nil
        })
```
 As a workaround one has to manipulate directly the `r.RawRequest` struct.

**Comment by jeevatkm** [comment]
Thanks for reporting @ChristianLohmann. I will have a look.

**Comment by jeevatkm** [comment]
I had a look and understood what you have describe. I will correct the execution sequence of `OnBeforeRequest`.

Please continue to modify the `*resty.Request` after the fix. Tomorrow fix will be available on master and will be released part of `v0.11`.

**Comment by ChristianLohmann** [comment]
Many thanks for this quick reply and  providing a fix that fast!

**Comment by jeevatkm** [comment]
Fix available on master branch. Please give it a try and let me know.

**Comment by ChristianLohmann** [comment]
Thanks, it works now!

**Comment by jeevatkm** [comment]
Thanks for the confirmation. I believe `master` branch is working without any issues.

**Comment by ChristianLohmann** [comment]
I haven't experienced any other issues with the master so far. I glued the commit hash to c53a09aa1fdff556f8e7034acc3202ca8cc13c2f with glide until a new release is available via gopkg.in.

**Comment by jeevatkm** [comment]
Thank you. I'm closing this issue.
