### ISSUE TITLE
Nil Pointer access on timeout using retry

### ISSUE THREAD

**Issue by ChristianLohmann** [go-resty/resty#58]
When a request interrupts due to a client timeout and when using a retry condition function then the underlying `resty.Response.RawResponse` is `nil`. Which is pretty obvious because the remote haven't sent any. But one has to make a `nil` check on the `RawResponse` in `RetryConditionFunc`s because functions like  `resty.Response.StatusCode()` access directly the underlying `RawResponse`s fields.

**Comment by jeevatkm** [comment]
@ChristianLohmann Thanks for your inputs. I will have a look and get back to you.

**Comment by jeevatkm** [comment]
@ChristianLohmann I have added nil check while access `RawResponse` returns value appropriately. Will be pushing the changes tomorrow and also making `v0.11` release.

**Comment by ChristianLohmann** [comment]
Thanks for that @jeevatkm !
