### ISSUE TITLE
json: unsupported type: func() (io.ReadCloser, error)

### ISSUE THREAD

**Issue by samsulbahari** [go-resty/resty#585]
hello this my code 

resp, _ := client.R().
		SetHeader("Content-Type", "application/json").
		SetBody(login).
		SetResult(&response).
		Post("http://localhost:8080/login")

	
	ctx.JSON(resp.StatusCode(), resp)

ayone help ?

**Comment by segevda** [comment]
It's a bit unclear what you're trying to do here. making a resty request and then serializing the resty response object in to a gin (maybe?) response..?

It seems like the error originates from gin, but it's really hard to know without more context
