### ISSUE TITLE
Unix socket example not working

### ISSUE THREAD

**Issue by sounddroid** [go-resty/resty#589]
Hi there! I followed the unix socket example in the README and referenced in #80 but I am getting the following error:

```
http: no Host in request URL
```

Any ideas on a workaround?

**Comment by raharper** [comment]
Interested in this as well.  Seeing this with go 1.18

**Comment by raharper** [comment]
You can use a throwaway hostname it seems:

```
// Supply transport type (http) and fake hostname along with the path you want
client.R().Get("http://fakehost/index.html")
```

**Comment by sounddroid** [comment]
Oh wow. Didn't even think to check that workaround. Does it actually work?

**Comment by jeevatkm** [comment]
@sounddroid I believe it suppose to be `http://localhost/`, will update the readme and also added a sample test too.
