### ISSUE TITLE
Lost repsonse and no error return

### ISSUE THREAD

**Issue by lrita** [go-resty/resty#59]
Someone api will cost N ms.

If we `SetTimeout` M ms (N< M < 2N) to `Client` and we call this api twice,  the server side will receive three request and send three response. 

In client side, user only see 2 api call but 3 api call be sent actually.

This issue will be duplicated in go 1.7.3, [here is the code](https://github.com/lrita/resty/blob/fix-timeout-issue/client_test.go#L101-L120).

I found a bad implement of `SetTimeout` and fix it.

**Comment by jeevatkm** [comment]
@lrita Thanks for your PR, I have added a comment. Please have a look.

**Comment by lrita** [comment]
I have fixed the build errors in golang 1.2.

**Comment by jeevatkm** [comment]
Thanks @lrita.

**Comment by jeevatkm** [comment]
PR #60 Merged.
