### ISSUE TITLE
Stuck after changing network adaptor/IP if using global client

### ISSUE THREAD

**Issue by athenakia** [go-resty/resty#593]
This is my scenario: 
I write a DDNS automatic update program using resty and run it on an Azure VPS. I use a global client(resty.New() assigned to a global variable) to send request to dns resolution service provider(such as Cloudflare). 

Then I rebound the azure VPS with the new network adaptor with new elastic IP. 

Then resty stuck, no normal response neither error is return. 

When settimeout for resty, it return error message "context deadline exceeded (Client.Timeout exceeded while awaiting headers)". 

After about 20 minutes, this problem fixed automatically and the DNS record updated as expected.

**Comment by athenakia** [comment]
When not using a global client(resty.New() every time), all the codes works as expected.

**Comment by janekolszak** [comment]
Have you found the problem?

**Comment by svarunan** [comment]
I too even use cloud fare domain name to hit one of my API.
I even get `context deadline exceeded (Client.Timeout exceeded while awaiting headers)`
This occurs rarely but when it happens most of my API fails.
i use below dialer and transport in `SetTransport`

```
	dialer := &net.Dialer{
		Timeout:   30 * time.Second,
		KeepAlive: 30 * time.Second,
		DualStack: true,
	}
	tranport := &http.Transport{
		Proxy:                 http.ProxyFromEnvironment,
		DialContext:           dialer.DialContext,
		ForceAttemptHTTP2:     true,
		MaxIdleConns:          100,
		IdleConnTimeout:       30 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
		MaxIdleConnsPerHost:   100,
		MaxConnsPerHost:       100,
	}
```
and then a `httpClient.Timeout` of 10sec. Not sure if its because of re-use connection if this is failing, Have to debug. its an on going issue for me

**Comment by jeevatkm** [comment]
@athenakia  @svarunan Any findings to share?

**Comment by janekolszak** [comment]
It may be because there's not enough CPU to handle the response, because it gets starved by some other processing. Maybe you're doing load tests?

**Comment by svarunan** [comment]
@jeevatkm, It turned out to be our network issues. Other services consuming different api at same moment also started failing.

**Comment by jeevatkm** [comment]
Thanks for the feedback. I will close this issue. If needed, we can create a new issue later on.

**Comment by athenakia** [comment]
ChatGPT suggests setting DisableKeepAlives in the transport:

```
client.SetTransport(&http.Transport{
	DisableKeepAlives: true,
})
```

It works well.
