### ISSUE TITLE
SetResult fails to parse JSON when the returned Content-Type is "application/x-amz-json-1.1" 

### ISSUE THREAD

**Issue by zackwine** [go-resty/resty#594]
I found the SetResult API fails to parse the result JSON if the `Content-Type` is equal to "application/x-amz-json-1.1" (which Amazon uses for some endpoints).  Would it be possible to add this as a supported Content-Type, or possibly support setting a custom JSON Content-Type for resty?

Looks like this is the regex that is failing to match:  https://github.com/go-resty/resty/blob/master/client.go#L63

**Comment by segevda** [comment]
As a workaround, you can set `application/json` as the content-type using Request.ForceContentType method, which will force resty to unmarshall the resp body as a JSON.

**Comment by zackwine** [comment]
@segevda  Thanks!
