### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by saeedgeek** [go-resty/resty#598]
i cant detect what error raise when i post a request with this library
in onError hook we get some error like ( connection error , EOF ,...) but i cant understand what error is this?
and sometime my response dosent set whit SetResult() method and it dosent rais any error
is there any way to separate this error without looking string of this error?

**Comment by kecci** [comment]
Hi @saeedgeek , Could you please share the code ?

First, about the `connection error , EOF`, i think it's you got empty response.
Second, I assume you are using `request POST` you mentioned before:

> i cant detect what error raise when i post a request with this library

An example of the request POST:
```
// POST JSON string
// No need to set content type, if you have client level setting
resp, err := client.R().
      SetHeader("Content-Type", "application/json").
      SetBody(`{"username":"testuser", "password":"testpass"}`).
      SetResult(&AuthSuccess{}).    // or SetResult(AuthSuccess{}).
      Post("https://myapp.com/login")
```

So there is 2 results of the request post: `resp, err`

1. resp -> which means the `resty.Response` here the struct:
```
type Response struct {
	Request     *Request
	RawResponse *http.Response

	body       []byte
	size       int64
	receivedAt time.Time
}
```

2. and err -> which means error from func execute
you can see more this func on: https://github.com/go-resty/resty/blob/313f4190d9b8f7605ff298b769de613621c50220/request.go#L735)

I hope this could be helpful for your discussion.

**Comment by jeevatkm** [comment]
@saeedgeek Do you have any input share with @kecci ?
