### ISSUE TITLE
performance problem

### ISSUE THREAD

**Issue by dandyhuang** [go-resty/resty#603]
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/12603054/203923929-4760ad95-6cd2-42b9-b2a2-79a5226197d2.png">
I'm not sure if resty uses a connection pool。resty is time-consuming, is this normal http1.1。I open EnableTrace，IsConnReused is true。

**Comment by jeevatkm** [comment]
@dandyhuang If you see the same behavior with Go default client, then the problem could be on the server side
