### ISSUE TITLE
Support trailing backslashes in URLs

### ISSUE THREAD

**Issue by marcusljx** [go-resty/resty#61]
Many REST APIs still include different behavior for addresses with a trailing slash vs without. For example:
```
GET /api/v1/dog
```
might possibly be different from
```
GET /api/v1/dog/
```

Current behavior is to trim the trailing backslash. I propose to include trailing backslashes and leave it to the user to specify the verbose path.

**Comment by jeevatkm** [comment]
I just had glance of request flow. `resty` does not do trim on URL. It just uses `url.Parse` method.

Could you go through resty code and help me to find an issue?

**Comment by marcusljx** [comment]
Sure. The path-trimming is just behavior I've noticed while using `resty`. I'll push something if I find anything.

**Comment by jeevatkm** [comment]
Okay thanks, just enable debug log in resty. Helpful for debugging.

**Comment by marcusljx** [comment]
Okay I think I made a mistake here. `resty` indeed does not trim the URL. It must have been something in my own code that was doing it. 

My apologies for the false alarm.

**Comment by jeevatkm** [comment]
Thank you for verify and your confirmation.
