### ISSUE TITLE
Protocol not available when updating from go 1.17 to 1.19

### ISSUE THREAD

**Issue by oliverlj** [go-resty/resty#610]
I'm running resty in a wam application

I got this error with default example : 

```
Error: Get "http://httpbin.org/get": dial tcp: lookup httpbin.org: Protocol not available
wasm_exec.js:19 Response Status Code: 0
wasm_exec.js:19 Response Status: 
wasm_exec.js:19 Response Body: 
wasm_exec.js:19 Response Time: 400.128µs
```

https://gitlab.com/c1560/cryptofiscafacile/-/merge_requests/824

I have tested http.get successfully

**Comment by oliverlj** [comment]
I have used this as a workaround : https://github.com/go-resty/resty/discussions/512#discussioncomment-1952147

**Comment by jeevatkm** [comment]
@oliverlj Thanks for bringing it up. @shynome did a PR #683 for this wasm I will try to add it.
