### ISSUE TITLE
Access to the specified website will be blocked and the timeout is invalid

### ISSUE THREAD

**Issue by reghtml** [go-resty/resty#616]
Test URL:
http://www.libertyphotos.net/

 `
client := resty.New()

client.SetTimeout(30 * time.Second)

fmt.Println(  "get start")

resp, err := client.R().Get(url)

fmt.Println( "get end")
`

Only "get start" will be output, and then stuck, and  "get end" will never be output

When GET accesses this website, it will be blocked directly, resulting in the process being occupied. How can I solve it

**Comment by kecci** [comment]
Hello @reghtml,

I think that url was stream protocol:
<img width="703" alt="Screenshot 2023-02-21 at 01 22 30" src="https://user-images.githubusercontent.com/25241073/220177512-e7b5c472-3877-47b2-83f3-5ced719cbff1.png">

I'm not sure, but it seems that protocol are not valid for this request.

You can try with other test URL: https://webhook.site/

I hope this can help your problem.

**Comment by ankitmalikg2** [comment]
Hi @reghtml ,
I have tried it and it's giving proper error.

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/16719111/221769518-44d48b47-f352-4f1f-88d0-4613b5d7673c.png">

**Comment by reghtml** [comment]
Thank you for your help, but it is accidental for me to test the dead process. It doesn't always get stuck. I haven't found a way to reproduce this problem 100% at present. I put it in the process to collect the web address. After collecting the web address, the process will always get stuck, causing the process in the transport pool to be occupied and will not stop. In addition, I won't get stuck using the official net/http. I will study it myself, See if there is a way to reproduce this problem 100%. It may also have something to do with the environment of the network. I am in China

**Comment by jeevatkm** [comment]
@reghtml I see, thanks for your response. If you could find the way to reproduce the problem, please create new issue or start a discussion thread. For now I'm marking this as closed.
