### ISSUE TITLE
Add an option for user-defined middleware after the built-in middlware, to modify the RawRequest object

### ISSUE THREAD

**Issue by ccp-ccollins** [go-resty/resty#62]
I wanted to use resty for requests to an AWS endpoint that requires requests to be signed with AWS credentials.  A library already exists for this (https://github.com/smartystreets/go-aws-auth), however using that one requires access to the http.Request object directly.  Currently, user defined middleware is run before the built-in middleware, which makes sense when modifying the resty.Request object.  However for resty to be compatible with go-aws-auth, I need middleware that is processed *after* the built-in middleware, so that the RawRequest object is available.

**Comment by jeevatkm** [comment]
Okay I will add. Thanks.

**Comment by jeevatkm** [comment]
@ccp-ccollins I thought through it, adding one more before request middleware will lead to confusion. Instead I'm planing to add `SetPreRequestHook` with same signature as middleware but only one can be added.

This will be available in `v0.12` release.

**Comment by jeevatkm** [comment]
@ccp-ccollins Sorry for the delay. Usually I make it quick. This time I got occupied with my [aah framework](https://aahframework.org) first public release.

`SetPreRequestHook` is ready and will be release with `v0.12`.

*_PS: If you could spare sometime, please have a look on aah framework and share your inputs. I would help me to improve the framework._*
