### ISSUE TITLE
Proposal: Response Body default JSON Unmarshal to provided golang struct or map

### ISSUE THREAD

**Issue by WhisperingChaos** [go-resty/resty#63]
Appreciate the default behavior of [Request SetBody(interface{})](https://godoc.org/github.com/go-resty/resty#Request.SetBody) to "Automatic marshalling for JSON and XML content type, if it is `struct` or `map`."  Would suggest the same automatic unmarshalling for [Reponse Body()](https://godoc.org/github.com/go-resty/resty#Response.Body() when specified with an interface{} argument.

**Comment by jeevatkm** [comment]
I believe you referring this https://godoc.org/github.com/go-resty/resty#Request.SetResult

**Comment by WhisperingChaos** [comment]
Thank you for:

- A package that simplified my code!
- Your quick reply to this issue!
- The link you provided to the desired feature!

I've encoded the solution proposed by the link but am unable to obtain the data for the unmarshalled object.  Here's a code snippet:
```
type EntropyPost struct {
	Session_id string   `json:"session-id"`
	Length     uint     `json:"length"`
	Entropy    []uint32 `json:"entropy"`
}

	req := resty.R().
		SetHeader("Content-Type", "application/json").
		SetBody(body). // automatic conversion to json
		SetResult(&EntropyPost{})

	var resp *resty.Response
	if resp, err = req.Post("http://172.17.0.2:8080/v1/316395C9-7226-41B2-94D7-013B778288FB/B615E471-CC76-4772-A879-3C865A131325/entropy/"); err != nil {
		t.Fatal("Client get failed: " + err.Error())
	}
	fmt.Fprintln(os.Stderr, resp.Status())
	var reply EntropyPost
	if err := json.Unmarshal(resp.Body(), &reply); err != nil {
		t.Fatal("Client unmarshal failed: " + err.Error())
	}
	fmt.Fprintf(os.Stderr, "reply: %v\n", reply)
	fmt.Fprintf(os.Stderr, "Result(): %v\n", resp.Result().(*EntropyPost))
```
Here's the generated output:
```
200 OK
reply: {sessionId 128 [16909060 84281096 151653132 219025168]}
Result(): &{ 0 []}
```
The output demonstrates that a manual decoding of the json produces the expected result.  However,
I must be missing something simple in the encoding of the SetResult & companion Result() that prevents the automatic unmarshalling to EntropyPost.  I would appreciate your insight to identify the problem.  Thanks!

**Comment by jeevatkm** [comment]
Response automatic marshaling happens based on response `Content-Type` header and Status Code.

Can you please enable debug `resty.SetDebug(true)` in resty? and give me that details. It will help me to identify an issue.

**Comment by WhisperingChaos** [comment]
Again, thank you for you kind assistance!  Using your suggestion of enabling SetDebug() method provided the information I needed to identify the problem.  In this situation, the server's content type was set to plain text, not json.

Sorry to have had you remotely debug "my" problem.

**Comment by jeevatkm** [comment]
I'm happy for you, you're welcome.
