### ISSUE TITLE
setting 'accept' header if 'content-type' header is set to JSON or XML type

### ISSUE THREAD

**Issue by Dylmay** [go-resty/resty#643]
The 'accept' header is set if the 'content-type' header is a JSON or XML type which causes unexpected behavior if creating a request like [here](https://github.com/opencontainers/distribution-spec/issues/396), where the underlying spec requires a JSON type but the server is not expected to return the same type, or any type, back.

Is there reasoning to set the 'accept' header automatically if it is a JSON or XML type? It seems like the auto-setting of the accept header should be toggle-able by client or the 'accept' header should only auto-set for basic MIME types.

**Comment by jeevatkm** [comment]
@Dylmay Typically, resty understands the JSON and XML marshal/unmarshals. Hence, it notifies the server via the Accept header if it sees content type JSON/XML and the Accept header is empty.

https://github.com/go-resty/resty/blob/e12ab69242b5618ed20e52f44d3e54db10c957a9/middleware.go#L129-L132

So, if the user sets the Accept header explicitly, then Resty will not do any action.

**Comment by Greyh4t** [comment]
I have encountered the same issue as well. In principle, resty should not set any unexpected header for the user. Users are supposed to set headers themselves, and in some cases, it is necessary not to set certain headers. In the current mode, if users want to avoid setting the User-Agent or Accept header, there is no way to do so.

**Comment by Greyh4t** [comment]
> @Dylmay Typically, resty understands the JSON and XML marshal/unmarshals. Hence, it notifies the server via the Accept header if it sees content type JSON/XML and the Accept header is empty.
> 
> https://github.com/go-resty/resty/blob/e12ab69242b5618ed20e52f44d3e54db10c957a9/middleware.go#L129-L132
> 
> So, if the user sets the Accept header explicitly, then Resty will not do any action.

I have encountered the same issue as well. In principle, resty should not set any unexpected header for the user. Users are supposed to set headers themselves, and in some cases, it is necessary not to set certain headers. In the current mode, if users want to avoid setting the User-Agent or Accept header, there is no way to do so.

**Comment by jeevatkm** [comment]
@Greyh4t @Dylmay, the user could modify any header on the request via `PreRequestHook.`

**Comment by jeevatkm** [comment]
Done on upcoming Resty v3
