### ISSUE TITLE
Bug: `context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

### ISSUE THREAD

**Issue by daidai21** [go-resty/resty#646]
when use like this:

```go

func service(query string) {
	resp, err := resty.New().SetTimeout(20 * time.Second).R().
		EnableTrace().
		SetFormData(map[string]string{
			"query": query,
		}).
		Post("xxx")

	
}

```

out: (occasionally)
```shell
context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by daidai21** [comment]
change to:
```go

cli := resty.New().SetTimeout(20 * time.Second)


func service(query string) {
	resp, err := cli.R().
		EnableTrace().
		SetFormData(map[string]string{
			"query": query,
		}).
		Post("xxx")
}

```

then succeed.

The error will no longer occur

**Comment by daidai21** [comment]
1GB mem, 1core cpu  server

**Comment by jeevatkm** [comment]
@daidai21 typically, creating a resty client once and firing N no. of request using that client is recommended.
In the first example, you're creating a client every time, which is unsuitable for system resource usage.
The second example usage is correct.

**Comment by athenakia** [comment]
> @daidai21 typically, creating a resty client once and firing N no. of request using that client is recommended. In the first example, you're creating a client every time, which is unsuitable for system resource usage. The second example usage is correct.

I encountered the same case when I followed the second example as well. Moreover, why does the first example result in an error, instead of giving a warning tip? This is quite frustrating.

**Comment by athenakia** [comment]
#593

**Comment by athenakia** [comment]
> > > @daidai21 typically, creating a resty client once and firing N no. of request using that client is recommended. In the first example, you're creating a client every time, which is unsuitable for system resource usage. The second example usage is correct.
> > 
> > 
> > I encountered the same case when I followed the second example as well. Moreover, why does the first example result in an error, instead of giving a warning tip? This is quite frustrating.
> 
> Sorry, the issue I am encountering is likely due to network instability caused by IDC.

This IDC provides a dynamic IP server, so it should be a old problem(network problems when switching IP).

**Comment by athenakia** [comment]
ChatGPT suggests setting DisableKeepAlives in the transport:

```
client.SetTransport(&http.Transport{
	DisableKeepAlives: true,
})
```

It works well.
