### ISSUE TITLE
Support for open-telemetry

### ISSUE THREAD

**Issue by amitpareek2** [go-resty/resty#649]
Hi Team ,

Is there an implementation provided to support Open telemetry traces ?
Below are the list of sdk supported for opentelemetry https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation where Resty name is missing .

Thanks,
Amit

**Comment by dubonzi** [comment]
I have implemented support on https://github.com/dubonzi/otelresty. Its also now listed on their [official registry](https://opentelemetry.io/ecosystem/registry/?s=resty).

**Comment by jeevatkm** [comment]
@dubonzi Thanks for sharing the library reference. You could provide PR with a Readme update with examples and references.
  
@amitpareek2 You could use the library mentioned above.
