### ISSUE TITLE
Interface Panic

### ISSUE THREAD

**Issue by hoc-tiki** [go-resty/resty#651]
receiving a response (I don't know what exactly response from third party), and I've got a panic
So what should I need to avoid this panic. Thank you

Code
```
resty.
		SetDebug(false).
		SetTimeout(1*time.Minute).
		R().
		SetBody(param).
		SetHeader("authorization", <api token>).
		SetResult(&response).
		SetError(&responseErr).
		Post(v1_pathInternalAsaDiscountRefund)
```

Error
```
panic: interface conversion: interface {} is nil, not string
goroutine 2463 [running]:
github.com/go-resty/resty/v2.responseLogger(0xc0001ae960, 0xc00b441d10)
/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/middleware.go:301 +0x75c
github.com/go-resty/resty/v2.(*Client).execute(0xc0001ae960, 0xc00b4511e0)
/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/client.go:972 +0xbe4
github.com/go-resty/resty/v2. (*Request).Execute(0xc00b4511e0,
{0x1150590?, 0xc00b4d95a0?}, {0x117ec20, 0x21})
/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:758 +0x5c5 github.com/go-resty/resty/v2. (*Request). Post(...)
/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:699
```

**Comment by theharveyz** [comment]
I have the same problem, does anyone can fixed it?

**Comment by hoc-tiki** [comment]
Thank for your answer, but why you don't return an error if it's empty. This error makes crashing app

**Comment by Greyh4t** [comment]
> Thank for your answer, but why you don't return an error if it's empty. This error makes crashing app

I am not a developer of resty, I encountered the same problem as you, the reason for this problem is that resty encountered an unexpected assertion, resty needs to fix it

**Comment by jeevatkm** [comment]
@Greyh4t Thanks for the analysis and sample test case. 

@hoc-tiki @Greyh4t I will look into this.

**Comment by jeevatkm** [comment]
@Greyh4t @hoc-tiki I have looked at it. Having too many RWMutex is not good, so I'm going to add the `SetDebug` method at the request level.
