### ISSUE TITLE
Feat: Http request set HTTP headers support http.Header

### ISSUE THREAD

**Issue by bumu** [go-resty/resty#657]
Since golang http lib define the header as `map[string][]string`,  but resty only support `func (r *Request) SetHeaders(headers map[string]string)`

So I think resty is better to support a function like 
```
func (r *Request) SetHTTPHeaders(headers http.Header)
```

reference:
```
type Header map[string][]string
https://github.com/golang/go/blob/master/src/net/http/header.go#L24
```

```
https://github.com/go-resty/resty/blob/master/request.go#L117
```

**Comment by hezean** [comment]
Hi, I feel this function reaches your requirement

https://github.com/go-resty/resty/blob/15cedd4f9ee3df956be40f38fa9b85fb529c8078/request.go#L124-L139

You can use it in this way:
```go
var h http.Header
resp, err := resty.New().R().SetHeaderMultiValues(h).Get(url)
```

**Comment by bumu** [comment]
Yes, can use it that way. 

The difference is the params type.
```
func (r *Request) SetHeaderMultiValues(headers http.Header) *Request 
```

```
func (r *Request) SetHeaderMultiValues(headers map[string][]string) *Request 
```

**Comment by jeevatkm** [comment]
@bumu As @hezean mentioned, you could supply the `http.Header` instance to `SetHeaderMultiValues`; it will work as expected. I will plan to use `http.Header` later on.
