### ISSUE TITLE
[docs] Mentioned example is missing

### ISSUE THREAD

**Issue by elfranne** [go-resty/resty#660]
`resty.Backoff()` is mentioned in the Readme [here](https://github.com/go-resty/resty/blob/15cedd4f9ee3df956be40f38fa9b85fb529c8078/README.md?plain=1#L728) but does not appear in the provided [link](retry_test.go)

**Comment by jeevatkm** [comment]
@elfranne `Backoff` method test cases are indeed present in the `retry_test.go`.
