### ISSUE TITLE
Multiple PreRequestHooks

### ISSUE THREAD

**Issue by rostislaved** [go-resty/resty#665]
I face the same problem as in https://github.com/go-resty/resty/issues/517#issue-1119261088 - I couldn't get not nil raw request.

The only way to get raw request is to use PreRequestHook. But we can have only one hook which will we overwritten if we try to attach the second one like this:
```
client := resty.New().
		SetPreRequestHook(preRequestHook1).
		SetPreRequestHook(preRequestHook2)
```

But having several hooks can be handy. I personally use it to:
1. Add custom auth which requires making hash of the request
2. Printing the final request as a curl (for debug purposes)
3. Can be used to remove headers which are set automatically like user-agent or content-type

That is why I wrote function which acts like this:

```
	client := resty.New().
		SetPreRequestHook(
			And(
				preRequestHook1,
				preRequestHook2,
			),
		)
```

So I want so propose to make it possible to have multiple PreRequestHook objects. That will allow to use resty this way:
 ```
client := resty.New().
		SetPreRequestHook(preRequestHook1).
		SetPreRequestHook(preRequestHook2)
```

**Comment by jeevatkm** [comment]
@rostislaved It was intentionally kept as one prehook.  However, I'm planning to make much improvement in v3.

**Comment by chb0github** [comment]
The vernacular should change from `SetPrerequestHook` to `AddPreRequestHook`. If you intend to stick with this approach, then offer a `CompositePreRequestHook` that take a slice of hooks and returns a singular using a closure

```go
func Compose(hooks ...PreRequestHook) PreRequestHook {
       var errors []error
	return func(c *Client, r *http.Request) error {

		for _, hook := range hooks {
			errors := append(errors,hook(c,r))
		}
		return fmt.ErrorF("%v",errors)
	}
}
```

**Comment by jeevatkm** [comment]
@chb0github There is an upcoming redesign in the middleware chain on request and response on v3.0.0. Current v2 series, I'm planning to keep it as-is.

**Comment by chb0github** [comment]
Looking forward to it
