### ISSUE TITLE
ResponseMiddleware cannot rewrite  response body

### ISSUE THREAD

**Issue by superorange** [go-resty/resty#666]
If an API endpoint returns encrypted data and I need to decrypt the data in the ResponseMiddleware before calling SetResult to process it correctly. How should I implement it now
![image](https://github.com/go-resty/resty/assets/49134865/7ce8a14e-06e6-4e14-81ce-7f734f889b8c)

**Comment by jeevatkm** [comment]
@superorange Currently, you can only process response objects/values via ResponseMiddleware no override/overwrite.

**Comment by jeevatkm** [comment]
@superorange Resty v3 response flow has been redesigned to include additional features. 

It has exported `Response.Body` field
https://github.com/go-resty/resty/blob/9215e71cd392e74551ac99da29458ea5622f372f/response.go#L24

Response body limi reading ability 
https://github.com/go-resty/resty/blob/9215e71cd392e74551ac99da29458ea5622f372f/request.go#L684

Reading response body unlimited times
https://github.com/go-resty/resty/blob/9215e71cd392e74551ac99da29458ea5622f372f/request.go#L699

and much more in Resty v3
