### ISSUE TITLE
TLSHandshakeTimeout issue

### ISSUE THREAD

**Issue by petercheng2023** [go-resty/resty#668]
Is it possible we can configure TLSHandshakeTimeout?
Right now, when we run load test with resty client, sometimes, it will return “[TLS handshake timeout on requesting data concurrently from api]”

**Comment by jeevatkm** [comment]
@petercheng2023 I think you could use custom transport with a more considerable timeout value for `TLSHandshakeTimeout`.

**Comment by jeevatkm** [comment]
In the Resty v3 development, new methods are added to create Resty clients.

This method provides the ability to customize all timeout and config values for the client.
https://github.com/go-resty/resty/blob/0d0bc1b1d873414d17ca6fb4e5240165672dd022/resty.go#L31
