### ISSUE TITLE
Is there anyway to make multipart formdata has order?

### ISSUE THREAD

**Issue by Sczlog** [go-resty/resty#669]
I am working with graphql-upload and it's processor must accept one field before any other fields, otherwise it will throw an error.
I know that map has no order and should has no order, but if there is anyway to make a raw body of multipart and keep its order?

![image](https://github.com/go-resty/resty/assets/29588646/a744b222-64f6-489d-80e9-639fbffb8af6)

**Comment by Sczlog** [comment]
Answer myself for a workaround, use `mime/multipart` to create body, set raw body and content-type will keep the order.

```
var bBody bytes.Buffer
writer := multipart.NewWriter(&bBody)

writer.WriteField("key","value")
part, err := writer.CreateFormFile("fieldname", "filename")
if err != nil {
	return nil, err
}
part.Write([]byte("filecontent"))
writer.Close()
request := c.Client.R()
request.SetHeader("Content-Type", writer.FormDataContentType())
request.SetBody(bBody.Bytes())
resp, err := request.Post("endpoint")
```

**Comment by jeevatkm** [comment]
@Sczlog Thanks for bringing it up and finding a workaround to move forward. I may think of a way to preserve order.

**Comment by praem90** [comment]
Can we add a new method that can accept a slice instead of map and write it to the body in the same order ?

**Comment by chb0github** [comment]
My rant: Go insists that maps don't/can't have order. But that's an implementation issue based on the fact that these are Hash based maps instead of Tree based maps (which are ordered).

What might be a slightly better solution than a slice (just a consideration) - take a sort function. Then it can be by insertion order or actual sort order. 

I don't know what the spec for `mime/multipart` says, but definitely don't deviate from it.

**Comment by jeevatkm** [comment]
@chb0github I hear you!  I will have to check the RFC spec for this part.  

A possible workaround/approach (as @praem90 mentioned above) is to add a method to accept the slice and process it.

**Comment by gospider007** [comment]
> I am working with graphql-upload and it's processor must accept one field before any other fields, otherwise it will throw an error. I know that map has no order and should has no order, but if there is anyway to make a raw body of multipart and keep its order?
> 
> ![image](https://user-images.githubusercontent.com/29588646/247395567-a744b222-64f6-489d-80e9-639fbffb8af6.png)

this can help you:
```go
package main

import (
	"log"
	"strings"

	"github.com/gospider007/requests"
)

func main() {
	orderMap := requests.NewOrderMap()
	orderMap.Set("name", "test")
	orderMap.Set("age", 11)
	orderMap.Set("sex", "boy")

	resp, err := requests.Post(nil, "https://httpbin.org/anything", requests.RequestOption{
		Form: orderMap,
	})
	if err != nil {
		log.Panic(err)
	}
	jsonData, err := resp.Json()
	if err != nil {
		log.Panic(err)
	}
	if !strings.HasPrefix(jsonData.Get("headers.Content-Type").String(), "multipart/form-data") {
		log.Panic("json data error")
	}
	if jsonData.Get("form.name").String() != "test" {
		log.Panic("json data error")
	}
}

```

**Comment by jeevatkm** [comment]
@Sczlog @chb0github @praem90 FYI, the upcoming Resty v3 has methods to achive it. 

For example, the above workaround from this https://github.com/go-resty/resty/issues/669#issuecomment-1600314675 could be transformed in two ways using new methods.

Example 1:
```go
client := resty.New()
defer client.Close()

res, err := c.R().
	SetMultipartOrderedFormData("firstkey", []string{"firstvalue"}).
	SetMultipartOrderedFormData("secondkey", []string{"secondvalue"}).
	SetFile("fieldname", "/path/to/file"). // alternatively, one could use these methods too SetFiles, SetFileReader, SetMultipartField
	Post("/upload")

fmt.Println(err, res)
```

Example 2:
```go
client := resty.New()
defer client.Close()

fields := []*MultipartField{
	{
		Name:   "firstkey",
		Values: []string{"firstvalue"},
	},
	{
		Name:   "secondkey",
		Values: []string{"secondvalue"},
	},
	{
		Name:        "fieldname",
		FilePath:    "/path/to/file",  // alternatively, one could also use MultipartField.Reader too
	},
}

res, err := c.R().
	SetMultipartFields(fields...).
	Post("/upload")

fmt.Println(err, res)
```
