### ISSUE TITLE
How to set Content-Lenght=0 with nil Body?

### ISSUE THREAD

**Issue by lyyyuna** [go-resty/resty#671]
resty v2.7.0
go 1.20

I use the following code to test:

```go
func main() {
	c := resty.New()

	c.SetPreRequestHook(func(c *resty.Client, r *http.Request) error {
		fmt.Println("zzzzzz", r.Body)
		return nil
	})

	c.R().SetContentLength(true).SetBody(nil).Get("http://10.233.32.117:12233")
}
```

I got following on stdout:

```
zzzzz {}
```

It seems that the rawBody is reassigned to `{}`

And I got following on tcpdump:

```
GET / HTTP/1.1
Host: 10.233.32.117:12233
User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
Accept-Encoding: gzip

.....
```

It seems that although I set the `nil` body and `setContentLength=true`，its not working as expected? anything I missed?

**Comment by lyyyuna** [comment]
I also tried `SetBody(nil).Put("http://10.233.32.117:12233")`, the result is same, no `Content-Length: 0` header sent

**Comment by jeevatkm** [comment]
@lyyyuna, I just wanted to confirm my understanding. When `Body is nil and setContentLength=true` the `Content-Length: 0` request header is not getting added, correct?
