### ISSUE TITLE
parseResponseBody overrides original error code in case of unmarshalling error

### ISSUE THREAD

**Issue by dmartinol** [go-resty/resty#673]
If the client has an `Error` object for automatic unmarshalling for the request, and the JSON response cannot be unmarshalled, the current behavior is to override the HTTP response status with a marshalling error like `unexpected end of JSON input`.

Since we cannot lose this information, I suggest to change:
```
                        if res.Request.Error != nil {
                              err = Unmarshalc(c, ct, res.body, res.Request.Error)
                        }

```
to:
```
                        if res.Request.Error != nil {
                              unmarshalErr := Unmarshalc(c, ct, res.body, res.Request.Error)
                              if unmarshalErr != nil {
                                      log.Printf("Failed to unmarshal response body: %s", unmarshalErr)
                              }
                        }
```
This way we'll miss the unmarshalling error but at least we can handle the server response status.

Maybe there's a better way to report the error, but I haven't found anyone ATM, please suggest an alternative if any.

**Comment by renathoaz** [comment]
@dmartinol ,@jeevatkm  I would like to propose a change from:
```
func (r *Response) fmtBodyString(sl int64) string {
	if r.body != nil  {
		if int64(len(r.body)) > sl {
...
```
Actual: Here we can see there's nothing in body, maybe empty string? but Content-Type is application/json; charset=utf-8

![Seleção_034](https://github.com/go-resty/resty/assets/16307350/e20ac898-d455-4382-b863-6f9702ede7fd)

to:

```
func (r *Response) fmtBodyString(sl int64) string {
	if r.body != nil && len(r.body) > 0 {
		if int64(len(r.body)) > sl {
...
```
After this small change everything is fine now:

![Seleção_033](https://github.com/go-resty/resty/assets/16307350/28d77567-a164-4686-a868-2be7ff5b057f)

I was implementing one client and the server is probably with issue in one of the routes that sends 201 and body is empty but r.body is getting initialized somehow although its length is 0. Maybe empty string is coming from server. 
It also affects `SetResult()`, maybe a check in `parseResponseBody` is also needed to prevent error from unmarshalling empty []byte{}.

**Comment by dmartinol** [comment]
Hi,
for some reason I cannot see the comment on gitHub so I reply via email.

The change you requested has been integrated.

Thanks,
Daniele
