### ISSUE TITLE
Post "http://xx:9000/mq/order/create": read tcp xx:37158->xx:9000: read: connection reset by peer

### ISSUE THREAD

**Issue by ckall** [go-resty/resty#676]
Request error: read: connection reset by peer

**Comment by ManuelReschke** [comment]
This error has nothing to do with resty.

**Comment by ckall** [comment]
May I ask how to solve this problem

**Comment by jeevatkm** [comment]
@ckall As @ManuelReschke mentioned is to related Resty, thanks.
