### ISSUE TITLE
Example for JSON handling

### ISSUE THREAD

**Issue by yellowiscool** [go-resty/resty#68]
Hi,

An example showing how to get the JSON document from a GET request could be nice to have in the README. I had to search in the source code to see that I should use `resp.Request.Result`

**Comment by yellowiscool** [comment]
Well, actually `Request.Result` is nil, so it doesn't seem to work.

**Comment by jeevatkm** [comment]
If I understand correctly, you would like to use Automatic Unmarshal feature for Response.

You have to use [Request.SetResult()](https://godoc.org/gopkg.in/resty.v0#Request.SetResult) and [Response.Result()](https://godoc.org/gopkg.in/resty.v0#Response.Result).

If you have error scenario then -
You can use [Request.SetError()](https://godoc.org/gopkg.in/resty.v0#Request.SetError) and [Response.Error()](https://godoc.org/gopkg.in/resty.v0#Response.Error).

Please refer this - 
* Success scenario: [Test case](https://github.com/go-resty/resty/blob/master/resty_test.go#L197)
* Error scenario: [Test case](https://github.com/go-resty/resty/blob/master/resty_test.go#L218)

_PS: Yes, you're correct it's to good have an example on Readme, would you like to send PR for README?_

**Comment by jeevatkm** [comment]
@yellowiscool I hope you have sorted out with above reference, please let me know.

**Comment by yellowiscool** [comment]
Hei, I didn't know about `Request.SetResult()` so I implemented the unmarshal myself. Thanks for the explanation though, I will use it the next time I should implement something using Resty.

**Comment by jeevatkm** [comment]
Glad to hear. Thanks.
