### ISSUE TITLE
Why is there no more release or tag?

### ISSUE THREAD

**Issue by dayeguilaiye** [go-resty/resty#682]
I found last release was from 2021, and many changes happened during those years.
For me, patch method not support multipart in v2.7.0, but I found it was fixed in main branch.

Can anyone tell me the reason, and how to get the newest version?
Thanks a lot!

**Comment by jeevatkm** [comment]
@dayeguilaiye It is a delay at my end. I'm going to wrap up the v2.8.0 in a day or two for sure.

**Comment by dayeguilaiye** [comment]
Thanks for your reply! 

I'd like to leave this issue open in case any one has the same question, feel free to close if you think it's better.

**Comment by jeevatkm** [comment]
No worries; so that you know, I'm in the process of making a release v2.8.0. Thanks.

**Comment by jeevatkm** [comment]
v2.8.0 is released! 🎉
