### ISSUE TITLE
Why TLS Timeout error can't be handle by Retries ?

### ISSUE THREAD

**Issue by alexwbaule** [go-resty/resty#689]
Hello !

I'm testing the retry feature and the URL that I am requesting is taking too long to be made and the retry its not used because the error is a tlstimeout.

Is there  a way to force retry on tls timeout ? 

Tks.

**Comment by jeevatkm** [comment]
@alexwbaule I'm not sure; I understand your question. Can you provide details?

**Comment by alexwbaule** [comment]
Hi @jeevatkm 

Sorry, i got the error.

On TLS timeout, the "statusCode" is not setted. The response is `nil`.

Im using the `AddRetryCondition` checking for http.StatusRequestTimeout or http.StatusGatewayTimeout, but on TLS timeout is not setted, but the error is http.tlsHandshakeTimeoutError{}, need to check for this in error too.

Tks , and my bad.!
