### ISSUE TITLE
SetRetryWaitTime is undefined

### ISSUE THREAD

**Issue by ideahitme** [go-resty/resty#72]
Readme file mentions that it is possible to define a wait time for retries, however `resty.v0` version `c45c7bcc0000d1a9ac1b119b2e6043c6540eedea` does not expose the method: 

```
	c := resty.New().SetRetryCount(3).SetHostURL(s.URL).AddRetryCondition(func(r *resty.Response) (bool, error) {
		// if r.StatusCode() <= 300 {
		// 	return false, nil
		// }

		return false, nil
	}).SetRetryWaitTime(5*time.Second) // <- undefined 
```

Probably documentation is outdated. What is the best way to implement this (e.g. adding time.Sleep into `AddRetryFunc` ?

**Comment by jeevatkm** [comment]
@ideahitme  This feature is available on master `github.com/go-resty/resty`. It is not yet released on `gopkg.in/resty.v0`.

**Comment by jeevatkm** [comment]
Closing this since `v0.12` is getting released.

**Comment by ideahitme** [comment]
thanks a lot 👍

**Comment by jeevatkm** [comment]
You're welcome.
