### ISSUE TITLE
Request body is written multiple times

### ISSUE THREAD

**Issue by patrikeh** [go-resty/resty#743]
In v2.10.0, I've observed an issue where the request body passed to `.SetBody(...)` is intermittently written multiple times under certain conditions.

From what I gather, it is somehow related to the retry mechanism, or at the very least I was only able to reproduce by triggering that.

[In the repro here](https://github.com/patrikeh/resty-request-body-issue), I ping an httptest mock endpoint triggering the retry mechanism, and observe the JSON request body being written multiple consecutive times e.g. 
```
{ <some-json> }{ <some-json> }
```

This issue does not occur in v2.9.1.

**Comment by iporer** [comment]
My projcet recurred this bug. Hope fix.

**Comment by lattwood** [comment]
@patrikeh thanks for throwing that test case together, really helped with tracking the issue down
