### ISSUE TITLE
memory leak when response is too large

### ISSUE THREAD

**Issue by royalraul** [go-resty/resty#751]
<img width="1010" alt="image" src="https://github.com/go-resty/resty/assets/7909621/e1e851a8-4dd2-443d-8c04-fc0d19ad8817">
using go-resty, where response body is too large, the memory usage is increasing gradually, I find 'if response.body, err = io.ReadAll(body); err != nil' may be the cause. could it be changed using ‘io.copy’ or other way.

**Comment by jeevatkm** [comment]
@john-behm-bertelsmann Thanks for your response.

@royalraul For the large response body size, it is recommended to take control on your end, since its not a typical JSON or XML or Text.
https://pkg.go.dev/github.com/go-resty/resty/v2#Request.SetDoNotParseResponse
