### ISSUE TITLE
SetRetryCount() on request?

### ISSUE THREAD

**Issue by arvenil** [go-resty/resty#752]
I know that I can add retry conditions per request with `client.R().AddRetryCondition()`, however there are other request on that client that I don't want to be retried. How this can be achieved?

Currently if I just add retry conditions on request, then nothing happens unless I also set retry count on client with `SetRetryCount(n)`. That however means other requests, that I don't want to be retried - will be retried.

**Comment by jeevatkm** [comment]
@arvenil Thanks for reaching out. I will add it to the v3.
