### ISSUE TITLE
Call to http.DetectContentType has trailing NUL bytes in buffer

### ISSUE THREAD

**Issue by internetisalie** [go-resty/resty#754]
In [`writeMultipartFormFile`](https://github.com/go-resty/resty/blob/v2/util.go#L211), the call to `http.DetectContentType` is passed a buffer with potentially trailing `0` bytes.  As a result, `text/plain` is never detected in such cases.

`cbuf` should be trimmed to `size` to ensure `text/plain` is property detected:

```go
// Auto detect actual multipart content type
cbuf := make([]byte, 512)
size, err := r.Read(cbuf)
if err != nil && err != io.EOF {
  return err
}

partWriter, err := w.CreatePart(createMultipartHeader(fieldName, fileName, http.DetectContentType(cbuf[:size])))
if err != nil {
  return err
}
```

**Comment by jeevatkm** [comment]
@internetisalie Thanks for reporting it. I'm sorry for the delayed response.

It is addressed and will be part of the v2.12.0 release.
