### ISSUE TITLE
Brotli support

### ISSUE THREAD

**Issue by AsyncAlchemist** [go-resty/resty#759]
I would like to request that support for Brotli compression be added. There is a very good library from github.com/andybalholm/brotli that implements native Brotli compression/decompression in Go, so it's really only a few lines of code.

Brotli is quickly replacing gzip as the go-to compression standard for text-based responses (html,json,css,etc).

If you feel this could be useful, I'm happy to help. Feel free to assign me the issue and I will try to implement it.

**Comment by jeevatkm** [comment]
@AsyncAlchemist, as of now, Go still needs to add Brotli support. I will provide mechanism/interface to add external compression library in the v3.
