### ISSUE TITLE
Suggestion to change json parser in order to improve performance

### ISSUE THREAD

**Issue by ZandorZ** [go-resty/resty#76]
Instead of using standard encoding/json, maybe use another  like https://github.com/json-iterator/go

**Comment by jeevatkm** [comment]
Thank you for your suggestion. I will have a look.

**Comment by jeevatkm** [comment]
@ZandorZ I have done my analysis.  

[json-iterator](https://github.com/json-iterator/go) supports all three compliant methods
- `Marshal(v interface{}) ([]byte, error)`
- `Unmarshal(data []byte, v interface{}) error`
- `MarshalIndent(v interface{}, prefix, indent string) ([]byte, error)`

There are other two candid libraries are available:

[ffjson](https://github.com/pquerna/ffjson) supports two compliant methods
- `Marshal(v interface{}) ([]byte, error)`
- `Unmarshal(data []byte, v interface{}) error`

[easyjson](https://github.com/mailru/easyjson) but this one is doesn't support drop-in replacement, so out-of-choice.

So, following is my design choice/approach:
- By default use standard `encoding/json` package in `resty`
- Expose option to register developer choice of JSON library into `resty`

I will give it try on the implementation and will post the outcome.

Do you have any suggestions?

**Comment by jeevatkm** [comment]
I have implemented above mentioned design e62101851570b1515c675672a9daa29887cedcf0, it is not yet merged to master.

**Comment by ZandorZ** [comment]
@jeevatkm Good idea!

**Comment by jeevatkm** [comment]
Merging e62101851570b1515c675672a9daa29887cedcf0 into master.

**Comment by jeevatkm** [comment]
Merged to master
