### ISSUE TITLE
How to handle response if a call to API returns 200 with struct A, or 201 with struct B?

### ISSUE THREAD

**Issue by arvenil** [go-resty/resty#761]
Hi,

I have a bit strange API to handle. POST to the endpoint usually returns 201 with created resource, but if resource already exists it will return 200 and an array with that specific resource. This means depending on status code I receive different payload - how this can be handled?

**Comment by lfrestrepog** [comment]
Hi.
Can you elaborate on the difficulty? From your description it sounds like a switch on the status code should do. Without more context I'd suggest something like:

```go
	switch r.StatusCode() {
	case 200:
		return handleUpdatedCase(r)
	case 201:
		return handleCreatedCase(r)
	default:
		return handleError(r)
	}

```

**Comment by alexhung** [comment]
If you are using automarshalling then you need to switch it off with `SetDoNotParseResponse()` then roll your own base on the status code per @lfrestrepog suggestion.

**Comment by jeevatkm** [comment]
@arvenil Please go with combined suggestions from @alexhung & @lfrestrepog. 

Also, in v3, I plan to improve response handling; Resty will possibly have out-of-the-box handling in this scenario.

**Comment by jeevatkm** [comment]
@arvenil FYI, the upcoming Resty v3, by this PR #902, brings an ability to control result or error struct based on status code or any other logic.

For example, something like this can be done - 

```go
client := resty.New()
defer client.Close()

resultByStatusCodeMiddleware := func(c *Client, res *Response) error {
	// Ideally in Resty v3 response middlewares should check error
	// before doing any processing, I'm ignoring this since, per 
	// below example, this middleware is the first one.
	// if res.Err != nil {
	// 	return nil
	// }

	switch res.StatusCode() {
	case 200:
		res.Request.SetResult(&StructA{})
	case 201:
		res.Request.SetResult(&StructB{})
	default:
		// you can set SetError too, any other logic
	}
	return nil
}

client.SetResponseMiddlewares(
	resultByStatusCodeMiddleware,
	resty.AutoParseResponseMiddleware, // before this, the body is not read by Resty except on debug flow
	resty.SaveToFileResponseMiddleware, // See, Request.SetOutputFile
)
```
