### ISSUE TITLE
SetProxy

### ISSUE THREAD

**Issue by daijun168** [go-resty/resty#765]
What if the agent needs to verify the username and password

**Comment by chrisfeng0723** [comment]
like this:
client.SetProxy(http://{proxy_username}:{proxy_password}@{proxy_host}:{proxy_port})

**Comment by chrisfeng0723** [comment]
proxy_username and proxy_password need url.QueryEscape

**Comment by jeevatkm** [comment]
Thanks, @chrisfeng0723, for responding to the question.
