### ISSUE TITLE
cache middleware

### ISSUE THREAD

**Issue by laggu** [go-resty/resty#776]
Is there anyway to make a caching middleware?

I hope to make a response middleware that cache response with some special key
and request middleware that get response from cache and skip the http request

is this possible??

**Comment by jeevatkm** [comment]
@laggu You could build that using `OnBeforeRequest` and `OnAfterResponse` middleware.

**Comment by laggu** [comment]
@jeevatkm OnBeforeRequest only have request with argument.
I need to access response with OnBeforeRequest and stop request without error

How to stop request on OnBeforeRequest and return response with cached data??

**Comment by jeevatkm** [comment]
@laggu I'm not sure this could help, maybe give it try.
You could create a cache layer (pick any good cache library). Then you could access that cache instance in `OnAfterResponse` to add the response to the cache; then before you fire the resty request, check your cache and to use it.

**Comment by laggu** [comment]
@jeevatkm I think caching api result is a common requirement for software
Would you have any plan for support this feature?
Support by middleware will be perfect, but adding function like retry is fine

**Comment by FarmerChillax** [comment]
I also have similar demands
