### ISSUE TITLE
Can it support socket5 proxy?

### ISSUE THREAD

**Issue by erosiners** [go-resty/resty#786]
Can it support socket5 proxy? I found that it can only support http proxy.

**Comment by jeevatkm** [comment]
@erosiners It seems Go has the socks5 dialer here https://pkg.go.dev/golang.org/x/net/proxy. I will schedule this with v3.

**Comment by jeevatkm** [comment]
@erosiners, I just validated the Go documentation; it seems the socks5 proxy is already supported out-of-the-box.


```go
client := resty.New().SetProxy("socks5://127.0.0.1:1080/")
```

I will update the godoc.
