### ISSUE TITLE
Resty retry function does not work in Slack as custom http client

### ISSUE THREAD

**Issue by rts-gordon** [go-resty/resty#787]
My program send message to Slack channel via [slack-go](https://github.com/slack-go/slack), I used a Resty as a custom http client and set it retry 3 times, but the retry function does not work with slack-go.

I changed to another http client [retryablehttp](https://github.com/hashicorp/go-retryablehttp), the retry function works well with slack-go.

slack-go code:
```
// transfor resty.Client to http.Client
httpClient = InitHttpClient().GetClient()
slack.PostWebhookCustomHTTP(url, httpClient, &msg)

```

Resty httpClient:
```
func InitHttpClient() *resty.Client {
	return resty.New().
		SetRetryCount(3).
		SetRetryWaitTime(1 * time.Second).
		SetRetryMaxWaitTime(20 * time.Second)
}

```

I studied retryablehttp code found that [StandardClient ](https://github.com/hashicorp/go-retryablehttp/blob/main/client.go#L843) returns a stdlib *http.Client with a custom Transport, which shims in a *retryablehttp.Client for added retries.  But [resty.GetClient](https://github.com/go-resty/resty/blob/v2/client.go#L1124)  just return c.httpClient, can resty.GetClient implement the same retry function? thank you.

Versions
Go: v1.22
slack-go/slack: v0.12.5
Resty: v2.12.0
retryablehttp: v0.7.5

**Comment by jeevatkm** [comment]
@rts-gordon Thanks for reaching out. If I recall correctly, `resty.GetClient` is the underlying Go HTTP client instance returned as-is. The returned client does not accommodate all the Resty feature(s) today.

Can you fork the Resty, add the implementation, and test it? If it works as-is, you could submit a PR. Otherwise, I will consider it part of the v3 design.

**Comment by rts-gordon** [comment]
@jeevatkm 
 Maybe we can implement this in v3. Thanks.
