### ISSUE TITLE
Support for POST with "Content-Type", "application/x-www-form-urlencoded" with data urlencoded

### ISSUE THREAD

**Issue by etsangsplk** [go-resty/resty#79]
It does not seem to support support for POST with "Content-Type", "application/x-www-form-urlencoded. We can set the header but the data is not url encoded

Example:
https://github.com/go-resty/resty/blob/master/request.go#L134
There is no data.Encode() at the end.

Is there another thing I have to set or it is missing?

**Comment by jeevatkm** [comment]
`resty` does support Content-Type `application/x-www-form-urlencoded` aka form data. Encode happens at [middleware#L332](https://github.com/go-resty/resty/blob/master/middleware.go#L332).

Have you tested it? If yes then please provide sample program to reproduce the issue.

Refer to these test case [TestFormData](https://github.com/go-resty/resty/blob/master/resty_test.go#L449) and [TestMultiValueFormData](https://github.com/go-resty/resty/blob/master/resty_test.go#L469).

**Comment by etsangsplk** [comment]
I am using it as a client level not as server middleware

**Comment by jeevatkm** [comment]
This is not a server middleware. This is `resty` middleware.

Typical usage of `SetFormData` as follows:

- Use `resty.SetFormData` for fields which needs to be sent for all request. Which is global
- Use `resty.R().SetFormData` for fields which needs to be sent for particular request. Also you can override field values of client level.

Encode happens in both cases, when request is created from `resty`.

**Comment by etsangsplk** [comment]
I don't know what's the difference between resty and the raw http client approaches. But I get that working using the raw http client, but it is much less nice if I can use resty.
	
```type result struct {
		TokenType   string `json:"token_type"`
		Exp         int    `json:"expires_in"`
		AccessToken string `json:"access_token"`
	}

	tokUrl := SomeURL here

	data := url.Values{}
	data.Set("grant_type", "password")
	data.Add("username", username)
	data.Add("password", password)

	r, _ := http.NewRequest("POST", tokUrl, bytes.NewBufferString(data.Encode()))
	r.Header.Add("Content-Type", "application/x-www-form-urlencoded")
	r.Header.Add("Cache-Control", "no-cache")
	r.Header.Add("Content-Length", strconv.Itoa(len(data.Encode())))

	var resp *http.Response
	client := &http.Client{}
	resp, err = client.Do(r)
```

**Comment by jeevatkm** [comment]
Can you please try following code and share your debug output?

```go
func main() {
	// Enabling debug
	resty.SetDebug(true)

	// Sets `Content-Length` header automatically
	resty.SetContentLength(true)

	tokURL := ""
	username := ""
	password := ""

	// resty will set content-type to `application/x-www-form-urlencoded`
        // automatically
	resp, err := resty.R().
		SetFormData(map[string]string{
			"grant_type": "password",
			"username":   username,
			"password":   password,
		}).
		SetHeader("Cache-Control", "no-cache").
		Post(tokURL)

	fmt.Println(err, resp)
}
```

_Tip: Use client side settings only if you want have dedicated client for specific purpose, otherwise just use resty.R()..._

**Comment by jeevatkm** [comment]
@etsangsplk did you get a chance to try above code snippet?

**Comment by etsangsplk** [comment]
yup it worked. It is the extra "Content-Type":  "application/x-www-form-urlencoded" I had that's causing the issue. Thanks

**Comment by etsangsplk** [comment]
I do have another question of SetTimeout(time.Duration(time.Duration(timeoutInSec) * time.Second)). ... in resty.. so it will abort and also clean up all the resources (connection, buffers etc etc) on expiry..  What resources are cleaned up?

**Comment by jeevatkm** [comment]
Thanks for the updates. I will place the check of content-type check.

Yes it aborts the request. Connection goes to pool (done by golang), bytes buffer goes pack to pool (done resty), other references are ready for GC. 

Currently `resty` provides high performance with very low footprint. However in the upcoming releases I will be adding further object pool support to improve performance, less allocations and less GC.
