### ISSUE TITLE
How to modify response body OnAfterResponse?

### ISSUE THREAD

**Issue by panyox** [go-resty/resty#802]
```golang
rc := resty.New()
rc.OnAfterResponse(func(c *resty.Client, r *resty.Response) error {
		// eg: in here, i want to modify response body
                 if r.StatusCode() == 403 {
                     // how can i change body to other content
                 }
		return nil
	})
```

**Comment by jeevatkm** [comment]
In Resty v2, only you could make use of [Response.SetBody](https://pkg.go.dev/github.com/go-resty/resty/v2#Response.SetBody).

In the upcoming Resty v3, a more natural way to do it is via `Response.Body` see this reference
https://github.com/go-resty/resty/blob/8471a1a19657bc63062ae8543f6d0c6c111206e9/response.go#L25
