### ISSUE TITLE
context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by tocha688** [go-resty/resty#806]
I'm stuck when I request, and when I add a timeout, I get an error. I'm sure there's no problem with the link, and the browser can open normally, but I can't simulate the http request. I'm not sure what the problem is.
```
p.Client.SetTimeout(time.Duration(30 * time.Second))
```
```
2024/07/24 13:23:44.640781 WARN RESTY Get "https://portswigger.net/users/youraccount/personaldetails": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
2024/07/24 13:24:14.751400 WARN RESTY Get "https://portswigger.net/users/youraccount/personaldetails": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2
2024/07/24 13:24:14.751400 ERROR RESTY Get "https://portswigger.net/users/youraccount/personaldetails": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by tocha688** [comment]
```
2024/07/24 13:39:01.621035 WARN RESTY Get "https://portswigger.net/users/youraccount/personaldetails": http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=COMPRESSION_ERROR, debug="", Attempt 1
```
He also has this error, is it because of http2, if so, how can I specify that he use http1.1 instead of trying http2

**Comment by jeevatkm** [comment]
@tocha688 The underlying Go HTTP client could handle HTTP/2 and HTTP/1.1 transparently based on the server-supported version, so specifying explicitly is not required.

Based on the error message, it seems that it is timing out while the reader headers from the server are being read. So try increasing the timeout value. There is also a possibility of an upstream server issue.

**Comment by jgbooks** [comment]
When the network is down, setting timeouts in resty is ineffective as the request will be stuck and unable to return.

**Comment by tocha688** [comment]
This is caused by duplicate cookies in the cookie, I think it can be avoided
```
a=1;a=1;a=1;
```
