### ISSUE TITLE
How to set tls fingerprint

### ISSUE THREAD

**Issue by tocha688** [go-resty/resty#807]
How to set the fingerprint of tls, like this library, set tls as the browser fingerprint. Many websites detect tls interception simulation requests
https://github.com/bogdanfinn/tls-client

**Comment by ahuigo** [comment]
I've written some examples before in [PR728](https://github.com/go-resty/resty/pull/728)

- Custom transport: https://github.com/ahuigo/resty/blob/examples-v2/examples/transport_test.go
- Custom tls config:  https://github.com/ahuigo/resty/blob/examples-v2/examples/ssl_test.go
- ...

**Comment by tocha688** [comment]
I mean setting TLS request fingerprint, ja3, ja4 verification, modifying some request features of tls, so as to fully simulate the browser request process

**Comment by tttturtle-russ** [comment]
There are implementations for this.
- https://github.com/juzeon/spoofed-round-tripper
- https://github.com/imroc/req

**Comment by jeevatkm** [comment]
@tttturtle-russ Thanks for adding a reference.

@tocha688 Please look at the example of Resty usage with [spoofed-round-tripper](https://github.com/juzeon/spoofed-round-tripper)
https://github.com/juzeon/spoofed-round-tripper?tab=readme-ov-file#usage
