### ISSUE TITLE
Client: Add Read-Write Mutex to struct to make all the client properties thread-safe

### ISSUE THREAD

**Issue by jeevatkm** [go-resty/resty#812]
All the exported fields will become getter methods, 

e.g., `client.BaseURL => client.BaseURL()`

**Comment by tttturtle-russ** [comment]
In this case, all the setter method should also be protected by the rw mutex right?
I write a simple demo as follows:
```
// Cookies method gets all cookies in the client instance.
// It uses a Read-Write mutex to make itself thread-safe.
func (c *Client) Cookies() []*http.Cookie {
	c.mutex.RLock()
	defer c.mutex.RUnlock()
	return c.cookies
}

// SetCookies method sets an array of cookies in the client instance.
// These cookies will be added to all the request raised from this client instance.
//
//	cookies := []*http.Cookie{
//		&http.Cookie{
//			Name:"go-resty-1",
//			Value:"This is cookie 1 value",
//		},
//		&http.Cookie{
//			Name:"go-resty-2",
//			Value:"This is cookie 2 value",
//		},
//	}
//
//	// Setting a cookies into resty
//	client.SetCookies(cookies)
func (c *Client) SetCookies(cs []*http.Cookie) *Client {
	c.mutex.Lock()
	c.cookies = append(c.cookies, cs...)
	c.mutex.Unlock()
	return c
}
```

**Comment by jeevatkm** [comment]
@tttturtle-russ, your understanding is correct. This is for Resty v3.

**Comment by tttturtle-russ** [comment]
@jeevatkm I can help with this.  Actually, I add the lock to some methods, such as `SetQueryParams`. However, it ends up failing the retry test. I tested 5 times, and it only succeeded once and passed all the tests. Maybe the lock introduced extra time consumption.

**Comment by jeevatkm** [comment]
@tttturtle-russ You're welcome to create a PR for v3. With Mutex, some of the tests may need to be rewritten or updated.
