### ISSUE TITLE
max reponse body limit

### ISSUE THREAD

**Issue by trim21** [go-resty/resty#819]
go-resty will read all response in to memory, is it possible to set a max body limit?

I can send a PR if you are open to this feature.

**Comment by jeevatkm** [comment]
@trim21 On the response body, the [user can take control](https://pkg.go.dev/github.com/go-resty/resty/v2#Client.SetDoNotParseResponse) from Resty and handle the read response body. 

In the upcoming [Resty v3](https://github.com/go-resty/resty/milestone/34), I will resolve the request body with a progress reading approach. 

Of course, you could create a PR with the solution you have in your mind. We can review it.

**Comment by trim21** [comment]
> @trim21 On the response body, the [user can take control](https://pkg.go.dev/github.com/go-resty/resty/v2#Client.SetDoNotParseResponse) from Resty and handle the read response body.
> 
> In the upcoming [Resty v3](https://github.com/go-resty/resty/milestone/34), I will resolve the request body with a progress reading approach.
> 
> Of course, you could create a PR with the solution you have in your mind. We can review it.

please review https://github.com/go-resty/resty/pull/830
