### ISSUE TITLE
bzlmod No dependencies were provided. util_curl.go

### ISSUE THREAD

**Issue by brounnoupegreula-7757** [go-resty/resty#825]
hi guys i try to add resty inside my bazel project its using bzlmod but i got this error

![image](https://github.com/user-attachments/assets/45f61f99-b96b-41bf-82ec-a021f9d624d2)

```
bazel_dep(name = "rules_go", version = "0.49.0")
bazel_dep(name = "gazelle", version = "0.38.0")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.22.6")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
use_repo(go_deps, "com_github_bytedance_sonic")
use_repo(go_deps, "com_github_go_resty_resty_v2")
```

**Comment by jeevatkm** [comment]
@brounnoupegreula-7757 I do not know much about Bazel. Please refer to this file https://github.com/go-resty/resty/blob/v2/BUILD.bazel

**Comment by jeevatkm** [comment]
@brounnoupegreula-7757 Any update?

**Comment by frank30941** [comment]
@brounnoupegreula-7757 Hi, below is my solution, and I use gazelle.
``` starlark
go_deps.gazelle_override(
    path = "github.com/go-resty/resty/v2",
)
```

**Comment by jeevatkm** [comment]
@frank30941 Where should we add this line? In `BUILD.bazel`??

**Comment by frank30941** [comment]
@jeevatkm I think you may follow up below steps. then you will see some BUILD.bazel changed.
``` shell
 # 1.
brew install bazelisk
# or
go install github.com/bazelbuild/bazelisk@latest

# 2. in project path
bazelisk run gazelle
# or
go install github.com/bazelbuild/bazel-gazelle/cmd/gazelle@latest
gazelle
```

**Comment by frank30941** [comment]
@jeevatkm Hi, I have a pr for you #833

**Comment by jeevatkm** [comment]
PR #833 merged!
