### ISSUE TITLE
SetDoNotParseResponse(true) prevents debug logs from printing

### ISSUE THREAD

**Issue by kon3gor** [go-resty/resty#829]
When using SetDoNotParseResponse(~~false~~ true) together with SetDebug(true) there is not request/response log at all. 

I believe there are two reasons for this:
1. Request log is not printed immediately, but saved and printed only after response is received via logging middleware. 
2. Response middleware is only applied **if the response has been automatically parsed**, otherwise it is not.

Together, these two details result in complete absence of request/response logs when using SetDoNotParseResponse(~~false~~ true) and  SetDebug(true) together.

**I'm willing to fix this issue myself. PR will be ready on Friday if someone from the core team approves the change**

**Comment by kon3gor** [comment]
Some links to the code:
- [No printing for request log](https://github.com/go-resty/resty/blob/v2/middleware.go#L352)
- [Printing request log only with response log](https://github.com/go-resty/resty/blob/v2/middleware.go#L371)
- [No middleware if DoNotParseResponse is set](https://github.com/go-resty/resty/blob/v2/client.go#L1220)

**Comment by jeevatkm** [comment]
@kon3gor I'm unable to follow your issue description. The default value is `false` for SetDoNotParseResponse. Did you mean `true`?

If the user sets SetDoNotParseResponse to `true`, then Resty doesn't log request debug info. Please let me know if you meant this.

Also, the request and response logs are combined before logging to provide complete roundtrip details for debugging, which is better than scattering the debug log of request and response.

**Comment by kon3gor** [comment]
@jeevatkm ohh, yes, my bad, I meant `true`. 

> Also, the request and response logs are combined before logging to provide complete roundtrip details for debugging, which is better than scattering the debug log of request and response.

In this case, I think there are two solutions to this issue: 
- Apply response middleware even if response is not parsed. 
- Use response logging not through middleware, but by directly calling it [(as it already is for request logging)](https://github.com/go-resty/resty/blob/v2/client.go#L1197).

**Comment by kon3gor** [comment]
@jeevatkm Yes, I would be happy to help!

**Comment by jeevatkm** [comment]
PR merged yesterday.
