### ISSUE TITLE
How to force http1.1

### ISSUE THREAD

**Issue by tocha688** [go-resty/resty#831]
How to force http1.1

**Comment by jeevatkm** [comment]
@tocha688 Maybe you could set an environment variable to disable HTTP/2.

```
GODEBUG=http2client=0
```
OR
As I mentioned in the previous comment, you could create a client and supply it to Resty.
```go
customClient := &http.Client{
      Transport: &http.Transport{
         TLSNextProto: map[string]func(string, *tls.Conn)http.RoundTripper{},
      },
   }

restyClient := resty. NewWithClient(customClient)
```

Reference: https://stackoverflow.com/a/67775105
