### ISSUE TITLE
how to disable request log with REQUEST(curl) when set debug to true

### ISSUE THREAD

**Issue by BoneAsh** [go-resty/resty#834]
I need to PUT request with large body as upload file， debug logger request body by "Body: r.fmtBodyString(c.debugBodySizeLimit)" ， it will logger fmt.Sprintf("***** REQUEST TOO LARGE (size - %d) *****", bodySize) where body is too large, but REQUEST(curl) will logger full body.

**Comment by jeevatkm** [comment]
@BoneAsh Thanks for reaching out. CURL command logging requires the entire body. However, it can be a bad experience for users who only need debug logging. 

I'm planning to implement another option as part of #828 to separate it like this -
* Debug log (same as before the CURL command feature was added)
* Debug log with CURL command log enabled

**Comment by jeevatkm** [comment]
@BoneAsh, I have merged the PR to fix #828; you can pin the branch version for now.

**Comment by BoneAsh** [comment]
> @BoneAsh, I have merged the PR to fix #828; you can pin the branch version for now.

ok, i will try

**Comment by BoneAsh** [comment]
yeah, the generateCurlOnDebug flag is useful, I will close this issue, thank you @jeevatkm
