### ISSUE TITLE
Support HTTP3?

### ISSUE THREAD

**Issue by tttturtle-russ** [go-resty/resty#846]
It seems that resty v2 does not support HTTP3/QUIC. Are there any plans to support in v3?

**Comment by jeevatkm** [comment]
HTTP/3 can be used in Resty using the library https://github.com/quic-go/quic-go with https://pkg.go.dev/github.com/go-resty/resty/v2#Client.SetTransport

```go
roundTripper := &http3.RoundTripper{
	TLSClientConfig: &tls.Config{},  // set a TLS client config, if desired
	QUICConfig:      &quic.Config{}, // QUIC connection options
}
defer roundTripper.Close()

restyClient := resty.New().SetTransport(roundTripper)
```
Reference: https://quic-go.net/docs/http3/client/
