### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by perdasilva** [go-resty/resty#85]
Hi,

Is it possible to stream the HTTP response?

Thanks in advance =)

**Comment by jeevatkm** [comment]
@perdasilva I'm sorry, I didn't get your question. Could you please describe your use case?

**Comment by perdasilva** [comment]
Hi,

Yeah, I want to stream the response to stdout as it comes in. From what I've tried, it seems the request blocks until the whole response is downloaded.

Basically, I would like to do this:

reader := bufio.NewReader(resp.Body)
for {
	line, err := reader.ReadBytes('\n')
	if err != nil {
		break
	}
	log.Print(string(line))
}

I've tried using Response.RawResponse.Body, but that didn't work for me.

Thanks for getting back so quickly!!

**Comment by jeevatkm** [comment]
You're correct. Resty reads the complete response and then returns to caller at once. Refer to [Line#722](https://github.com/go-resty/resty/blob/master/client.go#L722).

I can bring this feature in the upcoming release.

----

If you want save HTTP response as a file use https://godoc.org/github.com/go-resty/resty#Request.SetOutput

**Comment by perdasilva** [comment]
Hi,

Thanks for the reply.

What I would to do is print the response as it comes, instead of buffering the entire thing then printing. Would this be at all possible?

Basically I'm initiating a process on the server, which returns a log of what's going on - and I would like to see it as it comes through the pipe ^^

Cheers!!

**Comment by jeevatkm** [comment]
@perdasilva Currently this feature is not exists in `resty`. To achieve this resty have to be provide response reader to caller without reading a response.

If you're interested, create an issue for me "Expose response reader without reading response". Then I will think about the design and share it with you.

Once we are satisfied, I will implement it in resty. Sounds good?

**Comment by perdasilva** [comment]
Sounds like a plan! I've created the issue =D

ty!!
