### ISSUE TITLE
Is it possible to merge SetResult() with ForceContentType("application/json") into a single method

### ISSUE THREAD

**Issue by Snax1210** [go-resty/resty#850]
The original intention of using SetResult() is to convert the response into a struct, but sometimes the response header is not "application/json", and you need to add ForceContentType(" application/json") separately

**Comment by jeevatkm** [comment]
I do not understand about 
> into a single method

But if you're asking whether it can be used together in the request chain, then yes, you can.


Example:
```go
client := resty.New()
resp, err = client.R().
	SetBody(user).
	SetResult(&AuthSuccess{}).
	ForceContentType("application/json").
	Post("https://example.com/login")

fmt.Println(err, resp)
```

**Comment by Snax1210** [comment]
In other words, could we add _ForceContentType_("application/json") to _SetResult_(&AuthSuccess{}) so that you don't have to consider the type of response header when mapping to structs

**Comment by jeevatkm** [comment]
When you set the `ForceContentType("application/json"),`, then Resty uses this content type value when Unmarshalling the response body, not the response header value.
