### ISSUE TITLE
How to preserve case for request headers?

### ISSUE THREAD

**Issue by sudo-suhas** [go-resty/resty#86]
Golang calls [`CanonicalMIMEHeaderKey`](https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey) on headers and this does not preserve case. Something like `Channel_Name` gets changed to `Channel_name`. I am aware of the fact that HTTP headers are supposed to be case insensitive according to specification. However, I need to be able to send headers with specific case for consuming some external API. Would it be possible to provide a way to pass raw headers or preserve header name case for a request? Raw headers which preserve case can be created as follows:
```go
hdr := http.Header{
	"Channel_Name": []string{"WEB_DIRECT"},
}
```

Right now, I am doing a horrible hack using `SetPreRequestHook` to achieve this.

**Comment by jeevatkm** [comment]
Yes, you're correct. HTTP header is case insensitive as per spec. However your example header doesn't follow the spec completely. 

**For eg.:** 

You're not using `-` as word delimiter, other then `-` will be treated as single word.  Technically `Channel_name` is correct value as a `Canonical` key. I believe this is applicable to any programming language as per RFC.

On the server side, header can be retrieved in any `case`. It is applicable to any programming. I'm not sure why your external API is deviating from RFCs.

**Sample program to demonstrate:**
```go
package main

import (
	"fmt"
	"net/http"

	"gopkg.in/resty.v0"
)

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "Raw Headers:")
	fmt.Fprintln(w, r.Header)
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Headers:")
	fmt.Fprintln(w, "Channel-Name1 (Canonical):", r.Header.Get("Channel-Name1"))
	fmt.Fprintln(w, "channel-name1 (lowercase):", r.Header.Get("channel-name1"))
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Channel_Name2 (Canonical):", r.Header.Get("Channel_name2"))
	fmt.Fprintln(w, "channel_name2 (lowercase):", r.Header.Get("channel_name2"))
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Channel-Name3 (Canonical):", r.Header.Get("Channel-Name3"))
	fmt.Fprintln(w, "channel-name3 (lowercase):", r.Header.Get("channel-name3"))
	fmt.Fprintln(w, "")
}

func main() {
	go func() {
		http.HandleFunc("/sample", handler)
		http.ListenAndServe(":8080", nil)
	}()

	resp, _ := resty.R().
		SetHeader("Channel-Name1", "my channel value 1").
		SetHeader("Channel_Name2", "my channel value 2").
		SetHeader("channel-name3", "my channel value 3").
		Get("http://localhost:8080/sample")

	fmt.Println(resp.String())
}
```

**Output:**

```
Raw Headers:
map[User-Agent:[go-resty v0.13 - https://github.com/go-resty/resty] Channel-Name1:[my channel value 1] Channel-Name3:[my channelvalue 3] Channel_name2:[my channel value 2] Accept-Encoding:[gzip]]

Headers:
Channel-Name1 (Canonical): my channel value 1
channel-name1 (lowercase): my channel value 1

Channel_Name2 (Canonical): my channel value 2
channel_name2 (lowercase): my channel value 2

Channel-Name3 (Canonical): my channel value 3
channel-name3 (lowercase): my channel value 3
```

My suggestion is check with your external API support. Or Use your hack of `SetPreRequestHook`.

**Comment by sudo-suhas** [comment]
The external API does not follow spec and there's not much I can do about it.
 Thanks anyway.

**Comment by jeevatkm** [comment]
Understood. Thanks.

**Comment by mike-atlas** [comment]
For APIs that do not use canonical header names you can also get around this by setting the value on the Headers object directly Headers is just a map[string][]string

For instance we are hitting an external api that requires a header called "DevKey" - you can set it on the resty Request with:
`request.Headers["DevKey"] = []string{"the_dev_key_value"}`

Directly setting it into the map bypasses the canonization of the header. This is still a hack, but (maybe?) slightly easier to follow than one using `SetPreRequestHook`

**Comment by rew1nter** [comment]
> For instance we are hitting an external api that requires a header called "DevKey" - you can set it on the resty Request with:
request.Headers["DevKey"] = []string{"the_dev_key_value"}

This would be very nice if resty had implemented a method for non canonical header setting like this, since the stdlib doesn't provide a feasible way to do it

**Comment by jeevatkm** [comment]
@rew1nter refer to this https://github.com/go-resty/resty/issues/809#issuecomment-2267371964
