### ISSUE TITLE
digest: algorithm is not supported

### ISSUE THREAD

**Issue by fuhoo** [go-resty/resty#861]
code:
	c := resty.New()
	_, err := c.R().
		SetDigestAuth("admin", "admin@123").
		Get("http://192.168.1.196/ISAPI/ContentMgmt/InputProxy/channels")
	if err != nil {
		fmt.Println(err)
	}

Response headers:
HTTP/1.1` 401 Unauthorized
Date: Thu, 30 May 2024 17:28:44 GMT
Server: web
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval'
X-XSS-Protection: 1
Strict-Transport-Security: max-age=31536000;includeSubDomains
X-Content-Type-Options: nosniff
Content-Length: 142
Content-Type: text/html
Connection: close
WWW-Authenticate: Digest realm="DS-TCG405-E", domain="::", qop="auth", nonce="4d6b493452444d335130553659324534597a41304f47493d", opaque="", algorithm="MD5", stale="FALSE"
X-Appweb-Seq: 193970

algorithm="MD5" could not be recognized,
May I ask why C.LGorithm doesn't use strings.Trim？

**Comment by jeevatkm** [comment]
@fuhoo, thanks for reaching out. I'm sorry, but I did not understand the question.

> algorithm="MD5" could not be recognized,
> May I ask why C.LGorithm doesn't use strings.Trim？

Can you explain the problem in more detail?

**Comment by fuhoo** [comment]
Thank you for your reply. I tried using the latest version v2.15.1 and this problem has been solved.

**Comment by jeevatkm** [comment]
I see, thanks. What was the Resty version you tried before?
