### ISSUE TITLE
Expose response reader without reading response

### ISSUE THREAD

**Issue by perdasilva** [go-resty/resty#87]
I would like to get access to the response reader without the response first being read by resty. This would allow me to stream (e.g. to stdout) the response as it comes, rather than resty buffering it until it finishes.

**Comment by jeevatkm** [comment]
@perdasilva Thanks for creating an issue, once done I will ping you.

**Comment by jeevatkm** [comment]
@perdasilva I would like to know how soon you need this feature. Based on that I will plan it. Please let me know.

**Comment by adeanzan** [comment]
@jeevatkm - I am also interested in this feature and need it to continue with a project I'm working on.

**Comment by jeevatkm** [comment]
@adeanzan Thank you

**Comment by perdasilva** [comment]
ASAP would be great. As it is now, we are mixing b/w resty and net/http. Would be nice to just rely on resty ^^

**Comment by perdasilva** [comment]
Thx for picking this feature up ^^

**Comment by jeevatkm** [comment]
@perdasilva @adeanzan Thanks, understood. Once branch is ready I will ping you. So that you can try before merging into master.

**Comment by jeevatkm** [comment]
@perdasilva @adeanzan I have added this feature on branch [expose-response-body](https://github.com/go-resty/resty/tree/expose-response-body) of commit 0ff3d089f6ba7aa6e9a0760c46c85a02cbc4bccc

```
// Method available at Client and Request level
SetDoNotParseResponse(bool)
```
To get the body `io.ReadCloser` call `response.RawBody()`

Please refer to methods godoc. I look forward to feedback and improvements.

**Comment by jeevatkm** [comment]
@perdasilva @adeanzan Did you get a chance to try it out? Awaiting your feedback then I will merge it master.

**Comment by adeanzan** [comment]
@jeevatkm Just gave it a try and it worked great! I appreciate the quick implementation.

**Comment by jeevatkm** [comment]
@adeanzan Thanks for the feedback.

**Comment by perdasilva** [comment]
Shit dude, I'm so sorry - I totally missed your tag on the previous message. Thank you for implementing the change!!!

**Comment by jeevatkm** [comment]
That's okay @perdasilva. Give it try and let me know, its currently on master; not yet released.
