### ISSUE TITLE
Use with oauth2

### ISSUE THREAD

**Issue by olihey** [go-resty/resty#89]
I started playing around with resty and liking it so far.
I am talking to a REST API that uses oauth2 and up until now using net/http and golang/oauth2 worked but resty is much nicer.

My problem is refreshing the accessToken for oauth when it's expired. By using the oauth2.Client it's very simple but unfortunately setting the http.Client is not possible in resty.

So, 2 questions:
-  Is there a way to use oauth2.Client with resty
-  Is there an elegant way to handle expiring accessTokens in resty apart from checking the expire date before each call and refresh the token

**Comment by jeevatkm** [comment]
Currently no easy way to do it. @bak1an has finished the implementation of `http.RoundTripper` interface as a transport. It seems he is busy. I will take it to that closure.

Once #74 get merged into main track you can integrate oauth very seamlessly.

**Comment by jeevatkm** [comment]
I'm working on it. Let you know once done. Thanks.

**Comment by jeevatkm** [comment]
`http.RoundTripper` implementation is on this branch https://github.com/go-resty/resty/tree/bak1an-roundtripper

Please give it try and share your feedback then I will merge it to master.

For example: 
```go
// Create oauth client 
// ...
oauthClient := conf.Client(ctx, token)

// Create resty client
restyClient := resty.New()

// http://godoc.org/golang.org/x/oauth2 implements `httpRoundTripper` interface
// Set the oauthClient transport
restyClient.SetTransport(oauthClient.Transport)

// Now you can use resty :)
```

**Comment by jeevatkm** [comment]
Solved by #91

**Comment by olihey** [comment]
Tested and it works beautifully. Thanks and awesome job, really loving resty!!!!

**Comment by jeevatkm** [comment]
I'm very glad, thank you for your appreciation.

For this enhancement I gave only final touch. Credit goes to @bak1an for the PR.

**Comment by arekkas** [comment]
This does not work because `SetTransport` expects `*http.Transport` but `oauth2.Config.Client().Transport` implements `*oauth2.Transport` which in turn is incompatible with `*http.Transport`. Why isn't it possible to set the `http.Client` in resty? Wouldn't that resolve many issues around e.g. retry and also be the idiomatic Go way?

**Comment by jeevatkm** [comment]
@arekkas please use v1 or master (edge) for this feature. It is recently added. Thank you.

Can you please explain? What is the issue you're facing with retry? http.Client does not provide retry option; resty provides backoff mechanism and conditional option too.

**Comment by arekkas** [comment]
That was a quick response, awesome! :) I see, then I'll upgrade to v1. I think using `http.RoundTripper` is already all I need, thank you!

**Comment by jeevatkm** [comment]
@arekkas you're welcome.
