### ISSUE TITLE
Can it support color output?

### ISSUE THREAD

**Issue by silky1313** [go-resty/resty#891]
![image](https://github.com/user-attachments/assets/384fcfc6-dd2d-48ce-8b36-b6e3055c909d)
Like this，I think we can add a color to the Message。

**Comment by jeevatkm** [comment]
@silky1313 Thanks for reaching out. 

Are you referring to the colored logger? if yes, then Resty provides custom logger support; users could set their colored logger into Resty via 
https://pkg.go.dev/github.com/go-resty/resty/v2#Client.SetLogger

**Comment by silky1313** [comment]
ok, i wiil try, thank you!
