### ISSUE TITLE
Filesystem sync issue with saveResponseIntoFile middleware

### ISSUE THREAD

**Issue by bd-nweinstein** [go-resty/resty#927]
We encountered an [issue](https://github.com/jfrog/terraform-provider-artifactory/issues/858) in the terraform artifactory provider where a checksum check on the downloaded file was flaky in our kubernetes environment.

https://github.com/jfrog/terraform-provider-artifactory/blob/029347769aeaef4546e38b45558784cde4b718e9/pkg/artifactory/datasource/artifact/datasource_artifactory_file.go#L254

We suspect that this is because there is no call to `outfile.Sync()` here:
https://github.com/go-resty/resty/blob/c34e4605f4d5a775371be242ba0debb2705eb6d2/middleware.go#L585

The data is not guaranteed to have been flushed to the filesystem before the checksum check. In situations where the filesystem is network mounted or otherwise slower than expected, this can cause issues like the one we encountered.

Would it make sense to always sync the file to the filesystem before the middleware function returns?

**Comment by jeevatkm** [comment]
@bd-nweinstein Thanks for reaching out.

Generally, we don't need to explicitly call `.Sync` since Go write calls are direct syscalls. However, it is okay to add `.Sync`.

Are you interested in submitting PR? Otherwise, I will take care of it.

**Comment by bd-nweinstein** [comment]
This was a false alarm/misdiagnosis. I think we traced this down to a race condition between two downloads to the same file path.
