### ISSUE TITLE
Next planned release?

### ISSUE THREAD

**Issue by sudo-suhas** [go-resty/resty#94]
Hey @jeevatkm, I was looking through [changes not yet released](https://github.com/go-resty/resty/compare/v0.13...master) and I am interested in 6d8c785(adding support for registering external JSON library). Could you please let me know when you are planning to make a release with this feature? Also, do you think it is possible to handle this using build tags? That's how [gin does it](https://github.com/gin-gonic/gin#build-with-jsoniter).

**Comment by jeevatkm** [comment]
I'm planning to make `v1.0` release by this weekend.

For registering external JSON library, refer to https://github.com/go-resty/resty/issues/76#issuecomment-314015250

**Comment by sudo-suhas** [comment]
Great! Thanks again @jeevatkm.

**Comment by jeevatkm** [comment]
Thank you @sudo-suhas.
