### ISSUE TITLE
Cookie Jar error

### ISSUE THREAD

**Issue by thuongtin** [go-resty/resty#96]
<img width="600" alt="screen shot 2017-09-14 at 10 28 47 am" src="https://user-images.githubusercontent.com/3460591/30410844-9750e4f6-9937-11e7-8686-e3ad4bbc77fd.png">

**Comment by jeevatkm** [comment]
@thuongtin What I see from screenshot? Resty is in Debug mode and its logging request & response details.

I don't see a relation of Cookie Jar here, Could you please describe the problem with more detail? 
Screenshot is not helpful that much.

At least to begin with; such as:
* How you're using Resty?
* What is the nature of your server application?
* What are all the settings you're using in resty?

It would help me to understand the problem.

**Comment by jeevatkm** [comment]
@thuongtin Due to no response, I'm closing this one, if you have an input, feel free reopen or create a new issue.

**Comment by hikyaru-suzuki** [comment]
I had same problem but that is solved by this setting.

https://pkg.go.dev/github.com/go-resty/resty/v2#Client.SetCookieJar
> For Example: sometimes we don't want to save cookies in api contacting, we can remove the default CookieJar in resty client.
```go
client.SetCookieJar(nil)
```

My use case is a large number of requests are sent sequentially to the API that sets the cookie. Then the cookie will continue to be added and will be rejected from the API with 431 header too long.
