### ISSUE TITLE
Content-Type overrides in middleware.parseRequestBody method

### ISSUE THREAD

**Issue by Roma7-7-7** [go-resty/resty#97]
I'm going to manually set Content-Type header via resty.Request.SetHeader method but default.DefaultClient uses middleware.parseRequestBody before each request and Content-Type is overriding there.
I believe it would be better to keep original Content-Type.

**Comment by jeevatkm** [comment]
@Roma7-7-7 Resty behavior: `Content-Type` automatically set for Form (url-encoded and multipart involves content-type with boundary values). For other scenarios it will set only when user is not provided the content-type.

I had a look on your PR, it seems not a best spot to that. Can you please describe your usage? so that we can do it at appropriate spot.

**Comment by Roma7-7-7** [comment]
Hi @jeevatkm , I have very simple case when I need to execute GET request with Content-Type=application/json but when I do it resty lib removes this header and as result I'm receiving 415 Unsupported Media Type response.
Attached is simple script that illustrate it. You could use this script to trace incoming http requests https://github.com/Roma7-7-7/commons/blob/master/http_trace.py 
I would expect that if user manually set content-type then it should be same even if resty lib could provide better value
[main.zip](https://github.com/go-resty/resty/files/1310548/main.zip)

**Comment by jeevatkm** [comment]
@Roma7-7-7 Thanks for the details. So on GET request, resty removes the Content-Type header. Let me analyze it and get back.

FYI, typically `Content-Type` header is used when request contains body; otherwise `Accept` header should be used.

**Comment by Roma7-7-7** [comment]
@jeevatkm , agree, but unfortunately there are a lot of legacy code that we cannot modify and for some reasons it expects this header for all types of request.

**Comment by jeevatkm** [comment]
@Roma7-7-7 Okay, I understand. I will be closing your PR.  Not to worry, I will analyze and address this issue. Thank you.

**Comment by jeevatkm** [comment]
@Roma7-7-7 I have removed the check. Try it out from master. It should work now.

This is will be released in v1.0

**Comment by Roma7-7-7** [comment]
@jeevatkm Thank you, for looking at this

**Comment by jeevatkm** [comment]
You're welcome @Roma7-7-7
